### ISSUE TITLE
Todo list for v0.2.0 release

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#105]
I thought it would be good to compile a little list with things that need to be done to release a clean version.

- [x] Documentation and examples for the `autogenerate` module and some other 'stuff' (#77 #79 #86) @jbusecke
- [x] Add example notebook using `face_connections` with MITgcm LLC grid

Please let me know what else people think needs to be done before the release.

Closes #122

**Comment by rabernat** [comment]
Good idea Julius. Let's add some more examples to the example gallery that show off the new features. I added one of my own to your list.

**Comment by rabernat** [comment]
Ah I spoke to soon about the release. I should add my ecco example notebook.

**Comment by rabernat** [comment]
Face connection examples added in #124.
