### ISSUE TITLE
xgcm operations change chunk size?

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#107]
This might be a naive question, but is it necessary that xgcm operations like `diff` and `interp` change the chunksize along the used dimension to 1? I just stumbled across this and had to rechunk my dataset.

Here is a short example that reproduces the behaviour:
```
import numpy as np
import xarray as xr
from xgcm import Grid
from dask.array import from_array


ds = xr.Dataset(
        {'data_c': (['XC'], from_array(np.random.rand(9), chunks=9)),
         'data_g': (['XG'], from_array(np.random.rand(10), chunks=10))},
        coords={'XC': (['XC',], np.arange(1,10),
                        {'axis': 'X',
                         'standard_name': 'x_grid_index',
                         'long_name': 'x-dimension of the grid',
                         'c_grid_dynamic_range': '2:8'}),
                'XG': (['XG',], np.arange(0.5,10),
                         {'axis': 'X',
                          'standard_name': 'x_grid_index_at_u_location',
                          'long_name': 'x-dimension of the grid',
                          'c_grid_dynamic_range': '3:8',
                          'c_grid_axis_shift': -0.5})
        })
ds
```
<xarray.Dataset>
Dimensions:  (XC: 9, XG: 10)
Coordinates:
  * XC       (XC) int64 1 2 3 4 5 6 7 8 9
  * XG       (XG) float64 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5
Data variables:
    data_c   (XC) float64 dask.array<shape=(9,), chunksize=(9,)>
    data_g   (XG) float64 dask.array<shape=(10,), chunksize=(10,)>

```
grid = Grid(ds)
grid
grid.diff(ds.data_c,'X')
```
<xarray.DataArray 'sub-e029d03638632d37d2e9e464d41c935f' (XG: 10)>
dask.array<shape=(10,), dtype=float64, chunksize=(1,)>
Coordinates:
  * XG       (XG) float64 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5

**Comment by rabernat** [comment]
The xarray representation doesn't show you to full chunk size. To get the full chunk structure, you need to examine the dask object (`.data.dask.chunks`).

The chunks are not size 1--they are nonuniform. https://github.com/dask/dask/issues/3535 describes this in more detail.

I think it would be good to add a rechunk step at the end of these operations and then also possibly fuse them into a single task.

**Comment by jbusecke** [comment]
Interesting! But a bit over my head TBH. I would have to read further into it, but if this makes finite differences faster, I am all IN!
