### ISSUE TITLE
Support SGRID conventions

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#109]
Since we started working on xgcm, a new convention for staggered grid netCDF metadata has emerged:
http://sgrid.github.io/sgrid
(We learned about this thanks to @vrx- in #108.)

Reading through the document, I am pleased to see a huge amount of conceptual overlap between the sgrid and xgcm data models. This is a good thing! It means that there is one clear solution to this problem, and multiple independent groups have more-or-less converged on it.

We need to update xgcm to understand sgrid conventions (like it currently does with comodo conventions) so it can automatically build a Grid object based on just the sgrid metadata. This will require a few changes under the hood (see #108), bur should be doable. 

I wanted to ping some sgrid developers (@hrajagers, @rsignell-usgs) to get their thoughts on how we could work together. Particularly useful would be if you could point us towards some example netCDF files from real models that implement the conventions.

**Comment by vrx-** [comment]
The [Texas-Louisiana Regional ROMS Shelf Model](http://barataria.tamu.edu:8080/thredds/catalog.html?dataset=txla_hindcast_agg) ( @hetland)

**Comment by hrajagers** [comment]
Hi Ryan, Sorry for the slow ping. Following the success of the [UGRID](http://ugrid-conventions.github.io/ugrid-conventions/) we drafted SGRID as a lightweight meta data layer to add staggered grid information to NetCDF files using a syntax very similar to that of UGRID. Although we received several positive reactions, the uptake is slow. It's time for some tools to start leveraging the additional meta-data, so I'm glad you're reaching out.

We've added the meta-data to map-data of Delft3D in NetCDF. An example can be found at
http://opendap.deltares.nl/thredds/catalog/opendap/deltares/Delft3D/netcdf_example_files/catalog.html?dataset=varopendap/deltares/Delft3D/netcdf_example_files/trim-westernscheldt_sph.nc
Unfortunately that example file still contains some -999 values for the X and Y coordinates which should be missing values.

**Comment by rsignell-usgs** [comment]
The [USGS COAWST forecast results](https://gamone.whoi.edu/thredds/catalog/coawst_4/use/fmrc/catalog.html?dataset=coawst_4/use/fmrc/coawst_4_use_best.ncd) are also SGRID compliant.

**Comment by hrajagers** [comment]
In addition: SGRID describes what xgcm refers to as "simple grids". We don't address the connectivity of multiple structured grid tiles, but we did look into this topic for unstructured grids. An initial text on this topic was drafted at https://publicwiki.deltares.nl/display/NETCDF/Mosaics+of+meshes. We have more recently revisited this topic internally at Deltares for connecting 1D and 2D hydraulic models (laterally, longitudinally, and vertically). It would be interesting to come to a broader accepted convention for this which would consistent across grid specifications. An existing convention for _structured grid_ mosaics is [GridSpec](https://ice.txcorp.com/trac/modave/wiki/CFProposalGridspec).

**Comment by rabernat** [comment]
Thanks a lot for the feedback!

With xgcm, we are very interested in following standards (rather than making up new metadata conventions). That's why we followed the [comodo spec](http://pycomodo.forge.imag.fr/norm.html), which was well established (if not widely adopted) at the time we started coding. Have you had any interaction with those folks?

To actually implement this, what is required is to write some functions that parse the SGRID metadata. These could be modeled after the comodo mmodule:
https://github.com/xgcm/xgcm/blob/master/xgcm/comodo.py

In particular, we need two functions:
- `get_all_axes(ds)`: returns a list of axis names (perhaps "node dimensions" in SGRID speak)
- `get_axis_positions_and_coords(ds, axis_name)`: returns a dictionary whose keys are "position names" (`{'center' ,'left' ,'right', 'outer', 'inner'}`) and whose values are the `xr.DataArray`s corresponding to the coordinates along each axis.

One challenge I see is that SGRID doesn't explicitly define the notion of an "axis" the way that comodo does. The notion of an axis is central to xgcm's data model. In the SGRID [2D grid example](http://sgrid.github.io/sgrid/#d-grid), `icell` and `igrid` both belong to the same "axis", since the represent positions along the same direction of an orthogonal coordinate system. In parsing these files, we will need to pick a name for this axis somehow. (The obvious name to me is simply "i".) *Any suggestions about how to do this?*

Most importantly, *is anyone interested in working on this?* We are actively trying to grow the community of xgcm developers (see #104).

**Comment by rabernat** [comment]
More generally, all these conventions should be supported:
http://www.earthsystemmodeling.org/esmf_releases/last_built/ESMF_refdoc/node3.html#SECTION03028000000000000000

**Comment by dcherian** [comment]
https://github.com/VACUMM/xoa/blob/233540257af6932c781585e33b75b173c1949ce7/xoa/cf.py#L110-L120

looks related (not sure if it is actually doing SGRID)

cc @stefraynaud

**Comment by mgrover1** [comment]
We are having a meeting related to this issue on Friday!

[Here is a link to the event](https://calendar.google.com/event?action=TEMPLATE&tmeid=NGNlMGxmamJ2NXRnN2hycG8yb2IxYTZlNWsgbWdyb3ZlckB1Y2FyLmVkdQ&tmsrc=mgrover%40ucar.edu)

Within the event, you will find a document which will serve as the agenda - feel free to make edits to that!

**Comment by rabernat** [comment]
Hi @mgrover1! Unfortunately I was on vacation last week and was unable to attend. How did it go?

**Comment by mgrover1** [comment]
It went well - [here are the notes from our discussion](https://docs.google.com/document/d/1NNTtf5YSFQZyQFzqT_SDfOBqBTYD0os71iN3ScfTAds/edit?usp=sharing) and there is a continued discussion planned in https://github.com/xarray-contrib/cf-xarray/issues/220, focusing on coming up with use cases and how to design the api in cf-xarray

**Comment by dcherian** [comment]
@rabernat It'd be nice to hear of use-cases where this would be useful. It's hard to decide what goes in cf-xarray vs what goes in xgcm.

**Comment by rabernat** [comment]
> It'd be nice to hear of use-cases where this would be useful.

The main use case is to automatically build a `xgcm.Grid` object for an xarray dataset which contains sgrid metadata.

**Comment by raehik** [comment]
During a short hackathon at the end of September I proposed as a project adding support in xGCM for data using SGRID conventions. I was lucky to have 3 PhD students from Cambridge join me:

  * Jonathan Rosser @JonathanRosser
  * Mala Virdee @mvirdee
  * Natalie Yao @Nataliey

We spent a lot of time discussing how xGCM and SGRID conceptually lay out their grids (I'm indebted to them all for help with visualizing!). We apparently faced a similar problem to the one @rabernat points out in https://github.com/xgcm/xgcm/issues/109#issuecomment-408867668 :

> One challenge I see is that SGRID doesn't explicitly define the notion of an "axis" the way that comodo does. [...] In parsing these files, we will need to pick a name for this axis somehow.

If I remember correctly, when turning SGRID variable locations into xGCM internal metadata, we found that we had two choices for how to orient our axes. Perhaps we didn't fully understand how the grid topology is defined: where do the coordinates point to in a given cell, an edge, face or node? I think you can do any, which seems to be different to (more flexible than?) xGCM.

Most of these topology issues crop up when declaring a 3D grid, which were a point of discussion on the SGRID spec. More on a related issue: https://github.com/sgrid/sgrid/issues/20 . But probably I should focus on simpler topologies first.

Another smaller point: we had trouble finding example data using SGRID conventions. Many of the links on https://github.com/xgcm/xgcm/issues/108 no longer work or I don't understand how to access. Would anyone have any recommendations for *small-ish staggered grid datasets tagged with SGRID metadata?*

In the meantime I'm wrapping my head around SGRID's model and taking a look at [pysgrid](https://github.com/sgrid/pysgrid).

**Comment by jatkinson1000** [comment]
Hi All, I've been working on this with @raehik at the ICCS and we have started making some headway with reading in SGRID data and extracting grid information. However, we have a few questions that we need answering before we go further. The answers aren't immediately obvious to us from looking at the xccm code and centre around how data sets and variables are read in and represented.

- How much needs to be extracted/inferred from sgrid data?
- How does xgcm decide what coordinates a variable uses?

We were therefore hoping to arrange a discussion with someone who understands the inner workings of xgcm (perhaps @rabernat and @jbusecke ) to go over what we have done so far and how to proceed.

The code written so far is in a [forked repo](https://github.com/jatkinson1000/xgcm/tree/sgrid), though I am still making some updates.

I'd also re-emphasise that another thing we need to do is obtain a variety of sgrid datasets to use during testing and development to ensure we catch all possible ways sgrid can be stored and handle any edge cases.

**Comment by rabernat** [comment]
Hi Folks! Sorry for the slow responses on this issue. I just saw the email from Dominic pinging on this. I agree that a call will be a good way to move forward. Will follow up over email.

**Comment by hrajagers** [comment]
Some comments on SGRID. SGRID was primarily developed as a means to define staggered gridded data on a structured mesh (similar to UGRID for unstructured meshes) as a complement to everything CF conventions already do. So, SGRID doesn't redefine standard names or axis attributes for identifying coordinate directions; CF already covers that. We tried to stay away from the concepts of first and second dimension since those concepts may depend on the programming language (unless you define them in terms of fastest (inner) dimension and slower (outer) dimension. Since the vertical dimension is frequently defined in environmental models using sigma or s-coordinates between surface and bottom layers, we included the option of a separate vertical_dimensions concepts perpendicular to a 2D SGRID base mesh. The 3D SGRID is mostly there for generalization to general homogeneous 3D models with similar type of gridding in all directions.

**Comment by hetland** [comment]
I agree with the excellent summary by @hrajagers. A comment and an addition:

 - One way to think of S-GRID conventions, is (as Bert says) as an extension of the CF conventions. So, it's just attributes that need to be read in to specify how to set up the xgcm grid object. I suspect that if this information is absent, reasonable guesses could be made based on the shapes/sizes of the various coordinates, but I think that path is pretty difficult, since there are so many ways to get it wrong.
 - I think that 3D grids can be broken down into 2D horizontal and 1D vertical grids in every single use case I can think of.  So, I suggest always separating horizontal and vertical grid structure information. An s-grid compliant file will have information on both separately.

**Comment by jatkinson1000** [comment]
Thanks for the input.
- @rabernat a meeting will be good. Hopefully @jbusecke and tom will reply with availability soon.

- @hrajagers and @hetland we're pretty happy with what SGRID is, but you may be able to help with a couple of the practicality questions:
  - According to SGRID the only thing that _has_ to be provided is the dimension of cells and nodes. Coordinates are entirely optional. However, how likely is it that data would ever be provided without coordinates - does this need handling?
  - Similarly, coordinates could be provided as an optional mix of node, face and/or edge. This presents several different possible combinations (for 2D: face+node, edge+node, edges only etc.) that would all need logic to be checked for and handled. How likely is it that a dataset will come with different versions of these, however, or would we usually expect to see one type (e.g. faces+nodes)?
  - With the vertical dimension (on a 2D grid) SGRID only takes the dimension, no coordinates. However, xgcm expects to see coordinates when defining grids from a dataset. This could be handled by assigning a 'normalised coordinate' [0, 1] to the vertical dimension with the extraction of sigma or s-coords (or other) left as a 'variable' to be processed later in the code. Is this sensible or would there be a better way to handle?
  - Regarding axes and dimensions we understand that SGRID avoids being explicit about this - indeed there isn't really such a concept for unstructured meshes. However, the concept of separate 'axes' is key to the way xgcm interprets data as far as I can see, so there has to be an interface where we decide on some 'name' for each (see the [forked repo](https://github.com/jatkinson1000/xgcm/tree/sgrid) referred to above).
  - Finally, if you have some simple example SGRID datasets this would be really useful with handling these possibilities and testing the code.

A meeting to discuss these concepts and for people to share what they are well versed in (xgcm, SGRID etc.) and discuss will be useful. Thanks.

**Comment by hetland** [comment]
I'll leave it to the folks who wrote the SGRID convention to give the final word on this, but regarding your first point, I think that the SGRID conventions are an extension of the CF conventions; the _only_ thing the SGRID conventions do is define the relationship between the index and offset in a staggered grid. I.e., is u<sub>i</sub> (a velocity) to the left or to the right of T<sub>i</sub> (a tracer)? Thus I think it is possible to be SGRID compliant, but not CF compliant. Your questions regarding specifications of coordinates fall under CF conventions, so I think it's fair to assume this information is available, even if not required under SGRID.

**Comment by jbusecke** [comment]
Hey everyone, sorry for the slow response here. Thank you for working on this important feature for xgcm. I just replied via email re availability for a meeting. 

> Finally, if you have some simple example SGRID datasets this would be really useful with handling these possibilities and testing the code.

I think that getting an example dataset (ideally *before* that meeting) would be tremendously helpful. I am personally not aware of such a dataset, but maybe someone here has pointers?

From my quick read here it seems like we might have a dataset that is both CF and SGRID compliant to properly parse that information? If that is the case I wonder if there is some overlap with [cf-xarray](https://github.com/xarray-contrib/cf-xarray) and whether we can leverage some of their logic in this approach.

**Comment by hrajagers** [comment]
SGRID indeed allows for the definition of an abstract staggered mesh without coordinates. Most of UGRID also allows for an abstract unstructured mesh, but the UGRID conventions specify that the node_coordinates need to be specified. SGRID indeed doesn't do that. The main reason for this difference is that there are [1] staggered structured mesh models that only represent themselves using the "cell/face centre" coordinates (assuming that the interfaces are located halfway between the indicated points) as well as [2] staggered structured mesh models that use the nodes of the mesh to represent the outlines of the cells/faces (typically assuming that the cell value is in the "middle" of that area). To avoid introducing a bias for one or the other type of model, we did not specify either node_coordinates or face_coordinates as required. For unstructured meshes it's more natural to start from the nodes. This has resulted in a slight difference between UGRID and SGRID, but both conventions rely on the CF conventions to link the model to a place on earth. SGRID and UGRID by themselves could define staggered (un)structured meshes in an arbitrary N-dimensional space.

Although one could write SGRID or UGRID data that is not CF compliant, I think that very few _environmental_ models will only write SGRID/UGRID compliant files without being also CF compliant. A reader may check on a pair of SGRID and CF conventions specified in the Conventions attribute to be a bit more certain about the intended compliancy. The standard names and axis attribute of the CF conventions will indicate which geographical directions are concerned. In general the staggered mesh may not be rectilinear, so even though a 2D planar mesh will have X and Y (or longitude and latitude) coordinates, there may not be able to speak of an X or Y mesh direction.

Maybe you can check
http://opendap.deltares.nl/thredds/dodsC/opendap/deltares/Delft3D/netcdf_example_files/trim-westernscheldt_sph.nc
which has an SGRID compliant grid variable, but I just noticed that it doesn't include SGRID in the global Conventions attribute and the standard_name 'latitude' was misspelled. I'll try to update the file next week.

```
grid
cf_role: grid_topology
topology_dimension: 2
node_dimensions: MC NC
face_dimensions: M:MC (padding: low) N:NC (padding: low)
face_coordinates: XZ YZ
node_coordinates: XCOR YCOR
vertical_dimensions: SIG_LYR:SIG_INTF (padding: none)

```

**Comment by rsignell-usgs** [comment]
@jbusecke , this [USGS COAWST ocean forecast model](https://geoport.usgs.esipfed.org/thredds/catalog/coawst_4/use/fmrc/catalog.html?dataset=coawst_4/use/fmrc/coawst_4_use_best.ncd) (using the ROMS model for circulation) is SGRID compliant.

``` 
import xarray as xr
url = 'http://geoport.usgs.esipfed.org/thredds/dodsC/coawst_4/use/fmrc/coawst_4_use_best.ncd'
ds = xr.open_dataset(url)
```

**Comment by jbusecke** [comment]
Fantastic. Thanks @rsignell-usgs. Ill try to get into that dataset before the meeting!

Thanks for the explanation @hrajagers. I indeed think that xgcm's data model usually assumes 

> [1] staggered structured mesh models that only represent themselves using the "cell/face centre" coordinates (assuming that the interfaces are located halfway between the indicated points)

Even though an xgcm axis is linked to a set of xarray dimensions, none of the operations actually require values to be present. Instead the logic is based on e.g. differencing neighboring pairs of grid positions. To yield physical quantities these basic operations are then multiplied with [Grid Metrics](https://xgcm.readthedocs.io/en/latest/grid_metrics.html). For example:

```python
grid.diff(da, 'X')/dx
```
approximates the derivative of da along the axis `X`. 

Maybe this constrains a bit the logic needed to parse the SGRID information?

Happy to chat more about this as I spin back up on xgcm next week.

**Comment by rsignell-usgs** [comment]
Note I've updated the COAWST dataset info above to reference an SGRID 0.3 kerchunked dataset instead of thredds SGRID 0.1.

**Comment by TomNicholas** [comment]
We had a meeting about supporting SGRID conventions via a reader for xGCM today, [notes here](https://docs.google.com/document/d/1M23VyRsOtDquf1NCcwTWYuKvCwohXha6nBVMhgBzqi4/edit?usp=sharing) (@dcherian )

**Comment by jbusecke** [comment]
Thanks everyone for attending the meeting. 

Few quick follow up:
The `coords` input is confusing. I opened #555 to suggest a renaming. I also believe that providing coordinates instead of dimensions should have raised an error, but in the current setup this [check](https://github.com/xgcm/xgcm/blob/1e22b27af505eb52b9e24d296bfdc1b32eb74bac/xgcm/grid.py#L1330-L1340) is only applied to user provided input, not the input from e.g. the comodo or sgrid parser. In #557 (WIP) we will implement this check on the level of the `Axis` object which should fix this behavior. 

I will see if I can follow up with an example using @raphaeldussin [blog post](https://raphaeldussin.medium.com/modern-python-tools-for-the-roms-ocean-model-bfca8642db01) for how to manipulate the data to fit into xgcms data model. I think of ROMS output as a very complex (yet common!) edge case for sgrid+xgcm. If we can get the easier Delft example to work first, that will be a great step forward.

**Comment by jatkinson1000** [comment]
A useful meeting - a few comments came up ([see notes above](https://docs.google.com/document/d/1M23VyRsOtDquf1NCcwTWYuKvCwohXha6nBVMhgBzqi4/edit?usp=sharing)) that relate to SGRID rather than xgcm that we wanted to discuss with @hrajagers @hetland etc. I can raise these on the SGRID repo if you feel they are valid.

1: When trying to detect the `grid` variable in a dataset this has to be done in a slightly dodgy manner by looking for the `cf_role` attribute (could also use `topology_dimension` or `node_dimensions`). We felt that this would be better if the SGRID grid variable had a specific attribute explicitly identifying it as such, or had a standardised variable name. Is this something that could be implemented?

2: When extracting dimensions or coordinates we assume they are in the same order e.g.
```
    units:                1
    cf_role:              grid_topology
    topology_dimension:   2
    node_dimensions:      Xdim Ydim
    face_dimensions:      Xf:Xdim (padding: low) Yf:Ydim (padding: low)
    face_coordinates:     Xfcoord Yfcoord
    node_coordinates:     Xncoord Yncoord
```
But this does not seem to be a requirement. One could, in theory, have a dataset that looks like
```
    units:                1
    cf_role:              grid_topology
    topology_dimension:   2
    node_dimensions:      Xdim Ydim
    face_dimensions:      Yf:Ydim (padding: low) Xf:Xdim (padding: low)
    face_coordinates:     Xfcoord Yfcoord
    node_coordinates:     Yncoord Xncoord
```
Whilst unlikely it is allowed and would probably cause mess further down the line, could it be explicitly written into SGRID that all dimensions must be in the same order for all attributes of the grid variable? i.e. always `X Y Z` or `lat lon` etc.?

**Comment by rabernat** [comment]
> Could it be explicitly written into SGRID that all dimensions must be in the same order for all attributes of the grid variable?

Our attempt to implement SGRID is generating useful questions about the spec itself. Unfortunately we did not create SGRID and have no control over it. But we can propose changes over at https://github.com/sgrid/sgrid/issues.

**Comment by jatkinson1000** [comment]
Thanks for providing the data @rsignell-usgs, it has come useful in testing!
> `url = 'https://mghp.osn.xsede.org/rsignellbucket1/catalogs/ioos_intake_catalog.yml'`

However, I believe it is not SGRID compliant (at least not to current standards) as the face and node coordinates have a space between them after the colon where there should not be one e.g.
`xi_rho: xi_psi (padding: both)` should be
`xi_rho:xi_psi (padding: both)`.

Is this correct? If not more elaborate handling is required.

@TomNicholas I think I have finished code to read in dimensions from SGRID files so will push to my fork and submit a pull request for review shortly. Then we probably ought to write some test cases to check that I'm handling all possibilities correctly. @raehik can probably help me with this.
It would also be useful if you could share the ROMS dataset from the meeting with us for testing.

**Comment by rsignell-usgs** [comment]
@jatkinson1000 , I hope the code can handle a space after the colon since I think there might be quite a bit of this data out there in the wild from COAWST or ROMS.    

Also the 2D example from the SGRID 0.3 documentation has a space after the colon also:
https://sgrid.github.io/sgrid/#2d-grid

**Comment by jatkinson1000** [comment]
OK, I'll look to implement that before opening a pull request.

This might be somewhere where the SGRID documentation needs to be more clear about what formatting of the strings is/isn't acceptable.

**Comment by jatkinson1000** [comment]
Hi All, we're making progress with this and have got to the testing part. However, we're experiencing a few issues with discrepancies between dimension and coordinate names. We've done some reading and would appreciate advice from those perhaps more knowledgable in the area.

It seems to us that xgcm expects coordinates (as defined by `ds.coords`, where `ds` is an array dataset) to be a 1D vector that shares the name of its corresponding dimension.

After some digging this appears to be part of the CF conventions ([see here](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch01s02.html) or [here](https://web.archive.org/web/20160417032300/http://pycomodo.forge.imag.fr/norm.html#at-location-label)). So does xgcm assume that any datasets it reads are CF compliant?

Examining the our example datasets such as the deltares one provided by @hrajagers above in  https://github.com/xgcm/xgcm/issues/109#issuecomment-1309442394 which has CF in its `ds.conventions` this does not seem to be the case:
```
>>> ds.dims
Frozen({'MC': 193, 'NC': 168, 'M': 193, 'N': 168, 'SIG_LYR': 1, 'SIG_INTF': 2, 'KMAXOUT': 2, 'KMAXOUT_RESTR': 1, 'time': 25})
>>> ds.coords
Coordinates:
    XCOR           (MC, NC) float32 ...
    YCOR           (MC, NC) float32 ...
    XZ             (M, N) float32 ...
    YZ             (M, N) float32 ...
  * SIG_LYR        (SIG_LYR) float32 -0.5
  * SIG_INTF       (SIG_INTF) float32 0.0 -1.0
  * KMAXOUT        (KMAXOUT) int32 0 1
  * KMAXOUT_RESTR  (KMAXOUT_RESTR) int32 0
  * time           (time) datetime64[ns] 2014-01-01 ... 2014-01-02
```
Here the coordinate variables `XCOR` and `YCOR` are both 2D, not 1D, and do not share the names of the dimensions.

It's a similar case as far as I can tell with the coawst dataset from @rsignell-usgs 

If you can help us work out what we're missing that would be really useful, thanks.

**Comment by jatkinson1000** [comment]
Hi All, I think this is now almost ready to go in PR #559 
In addition to adding SGRID functionalities I've alos set up the groundwork for adding further metadata convention parsing functionality in the future.
Please do take a look and let me know any thoughts.
Looking forward to getting this added in!

**Comment by rsignell-usgs** [comment]
I guess this can be closed, right @jatkinson1000 ?

**Comment by jbusecke** [comment]
Thanks for the ping @rsignell-usgs. Closing this now. And a big +1 for real world examples!
