### ISSUE TITLE
latest rtd build failed

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#112]
I was excited to see the results of @jbusecke's new example (#106) in the online docs. Unfortunately the rtd build failed:
http://readthedocs.org/projects/xgcm/builds/7570337/

**Comment by raphaeldussin** [comment]
ok I think I know how to fix it

**Comment by jbusecke** [comment]
Oh shoot. Did I mess something up? Is there a way to test the rtd build as part of the ci?

**Comment by rabernat** [comment]
@raphaeldussin -- what is the fix you have in mind. It would be great to get these new docs up and proceed with the 0.2.0 release (see #105).

**Comment by raphaeldussin** [comment]
I thought it was similar to the problem we had with xmitgcm but it's not :(
I spoke too fast

**Comment by jbusecke** [comment]
I would be happy to look into this, but I cannot find any more detailed logs than the "FAILED" on there. Does anyone know where I could start diagnosing what is wrong?

**Comment by rabernat** [comment]
http://readthedocs.org/projects/xgcm/builds/7570337/ (I just triggered
another build)

I think the best long term solution would be to avoid building the docs on
RTD (which has become flaky in general) and build them instead on Travis.
This is what xarray now does:
https://github.com/pydata/xarray/blob/master/.travis.yml#L99-L101

**Comment by jbusecke** [comment]
Ok great. They are working for me now. That sounds like a good idea @rabernat. Should I open a new issue?

**Comment by rabernat** [comment]
It seems like it is magically fixed now! https://xgcm.readthedocs.io/en/latest/autogenerate_examples.html

Lets go ahead and release 0.2.0.

**Comment by jbusecke** [comment]
Ill close this then.
