### ISSUE TITLE
xgcm for plasma physics instead of atmospheric physics

### ISSUE THREAD

**Issue by TomNicholas** [xgcm/xgcm#113]
The tools you are building here look like they could be potentially useful for a much wider audience than just atmospheric physicists. Anyone who runs simulations which produce results on a staggered grid and with non-trivial topology could benefit, but I'm thinking specifically of plasma physicists from the magnetically-confined-fusion (MCF) community.

MCF physicists routinely run large-scale, 3D, multi-parallel, fluid-like models on meshes with complex curvilinear geometries, which have a range of topologies. All of these things are common with the atmospheric physics community. For example the widely-used code [BOUT++](https://boutproject.github.io/) has the ability to model [complex topologies](http://bout-dev.readthedocs.io/en/latest/user_docs/input_grids.html#bout-topology). 

The full geometry looks something like this (VisIt plot of BOUT++ output showing cutaway view): ![plot](https://bout.llnl.gov/content/assets/images/bout_w_divert_t75_v1_large.png)

Although the MCF community is just starting to get to grips with xarray, I don't think anyone knows about this library yet.

I suppose I am asking whether there is anything about this project which restricts it's use to atmospheric models with that topology, or whether it could be used for more general problems? Also what is the scope of this project, is it a general framework with specific functionality built by those who want it or is it intended purely to support meterologists?

**Comment by rabernat** [comment]
Hi @TomNicholas. Thanks a lot for your interest in the project!

I am an oceanographer, and xgcm is currently most used in the context of ocean modeling.

You are correct--the approach is applicable in principle for any finite volume model in orthogonal curvilinear coordinates. (Unstructured meshes are probably out of scope for now.) There has been plenty of exchange between the GFD / MHD communities for decades, and I would love to collaborate with you if you think this tool could be of use to your community.

We are very actively seeking new contributors to this project (see #104). It does a few things very well, but we could do a lot more with more people involved.

The first step would be to get your model data into xarray somehow. The folks on the xarray mailing list / issue tracker will be more than happy to help with that.

**Comment by TomNicholas** [comment]
> would love to collaborate

Okay great!

> actively seeking new contributors

I don't know if I personally will need to use this library soon (simply because my simulations have a super-simplified geometry), but I just wanted to check that collaboration was possible before I suggested it to the people who develop BOUT++ and its main user tools.

> get your model data into xarray

Don't worry, I'm already a convert to xarray!

(I'll close this issue until I have more specific questions)

**Comment by rabernat** [comment]
FYI, we wrote a package to read our model's custom binary data format into xarray (lazily using dask): https://github.com/xgcm/xmitgcm/

You may find this a useful template if you also have a custom binary data format.

**Comment by TomNicholas** [comment]
I was looking into how I would use this for BOUT++ data a bit further, but I have a question:

In all the examples of complex topologies I've seen ([for example here](https://xgcm.readthedocs.io/en/latest/grid_topology.html#cubed-sphere)) then each connected face has the same shape, and is stored in the same dataset (indexed by the `face` dimension). What if I have a logically rectangular domain, which is subdivided into a set of faces, but the faces are of different shapes? The edges of these faces still have matched sizes, but I don't see how that would fit so neatly into your model?

**Comment by rabernat** [comment]
The limitation is more with xarray / numpy’s data model. What you are describing, different shapes along the face dimension, is a ragged array. This is not supported anywhere I the python ecosystem afaik. Our workaround is to break the faces into tiles of equal size.

**Comment by rabernat** [comment]
@TomNicholas - I'd like to close or resolve this issue, which has been open for a long time.

Do you have an example of using xgcm with plasma physics data? If so, would you be willing to contribute and example to the docs?

**Comment by TomNicholas** [comment]
> Do you have an example of using xgcm with plasma physics data?

No - we may do in the future, but not at the moment. 

> The limitation is more with xarray / numpy’s data model. What you are describing, different shapes along the face dimension, is a ragged array. This is not supported anywhere I the python ecosystem afaik. Our workaround is to break the faces into tiles of equal size.

BOUT++ solves on logically rectangular grid, but to simulate complex topologies that grid is broken up into regions of differing sizes. These can't be stacked along a `face` dimension, so xgcm would need to be able to describe the connections between different xarray objects of different sizes. Then we could maybe wrap all the different sub-regions up, but I'm not planning to work on this soon.

The topological breakdown looks like this

![topology_schematic](https://user-images.githubusercontent.com/35968931/74604931-cfe12780-50ba-11ea-842d-8e2a8ebca51b.png)
which corresponds in real space to a domain that (at it's most general) looks like this

![topology_cross_section](https://user-images.githubusercontent.com/35968931/74605005-92c96500-50bb-11ea-880e-d01d48231c2d.png)

 (I do have examples of using xarray, xrft and xhistogram with plasma physics data though)

**Comment by rabernat** [comment]
Just out of curiosity, how do you deal with these ragged arrays in xarray?

**Comment by TomNicholas** [comment]
> Just out of curiosity, how do you deal with these ragged arrays in xarray?

Well we don't, because the overall dataset isn't ragged - it's a single rectangular array which is then split up into differently-sized chunks (see the top of the first diagram in my last comment). So we can use xarray directly for the whole thing. The only time we should be taking into account the ragged nature is for plotting all the different regions together (which you can see we did [as a patchwork](https://github.com/boutproject/xBOUT/pull/34)), or spatial-coordinate aware analysis operations (which we simply haven't implemented yet). It's the latter which xgcm could possibly help with.

**Comment by rabernat** [comment]
Gotcha. This is actually very similar to how MITgcm LLC grids work: https://xmitgcm.readthedocs.io/en/latest/performance.html

So it would be quite cool to eventually support this sort of thing in xgcm.

**Comment by TomNicholas** [comment]
I just had a thought that the proposed `xarray.DataTree` object might enable this functionality in xgcm: you could store differently-sized tiles/faces/regions in a single DataTree object and perform your grid-aware operations on the whole thing. You would no longer be restricted to using tiles of the same size stacked along a non-physical `face` dimension. See https://github.com/pydata/xarray/issues/4118
