### ISSUE TITLE
Yee grid for electromagnetic simulations

### ISSUE THREAD

**Issue by shoyer** [xgcm/xgcm#115]
The [Yee grid](https://meep.readthedocs.io/en/latest/Yee_Lattice/) is frequently used for discretizing Maxwell's equations:
![image](https://user-images.githubusercontent.com/1217238/45791895-6ac4a080-bc40-11e8-992e-3c1128b5381a.png)

Obviously E&M simulations aren't general circulation models, but otherwise these grids look like a very good fit for xgcm. The set of desired post-processsing operations for E&M simulation output is pretty similar, i.e., including differentiation, integration and interpolation.

Would it make sense to broaden the scope for xgcm to include these types of non-GCM grids? Or perhaps create a higher level "xgridcalculus" package that xgcm relies upon? Or maybe it would just be better to fork the desired logic xgcm (e.g., xyee?).

I'm not committing to undertaking this project now, but I wanted to open this up for discussion. If I'm really lucky I'll find some entrepreneurial grad student interested in this project :).

**Comment by rabernat** [comment]
Yes! I think much of this would work today, straight out of the box. Every point on that diagram can be described as some combination of center and edge locations. The xarray dataset would need to use different dimensions to represent these different points, and their relationships would have to be specified in the xgcm.Grid constructor.

I expect the challenges are mostly related to the representation of vectors. Vectors are not really part of xgcm's data model yet; it is up to the user to compose the vector operations out of components in a way that is appropriate to the grid ([example](https://xgcm.readthedocs.io/en/latest/example_mitgcm.html#Vorticity-and-Strain)).
But, depending on the application, this might not be a dealbreaker.

We have dreams of creating a higher level interface (see #99), which would require xgcm to understand much more about the grids and how to do calculus on them. But I'm honestly not sure whether this is worth the maintenance burden. You can already do a lot of useful stuff with xgcm without the higher level interface.

**Comment by shoyer** [comment]
OK, so it looks like the Yee grid would actually be a perfect fit for xgcm right now -- if only because you haven't yet implemented the high level interface for calculus! :)

It isn't a deal breaker to not have high level operators that act on vectors. These are pretty easy to write by hand. Actually, for E&M it's a little bit easier, since the coordinate systems are usually regular (but staggered) grids -- no need to worry about coordinate transformations like projecting onto the faces of a cubed-sphere.

**Comment by jbusecke** [comment]
I am still very much interested in the higher level interface calculus (and more), and will soon have some more time to work on it.
Once the first steps are implemented, I think it would be wonderful to get feedback for non-GCM type situations.

**Comment by rabernat** [comment]
Doing some much-needed cleanup on xgcm issues.

@shoyer - do you have an example dataset that we could use to demonstrate the capability of xgcm to work with electromagnetic simulations? (see also #113)

**Comment by shoyer** [comment]
Feel free to close. I'm pretty this is possible but I don't have an actual
use case right now (I'm not currently working on E&M problems).

**Comment by ykhorrami** [comment]
Please see my lecture about Yee Grid:
https://www.youtube.com/watch?v=GS-1zYHoCTo
