### ISSUE TITLE
llc4320 face connections?

### ISSUE THREAD

**Issue by xy6g13** [xgcm/xgcm#116]
Hi all,
does anybody have llc4320 face connection to be used with xgcm?
Something like:
```
face_connections = {'face':
                    {0: ...
```

**Comment by rabernat** [comment]
Yes! We are planning to add some examples from llc grids to the docs. For now, you can look at this:

https://gist.github.com/rabernat/20dc23ac14c26880715f0ffe5fe8ff88

```python
{'face': {0: {'X': ((12, 'Y', False), (3, 'X', False)),
              'Y': (None, (1, 'Y', False))},
          1: {'X': ((11, 'Y', False), (4, 'X', False)),
              'Y': ((0, 'Y', False), (2, 'Y', False))},
          2: {'X': ((10, 'Y', False), (5, 'X', False)),
              'Y': ((1, 'Y', False), (6, 'X', False))},
          3: {'X': ((0, 'X', False), (9, 'Y', False)),
              'Y': (None, (4, 'Y', False))},
          4: {'X': ((1, 'X', False), (8, 'Y', False)),
              'Y': ((3, 'Y', False), (5, 'Y', False))},
          5: {'X': ((2, 'X', False), (7, 'Y', False)),
              'Y': ((4, 'Y', False), (6, 'Y', False))},
          6: {'X': ((2, 'Y', False), (7, 'X', False)),
              'Y': ((5, 'Y', False), (10, 'X', False))},
          7: {'X': ((6, 'X', False), (8, 'X', False)),
              'Y': ((5, 'X', False), (10, 'Y', False))},
          8: {'X': ((7, 'X', False), (9, 'X', False)),
              'Y': ((4, 'X', False), (11, 'Y', False))},
          9: {'X': ((8, 'X', False), None),
              'Y': ((3, 'X', False), (12, 'Y', False))},
          10: {'X': ((6, 'Y', False), (11, 'X', False)),
               'Y': ((7, 'Y', False), (2, 'X', False))},
          11: {'X': ((10, 'X', False), (12, 'X', False)),
               'Y': ((8, 'Y', False), (1, 'X', False))},
          12: {'X': ((11, 'X', False), None),
               'Y': ((9, 'Y', False), (0, 'X', False))}}}
```

There are a few simple examples of using xgcm with the llc90 grid here:
https://gist.github.com/rabernat/a4158e23f50470f1a55be54910a2134b

Everything is identical with llc4320, you just need LOTS more memory! ;)

**Comment by xy6g13** [comment]
Thanks very much for your quick reply. Very helpful.

It turned out I have the same issue just like your 'In[98]' in the link you shared (i.e. grid.diff/interp only works for the center points when I consider face connections). Do you have any suggestion to let it work at locations of u and v?  Thanks!

**Comment by rabernat** [comment]
Unfortunately this is not implemented yet. The corner vorticity points involve a three-way exchange  between faces, and I have not had time to figure it out.

The relevant code is here:
https://github.com/xgcm/xgcm/blob/f9daf9db67ac8ce7ed382734496bda241be5efd9/xgcm/grid.py#L314-L331

It would be amazing if someone (you?) wanted to volunteer to work on this. It would be very valuable to the MITgcm community. For example, I know that @maikejulie needs this functionality.

**Comment by rabernat** [comment]
It is also worth pointing out that, the higher the resolution, the less the exchanges actually matter. One temporary work around is simply to skip the face connections completely and operate on each tile as if it were independent. For LLC4320, this means throwing away 2 out of 4320 data points. I can't imagine that this makes any practical difference for real-world calculations.

**Comment by maikejulie** [comment]
Agreed. I think this likely matters for the lower resolutions (e.g. LLC90), but for higher resolution off-line work I think it is more a matter of principles.

**Comment by apatlpo** [comment]
I'm working with @xy6g13 and took a look at the xgcm code but I am afraid that proposing any fix for this is technically out of reach for us at the moment. Sorry about this.

We'll follow your advice and treat tiles separately, ignoring edges for now.

**Comment by apatlpo** [comment]
I still have a question though, related to the following example.

With the following data and grid (follows [xgcm cube sphere example](https://xgcm.readthedocs.io/en/latest/grid_topology.html#cubed-sphere)):
```
import numpy as np
import xarray as xr
import xgcm

N = 25
ds = xr.Dataset({'data_c': (['face', 'y', 'x'], np.ones((6, N, N)))},
                coords={'x': (('x',), np.arange(N), {'axis': 'X'}),
                        'xl': (('xl'), np.arange(N)-0.5,
                            {'axis': 'X', 'c_grid_axis_shift': -0.5}),
                        'y': (('y',), np.arange(N), {'axis': 'Y'}),
                        'yl': (('yl'), np.arange(N)-0.5,
                            {'axis': 'Y', 'c_grid_axis_shift': -0.5}),
                        'face': (('face',), np.arange(6))})

# very unrealistic flow
ds['u'] = 0.*ds.face + ds.xl + 0.*ds.y
ds['v'] = 0.*ds.face + 0.*ds.x + ds.yl

face_connections = {'face':
                        {0: {'X': ((3, 'X', False), (1, 'X', False)),
                             'Y': ((4, 'Y', False), (5, 'Y', False))},
                         1: {'X': ((0, 'X', False), (2, 'X', False)),
                             'Y': ((4, 'X', False), (5, 'X', True))},
                         2: {'X': ((1, 'X', False), (3, 'X', False)),
                             'Y': ((4, 'Y', True), (5, 'Y', True))},
                         3: {'X': ((2, 'X', False), (0, 'X', False)),
                             'Y': ((4, 'X', True), (5, 'X', False))},
                         4: {'X': ((3, 'Y', True), (1, 'Y', False)),
                             'Y': ((2, 'Y', True), (0, 'Y', False))},
                         5: {'X': ((3, 'Y', False), (1, 'Y', True)),
                             'Y': ((0, 'Y', False), (2, 'Y', True))}}}

grid = xgcm.Grid(ds, face_connections=face_connections)
```

Could you please confirm that if I want to interpolate velocity to the middle point I should do:
```
vec = grid.interp_2d_vector({'X': ds.u, 'Y': ds.v}, to='center')
```
which leads the following error:
```
...
~/code/xgcm/xgcm/grid.py in face_edge_data(fnum, face_axis, count)
    309                     data = vector_partner[vector_partner_axis_name]
    310                     if reverse:
--> 311                         raise NotImplementedError("Don't know how to handle "
    312                                                   "vectors with reversed "
    313                                                   "connections.")

NotImplementedError: Don't know how to handle vectors with reversed connections.
```

Could you also please confirm that trying to do the following does not make sense:
```
grid.interp(ds.u, 'X')
```
which leads to the following error:
```
...
~/.miniconda3/envs/xgcm/lib/python3.6/site-packages/xarray/core/common.py in _get_axis_num(self, dim)
    136         except ValueError:
    137             raise ValueError("%r not found in array dimensions %r" %
--> 138                              (dim, self.dims))
    139 
    140     @property

ValueError: 'yl' not found in array dimensions ('face', 'xl', 'y')
```

**Comment by rabernat** [comment]
This should work and does work with ecco. The problem may be that the grid specification for this contrived CS grid is somehow inconsistent.

Here is an example of using `interp_2d_vector` and `diff_2d_vector` functions on the ECCO LLC90 grid:
https://gist.github.com/rabernat/fcb944ddbc19237d1bc1292c5adf9bfe

You can run this right now from pangeo.pydata.org and verify it works.

**Comment by apatlpo** [comment]
ok, I tried on pangeo.pydata.org and it seemed to be working.
seemed because at the plotting stage I've got the following error:
```
distributed.core - ERROR - 'text'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 320, in handle_comm
    result = yield result
  File "/opt/conda/lib
...
future: <Future finished exception=KeyError('text',)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 2808, in get_data_from_worker
    max_connections=max_connections)
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1113, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.6/site-packages/distributed/core.py", line 448, in send_recv
    raise Exception(response['text'])
KeyError: 'text'
```
will try latter on again

**Comment by rabernat** [comment]
This is the same issue that #chiara7 is having in https://github.com/pangeo-data/pangeo/issues/392. I think there is a new bug in pangeo.pydata.org.

**Comment by rabernat** [comment]
Ok, I think I see what happened. The docker image for https://github.com/pangeo-data/helm-chart/pull/65 never built for some reason.

**Comment by rabernat** [comment]
Or it built, but it didn't push to dockerhub.

**Comment by rabernat** [comment]
FYI, all the problems on pangeo were fixed last week. Have you been able to proceed?

**Comment by apatlpo** [comment]
Works like a charm ! Very impressive !

Now, could you please develop your statement:
`The problem may be that the grid specification for this contrived CS grid is somehow inconsistent.`

Are you suggesting, there may be an issue with the value given to coordinates?
