### ISSUE TITLE
[DOC] Link to pycomodo is broken

### ISSUE THREAD

**Issue by willirath** [xgcm/xgcm#119]
<http://pycomodo.forge.imag.fr/> gives a 503

Also, Google does not seem to bring up any other place with the comodo specs?

**Comment by willirath** [comment]
Short term, this could be used instead:

https://web.archive.org/web/20160417032300/http://pycomodo.forge.imag.fr/norm.html

**Comment by rabernat** [comment]
Bummer! Do you know how owns that website?

**Comment by willirath** [comment]
There's a website of the building (what?!) ... https://batiment.imag.fr/en

Maybe @lesommer knows what happened to the comodo project and if there's any effort in keeping the outcomes (and the pycomodo docs in particular)?

**Comment by rabernat** [comment]
I found it!

https://prod-gitlab.inria.fr/pycomodo/pycomodo/-/blob/master/doc/source/figures/grid2d_hv.svg

**Comment by jbusecke** [comment]
Is this issue still actionable? Should we add the link somewhere in the docs?
