### ISSUE TITLE
Error using coords keyword

### ISSUE THREAD

**Issue by navidcy** [xgcm/xgcm#122]
I was having headaches with output from MOM6 which uses staggered C-grid... then I (re)discovered xgcm! Nice work you've done here! 👍 

However, I want to point out something. Following the [documentation](https://xgcm.readthedocs.io/en/latest/grids.html#manually-specifying-axes) I went on and called
```python
grid = Grid(dsx, coords={'X': {'center': 'xh', 'right': 'xq'}, 'Y': {'center': 'yh', 'right': 'yq'}})
```
but I got an error saying `coords` is an unexpected keyword argument. See here for specifics:
https://gist.github.com/navidcy/2535802336124297522d1f3fe5250cec

When I went on adding attributes to my xarray dataset coordinates then calling xgcm.grid worked. (Again, see my gist above)

Why is that? Was I doing anything wrong?
Error saying unexpected keyword `coords` seems like a bug? Or things have changed and there was no update in the docs?

**Comment by rabernat** [comment]
This is likely because this feature has not been "released" yet (it was added in 817326afd15dddce3201ed84ec8c5f2367c5068f). If you are installing from pip, you still have version 0.1. We need to actually release 0.2 (see #105). In the meantime, you can install directly from git:
```
pip install git+https://github.com/xgcm/xgcm.git
```
