### ISSUE TITLE
examples for different models

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#142]
It would be great to have an example gallery in the docs which shows xgcm usage with many different ocean / atmosphere models. A partial list would be

### Ocean 

- [x] mitgcm
- [ ] mom5
- [ ] mom6 (almost done in https://github.com/pangeo-data/pangeo-ocean-examples)
- [ ] pop (done in https://github.com/pangeo-data/pangeo-ocean-examples)
- [ ] ROMS
- [ ] NEMO
- [ ] Oceananigans (https://climate-machine.github.io/Oceananigans.jl/latest/)
- What else?

### Atmosphere

- [ ] WRF
- [ ] GFDL FML (references in https://github.com/xgcm/xgcm/issues/91)
- [ ] CAM
- What else? Not my area of expertise.

**Comment by rcaneill** [comment]
Hello,
I am now using xgcm with NEMO for 6 months, and I am planning to write some doc about it in the next montha.
What should be the format? I have never properly done this before. My idea was to follow the MITgcm example on the doc ([https://github.com/xgcm/xgcm/blob/master/doc/example_mitgcm.ipynb](https://github.com/xgcm/xgcm/blob/master/doc/example_mitgcm.ipynb)), but using a NEMO output.
Speaking concretely, how should I proceed? Fork, create a new git branch, add a jupyter notebook, pull request and this is it? Is there another step to add the notebook result to the readthedoc documentation? Is it necessary?
Thank you for your help!

**Comment by rabernat** [comment]
Hi @rcaneill - thanks for the interest. We would love to have your contribution on using xgcm with NEMO!

Yes, please prepare your example as a jupyter notebook, similar to the mitgcm example. 

Yes, fork, create new branch, commit your changes, push to your fork, and then create a pull request. You may wish to try building the docs locally as you develop your notebook. To do this, you will need to 
- Install the [doc environment](https://github.com/xgcm/xgcm/blob/master/doc/environment.yml).
- Build the docs by calling `make html` from the `doc/` subdirectory.
- Preview the output in `doc/_build/html`.

We have some development instructions here, but they are not very complete:
https://xgcm.readthedocs.io/en/latest/contributor_guide.html

Please let us know if you have any questions or need any more guidance. We are really happy to have your contribution and want to support you in every way possible.

**Comment by jbusecke** [comment]
Hi @rcaneill, thanks for using xgcm. NEMO docs would be phenomenal!

Are there NEMO datasets in the cloud? I think that would be the easiest, since we dont want to bloat the repo with large example datasets. 

Reproducing the mitgcm examples would be nice, but feel free to substitute any other example you might have in mind. Regarding the organization, I recommend taking a look at the [contributor guide](https://xgcm.readthedocs.io/en/latest/contributor_guide.html) and the one of xarray (linked in our guide). We try to follow their procedure, but if something is unclear I am happy to modify our guide (its very 'lean' at the moment).

Adding to the RTD is as easy as creating a notebook and then linking it in the index (I can help with that).
> Fork, create a new git branch, add a jupyter notebook, pull request and this is it?

Pretty much, yes! Make sure to work with the conda environment in `doc/environment.yml` and add dependencies that you need for your examples if they aren't present.

Let me know if you have any further questions.

**Comment by rcaneill** [comment]
Thank you for you rapid answers! This is very motivating!

@jbusecke I don't know yet if NEMO datasets are available on the cloud, I will ask around and search!

**Comment by rcaneill** [comment]
I work on the NEMO example slowly but surely!

> Are there NEMO datasets in the cloud? I think that would be the easiest, since we dont want to bloat the repo with large example datasets.
> 

For the moment I am writing the example in an idealized configuration. I uploaded some dataset in a draft website for the moment, and I download it from the notebook, is it a good practice? Is there another way to do? Here is the link to the notebook (in the cell In [2]:) [https://github.com/rcaneill/xgcm/blob/master/doc/example_nemo_idealized.ipynb](https://github.com/rcaneill/xgcm/blob/master/doc/example_nemo_idealized.ipynb).
If this solution is suitable, I'll find another place to store the example data online.

**Comment by rabernat** [comment]
This example looks great! It's absolutely fine to download data if the dataset is small (as yours is).

However, we should probably put the data in a permanent repository, like https://zenodo.org/, rather than your personal website (which could disappear, go down, etc.).

**Comment by rcaneill** [comment]
> This example looks great! It's absolutely fine to download data if the dataset is small (as yours is).
> 
> However, we should probably put the data in a permanent repository, like https://zenodo.org/, rather than your personal website (which could disappear, go down, etc.).

Excellent! I'll create a permanent repository when the doc will be finished, so I m sure that the data fit exactly the needs.

**Comment by navidcy** [comment]
hi, I was trying to use `xgcm` in MOM5 for computing [relative vorticity](https://github.com/COSIMA/cosima-recipes/issues/13). I'd be happy to contribute an example for the docs when I finally figure it out :)

I do have an xarray dataset with my grid and I add the properties
```python
dsx_geom.coords['xt_ocean'].attrs.update(axis='X')
dsx_geom.coords['xu_ocean'].attrs.update(axis='X', c_grid_axis_shift=0.5)
dsx_geom.coords['yt_ocean'].attrs.update(axis='Y')
dsx_geom.coords['yu_ocean'].attrs.update(axis='Y', c_grid_axis_shift=0.5)
```

For start I thought I'd do an x-y grid to be used in surface quantities.

1) First of all, will `c_grid_axis_shift` work for a B-grid?

2) How do I properly add the metrics so I can do integrations/differentiations? As #190 points out the docs are lacking a bit. I tried this:

```python
metrics = {
    ('X',): ['dxt', 'dxu'], # X distances
    ('Y',): ['dyt', 'dyu'], # Y distances
    ('X', 'Y'): ['area_t', 'area_u'] # Areas
}

grid = xgcm.Grid(dsx_geom, periodic=['X'], metrics=metrics)
grid
```

Then, it seems that `grid.interp` works. But
```python
uy = grid.derivative(u, 'Y', boundary='extend')
```
gives
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-56-b91fca001fad> in <module>
      9 print(" ")
     10 
---> 11 uy = grid.derivative(u_interpolated, 'Y', boundary='extend')
     12 
     13 print(uy)

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/lib/python3.7/site-packages/xgcm/grid.py in derivative(self, da, axis, **kwargs)
   1172         ax = self.axes[axis]
   1173         diff = ax.diff(da, **kwargs)
-> 1174         dx = self.get_metric(diff, (axis,))
   1175         return diff / dx
   1176 

/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.01/lib/python3.7/site-packages/xgcm/grid.py in get_metric(self, array, axes)
   1015             raise KeyError(
   1016                 "Unable to find any combinations of metrics for "
-> 1017                 "array dims %r and axes %r" % (array_dims, axes)
   1018             )
   1019 

KeyError: "Unable to find any combinations of metrics for array dims {'yu_ocean', 'xt_ocean'} and axes ('Y',)"
```

**Comment by dcherian** [comment]
Answer to 1. is yes. For POP see https://github.com/NCAR/pop-tools/blob/1f484deb9372f5dd51372ace167ad8af3e297577/pop_tools/xgcm_util.py#L11-L32

Hmm.. I got it to work with POP's B-grid using the same metric definition as yours in https://github.com/xgcm/xgcm/issues/187 (see also https://pop-tools.readthedocs.io/en/latest/examples/pop_div_curl_xr_xgcm_metrics_compare.html)

**Comment by jbusecke** [comment]
@navidcy you are missing metrics at the grid face (e.g. situated at ('yu_ocean', 'xt_ocean'), this would be the north face of the tracer cell. You have a few options:
1) Find the missing metrics: I have extracted the grid metrics from raw mosaic files for CM2.6 [here](https://github.com/jbusecke/mom_xtools/blob/928f780d59570d96c629e12d87d08b366ffbb024/docs/CM-O_suite_static_grid_files.ipynb), perhaps this helps (its a pretty old notebook, some things might be outdated, but the naming should be helpful?).
2) Interpolate the metrics onto the cell faces and redefine the grid object:
```
ds['dxtn'] = grid.interp(ds.dxu, 'X')
...
```
3) Interpolate the data: *This is in fact what mom does internally!*
```
ue = grid.interpolate(u, 'Y', metric_weighted='Y') 
#metric_weighted='Y' ensures that the mass flux across the east face is conserved (in the MOM5 doc they call it remapping. Basically its uflux = u*dyu -> interpolate on center of east face -> uflux/dyte

du_dx = grid.derivative(ue, 'X')
```

Id recommend using 3) no matter what, but add the missing metrics (preferrably with 1)) once you need to compute e.g. vorticity.

**Comment by navidcy** [comment]
@jbusecke, I appreciate a lot your attempt to help me, but apparently it turns out I don't understand what you mean...

first, the `ds` that I use to create my grid must have all `xt_ocean`, `xu_ocean`, `yt_ocean`, `yu_ocean`, `st_ocean` and also all metrics as variables?

(perhaps we should move the discussion elsewhere since it ends up being me asking for help rather than an issue of xgcm?)

**Comment by jbusecke** [comment]
@navidcy I think @rabernat is right in saying this should be easier to understand from the docs and thus it is very much an issue of xgcm. 

I have been thinking about how to illustrate the process better and have some ideas, but I have been quite busy with my work project and generally do not experience peak productivity in these days, hence things are moving slowly on the development side.

I really want to understand how to best explain this. I think illustrations help tremendously, but if you need a quick fix, we could have a video chat? That could be a quick solution for you and perhaps help me to understand how to convey this concept better?

**Comment by rabernat** [comment]
I would like to add the important point that the metrics are *entirely optional*.  They are a convenience layer to enable high-level operations like derivative, integral, grad, etc. They are a relatively new feature and are evidently lacking a bit in documentation and examples. 

The core of xgcm is the *low level operators* `diff` and `interp`. I believe these are explained clearly in the docs on [simple grids](https://xgcm.readthedocs.io/en/latest/grids.html). If you find the metrics confusing, I recommend you start with the low level operators. The [Pangeo POP example](https://github.com/pangeo-data/pangeo-ocean-examples/blob/master/cesm-pop-highres-ocean.ipynb) demonstrates how to calculate vorticity on a tripolar B-grid, very similar to your application. The relevant code looks like this:

```python
grid = xgcm.Grid(ds_new, periodic=['X'])

zeta = ( grid.diff(grid.interp(ds_raw.V1_1 * ds_coords.DYU, 'Y', boundary='extend'), 'X')
       - grid.diff(grid.interp(ds_raw.U1_1 * ds_coords.DXU, 'X'), 'Y', boundary='fill') ) / ds_coords.TAREA
```

**Comment by navidcy** [comment]
I put together [this](https://github.com/COSIMA/cosima-recipes/blob/3f145d1de7473730d9f5b3a51b42aa57c4616cc6/DocumentedExamples/RelativeVorticity.ipynb) for computing vorticity in MOM5. I've checked that the xgcm method,
```python
ζ_xgcm = ( grid.interp( grid.diff(ds.v, 'X') / grid.interp(ds.dxu, 'X'), 'Y', boundary='extend')
          - grid.interp( grid.diff(ds.u, 'Y', boundary='extend') / grid.interp(ds.dyt, 'X'), 'X') )
```
 reproduces the `vorticity_z` diagnostic of MOM5.

I'd be grateful if you can help me include the metrics in the xgcm grid and thus simplify the expression even more to something like
```python
ζ_xgcm = grid.derivative(ds.v, 'X') - grid.derivative(ds.u, 'Y')
```

I'd be happy to produce a self-contained MOM5 example to add it to xgcm docs.

**Comment by dcherian** [comment]
https://pop-tools.readthedocs.io/en/latest/examples/pop_div_curl_xr_xgcm_metrics_compare.html#xgcm-with-metrics

These variable names look like the POP variable names so it should be straightforward to translate this notebook. Basically you create a `metrics` dictionary and pass it to the `Grid` constructor.

**Comment by navidcy** [comment]
> https://pop-tools.readthedocs.io/en/latest/examples/pop_div_curl_xr_xgcm_metrics_compare.html#xgcm-with-metrics
> 
> These variable names look like the POP variable names so it should be straightforward to translate this notebook. Basically you create a `metrics` dictionary and pass it to the `Grid` constructor.

Yeap... but when I try to follow these steps I got an error. See my post above: https://github.com/xgcm/xgcm/issues/142#issuecomment-609603002

**Comment by navidcy** [comment]
(btw, I am still very interested in this and haven't manage to get myself around it...)

**Comment by jbusecke** [comment]
It's on my list for the next weeks!

**Comment by dcherian** [comment]
> KeyError: "Unable to find any combinations of metrics for array dims {'yu_ocean', 'xt_ocean'} and axes ('Y',)"

Can we see what your grid variables look like?

**Comment by navidcy** [comment]
here's how `ds.v` is
<img width="1091" alt="Screen Shot 2020-10-09 at 12 00 03 pm" src="https://user-images.githubusercontent.com/7112768/95529598-0d6a3a80-0a27-11eb-9203-f2c985c24195.png">

(`ds.u` is similar)

**Comment by jbusecke** [comment]
I think the problem is that you need grid metrics (here: distances) on the center/cell face points. The simplest way to achieve that is to used grid.interp on existing metrics. Check out #196 for a notebook that explains this in more detail. Once you have metrics on all 4 horizontal grid points `(xt_ocean, yt_ocean)`/`(xt_ocean, yu_ocean)`/
`(xu_ocean, yt_ocean)`/
`(xu_ocean, yu_ocean)`, this should work.

**Comment by jbusecke** [comment]
Also we are discussing refactoring some of the metric internals in #199. 
This might be helpful with situations like this in the future.

**Comment by jbusecke** [comment]
I have started migrating the different model examples over to a seperate repo [xgcm-examples](https://github.com/xgcm/xgcm-examples), which builds this neat [gallery](https://gallery.pangeo.io/repos/xgcm/xgcm-examples/). 

Any further examples should be submitted over there I think.
