### ISSUE TITLE
autogenerate notebook not rendering in docs

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#147]
I just noticed that the code cells in the [autogenerate doc page](https://xgcm.readthedocs.io/en/latest/autogenerate_examples.html) are not rendered correctly. Other pages seem to work. 

@rabernat, do you have an idea what could be causing this?

![Screen Shot 2019-09-11 at 3 12 50 PM](https://user-images.githubusercontent.com/14314623/64727426-d84b8b80-d4a6-11e9-99a5-eb1ec01dceb7.png)

**Comment by rabernat** [comment]
Weird. The notebooks should be un-executed in github and should get built during the build process.

My recommendation to debug is to build the docs locally to see what's going on.

**Comment by jbusecke** [comment]
Will do when I have a minute.

Julius J.M. Busecke, PhD (he/him)
———————————————
Postdoctoral Research Associate
Princeton University • Geosciences
408A Guyot Hall • Princeton NJ
jbusecke.github.io
