### ISSUE TITLE
wrong doc link

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#148]
The 'edit on github' link on the docs mainpage is broken. 

I am not sure where that is defined...

**Comment by rabernat** [comment]
Weird. The notebooks should be un-executed in github and should get built during the build process.

My recommendation to debug is to build the docs locally to see what's going on.

**Comment by rabernat** [comment]
Hmmm. I found some useful information about that [here](https://lmgtfy.com/?q=sphinx+edit+on+github+link).

**Comment by jbusecke** [comment]
Note to myself: Keep bugs you notice while doing 5 other things in my private to-do (where they will die a solitary death) instead of jotting them down in an issue quickly if I want to avoid @rabernat 's almighty snark 😆

**Comment by rabernat** [comment]
I only do it cause I love you 🤗

**Comment by jbusecke** [comment]
I found [this](https://github.com/readthedocs/readthedocs.org/issues/5518#issuecomment-475297781) but I think I do not have access to the rtd config page. Any chance you could give me access or try this workaround @rabernat?

**Comment by jbusecke** [comment]
Closing, since the new design doesn't have this button anymore.
