### ISSUE TITLE
Add Grid.boundary

### ISSUE THREAD

**Issue by dcherian** [xgcm/xgcm#149]
How about having `xgcm.set_options(boundary="extend")` or similar to save quite a lot of typing?

**Comment by willirath** [comment]
First thing that comes to mind: It's quite likely that people use XGCM for different grids within the same session.

**Comment by dcherian** [comment]
Right I was thinking this would be exactly like `xarray.set_options` which can be used as a context manager. So `with xgcm.set_options(boundary="extend"): ` etc. The default can stay `None` which is the current default so it won't break anything...

**Comment by rabernat** [comment]
Good idea. But one might not want to set these globally, since someone might be working with multiple different Grid objects in one session.

Instead, they could be attached to a grid. For example

```
grid = Grid(ds, coords={'X': {'center': 'x_c', 'left': 'x_g'},
                        'Y': {'center': 'y_c', 'left': 'y_g'}},
           periodic=False, boundary={'X': 'extend', 'Y: 'fill'})
```

Then every time you did `grid.diff(data, 'X')` it would apply the specified boundary condition.

**Comment by dcherian** [comment]
That's even better!

**Comment by rabernat** [comment]
PR welcome! 😉

**Comment by rabernat** [comment]
The path to implementing this would be to attach a new attribute to Axis objects

https://github.com/xgcm/xgcm/blob/cac66afeb2426546b142aef07b7752bd02ea0ebb/xgcm/grid.py#L59-L77

and then pass that through the Grid constructor.
