### ISSUE TITLE
Current build broken?

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#154]
It seems that both #153 and #130 both have the same errors that seem unrelated at first look.

> xgcm/test/test_duck_array_ops.py::test_concatenate FAILED 
> xgcm/test/test_grid.py::test_add_to_slice FAILED

The last build of the master branch was 3 months ago, did something change with the `xr.concat` function, that breaks `add_to_slice`?

I just pulled the latest master and I can confirm the same tests failing for me locally.

**Comment by dcherian** [comment]
See https://github.com/pydata/xarray/pull/3362

Thanks for finding this. I think `xgcm` should test using xarray master so that these bugs can be caught before release.

**Comment by rabernat** [comment]
Thanks for working on this guys!

**Comment by jbusecke** [comment]
Ok I am happy to implement this. @dcherian, is there another package that does this, so I can get inspiration how to implement? 
I feel it would also be needed to trigger a rebuild of the master branch on travis (our current build is 3 months old), this would have at least alerted us a bit earlier.

**Comment by dcherian** [comment]
Xarray does this with dask master. Really helps

**Comment by jbusecke** [comment]
Closed via #155
