### ISSUE TITLE
Beta application of continuous documentation via ReadTheDocs.

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#161]
As @timothyas pointed out in # 160, rtd seems to have a beta version of building docs as part of a PR (and checking the status before a merge). 

I just sent them an email and asked to be considered for the beta.

**Comment by jbusecke** [comment]
Just got a reply

![image](https://user-images.githubusercontent.com/14314623/66587337-388e2580-eb58-11e9-8e31-2dd0ea062c87.png)

Let me try to enable that and we can try it with the `grid.differentiate()` doc? @timothyas

**Comment by jbusecke** [comment]
Hmmm It seems like I cannot access the repo settings. @rabernat, could you look into this if you have a minute? Thx

**Comment by rabernat** [comment]
I have updated the webhook for RTD to include the PR event. Once we verify it's working, we can close this issue.

**Comment by jbusecke** [comment]
I think this is working pretty well. Will write a nice email to the RTD team and close this
