### ISSUE TITLE
LLCMapper: overwrites passed axes

### ISSUE THREAD

**Issue by jk3652** [xgcm/xgcm#167]
if ax is None:
            fig, ax = plt.subplots(figsize=(12, 6))

field = pyresample.kd_tree.resample_nearest(self.orig_grid, da.values,
                                                    self.new_grid,
                                                    radius_of_influence=100000,
                                                    fill_value=None)

vmax = plt_kwargs.pop('vmax', field.max())
vmin = plt_kwargs.pop('vmin', field.min())

m = plt.axes(projection=projection)

The line that returns "m" overwrites the passed axis "ax" in the previously given line. This prevents plotting in multiple subplots. You can fix this by moving m inside the if statement. With this fix, the user must specify the geoaxes object m.

**Comment by jbusecke** [comment]
Hi @jk3652, thanks for using xgcm. Could you describe a bit more what you are trying to achieve with this code? It seems that your code is related to plotting issues, which might not be directly related to xgcm. 

Cheers

**Comment by rabernat** [comment]
I believe this comment refers to the ECCOv4 example from the documentation:
https://xgcm.readthedocs.io/en/latest/example_eccov4.html

It's a bug in the plotting code. Not part of xgcm, but still our problem, since it's in our docs.
