### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by andersy005** [xgcm/xgcm#168]
Is there a timeline on when the next "stable" version of xgcm will be available? it's been a while since the last release.

**Comment by rabernat** [comment]
It would be great to have a release soon. I've been swamped this semester so have not taken it on myself. If one of the other contributors wanted to organize a release, I would be 100% 👍 .

**Comment by jbusecke** [comment]
I was super swamped until now, but would be happy to drive this forward. Is there a tutorial on which steps are involved? Still very unfamiliar with the whole process but eager to learn.

**Comment by andersy005** [comment]
>  Is there a tutorial on which steps are involved?


@jbusecke, here are the steps that I would do for PyPI.

0. Update `~/.pypirc` with your PyPI credentials

```
[distutils]
index-servers=
    pypi

[pypi]
username: xxxxxxxxxx
password: xxxxxxxxxxxxxxxxxx
```

1.  Tag a release and push to github

        git tag -a 1.0.0 -m "Version 1.0.0"
        git push origin master --tags

2.  Build and publish release on PyPI

    ```
    git clean -xfd  # remove any files not checked into git
    python setup.py sdist bdist_wheel   # build package
    twine upload dist/*  # register and push to pypi. This requires having `twine` installed (It's available on PyPI and conda-forge)
    ```

**Comment by jbusecke** [comment]
Thank you very much @andersy005, Ill try to get to it tomorrow. Is is kosher to save username and password unencrypted like that?

**Comment by andersy005** [comment]
You are welcome! 

> Is is ok to save username and password unencrypted like that?

There's a much safer way, **using an API token**:

- Head over to https://pypi.org/manage/account/ to create an API token
- Here's the documentation on how to update the `~/.pypirc` file to use the API token: https://pypi.org/help/#apitoken
- Remember to set the permission of `~/.pypirc` with  `chmod 600 ~/.pypirc`

**Comment by jbusecke** [comment]
Awesome, thanks. Will hopefully get to it tomorrow.

**Comment by rabernat** [comment]
What is up with this? Are we going to do a release or not? Anything needed from me?

**Comment by jbusecke** [comment]
Hey @rabernat and @andersy005, sorry for dropping the ball on this. I was pretty swamped over here.

@andersy005, if I understand your changes correctly (and I might very well miss something here), we only need to trigger a release on github (v.0.3.0, I assume) and then the release on pypi will be triggered? Do we need to do anything after that for conda? Or is this based on the pypi release?

I am not able to set those secrets in the settings, so I think that would have to be done by @rabernat.

**Comment by rabernat** [comment]
I have added the pypi secrets, so I think it should work.

One question I have is whether it's worth trying to resolve the open PRs before a 0.3.0 release.

**Comment by jbusecke** [comment]
I thought the same thing, but I have to admit that I probably will need some time for the ones I am involved in (e.g. #159). I am also very unsure about *when* it is appropriate to release, and which version to bump for certain features. 
I think the major upgrade so far was the handling of grid metrics, warranting the 0.3.x. Perhaps we should release 0.3.0 and then have a todo list for the next release, where we include the open PRs?

**Comment by jbusecke** [comment]
Depending on reviews on #159, we might be able to turn that around quickly, and we could include it in 0.3.0, which would be nice. Also we should probably start a `whats-new` in the docs at some point?

**Comment by rabernat** [comment]
Let's move ahead with the release without #159. There are still some issues there.

**Comment by jbusecke** [comment]
Should we add a `whats-new.rst`? That would be a quick PR (I can do that right now), and then we can keep track of changes?

**Comment by jbusecke** [comment]
Just added a PR with those changes in #172. Ill go ahead and start a release draft.

**Comment by jbusecke** [comment]
I already drafted a release. Should I pull the trigger? Or do we have anything still pending?

**Comment by rabernat** [comment]
Go for it Julius!
