### ISSUE TITLE
grid.average with MOM6

### ISSUE THREAD

**Issue by raphaeldussin** [xgcm/xgcm#182]
it works but there is a pitfall, see https://mom6-analysiscookbook.readthedocs.io/en/latest/03_spatial_operations.html#Using-xgcm

I wonder if raising a warning if the number of points summed in the numerator and denominator differ would be a good idea. Or add the option for an optional land/sea mask.

@rabernat  @jbusecke what do you think?

also I have some very basic examples of using xgcm with MOM6. I'd be happy to contribute an example notebook if @jbusecke  don't have one in prep already.

**Comment by rabernat** [comment]
I think the points you raise are very useful and also quite general. Many models (like POP) have similar issues with inconsistent masking of grid variables. This might also be an issue in MIT: the data variables (e.g. `THETA`) are just 0 in the land, and the weights (e.g. `rA`) are defined everywhere. So a naive weighted mean could also give the wrong answer.

There are a couple of paths forward I can think of:
- We could have users define the metrics with the appropriate masks outside of xgcm, i.e. `area = metrics['areacello'] * metrics['wet']` and then pass these the xgcm's metrics. (Perhaps some preprocessing routines for common models could automate this.)
- We could add the notion of masks to xgcm's data model and automatically mask data where necessary. This could also come in handy for other things, like enforcing boundary conditions.

Thoughts?

**Comment by jbusecke** [comment]
I noticed this too in some of my work. I hoped that we could take care of this upstream in [xarray](https://github.com/pydata/xarray/pull/2922), but it seems that might have stalled...

> We could have users define the metrics with the appropriate masks outside of xgcm, i.e. area = metrics['areacello'] * metrics['wet'] and then pass these the xgcm's metrics. (Perhaps some preprocessing routines for common models could automate this.)

I did wright some logic to do weighted averages [here](https://github.com/jbusecke/xarrayutils/blob/003e4f8a12aefc09714f7ecc184ac3c70956dc3c/xarrayutils/weighted_operations.py#L108), which we could modify. This will however make these operations slower. Perhaps it would be good to have it on by default (so a weighted mean over ocean masked properties with a global area is not biased for example), but for the user to be able to turn it off if they have properly preprocessed metrics?

>also I have some very basic examples of using xgcm with MOM6. I'd be happy to contribute an example notebook if @jbusecke don't have one in prep already.

Nothing specific in the pipeline yet (mostly worked with MOM5!), so I would be super happy if you could add some MOM6 examples.

**Comment by rabernat** [comment]
What we need is a clear template and structure within the docs to accept these examples.

What do we think about my idea of adding masks to xgcm's data model.

**Comment by jbusecke** [comment]
+1 on the templates! Should we have a gallery of various models all doing the same thing? I think that would be very helpful to get ppl started. We can add other, more advanced examples based on any of the models.

I think the masks are a great idea, but I am worried it adds a lot of complications to the use cases, but it seems like a very general implementation, so lets do it. 

How about this: We implement the masks, but then eventually work on a better ‘autogenerate’ machinery that would approximate all of these fields from a simple input like `grid=Grid(ds)`

E.g. if no mask is provided, the internal machinery could automatically build a mask from the data and apply it to the metric. This would be slower but we could add a keyword to switch it off. With appropriate warnings this would be nice for “quick and dirty” workflows (these are always nice to get people started with a software)



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rabernat** [comment]
> +1 on the templates! Should we have a gallery of various models all doing the same thing?

Exactly. We should define the same basic N tasks, and then show how to do each of them in different models. We could store this in a subdirectory, i.e. `docs/examples`, along with a template for new examples.

@jbusecke - do you have bandwidth to take this on?

**Comment by jbusecke** [comment]
Not at the moment I am afraid (Big seminar coming up on Mon). Could you ping me next week by any chance? I might be able to do it then.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment]
Any chance you could test #204 and see if that does solve the issue @raphaeldussin?

**Comment by raphaeldussin** [comment]
I create my grid+weights with:

```python

metrics = {
    ('X',): ['dxt'], # X distances
    ('Y',): ['dyt'], # Y distances
    ('X', 'Y'): ['areacello'], # Areas
}

coords={'X': {'center': 'xh', 'right': 'xq'},
        'Y': {'center': 'yh', 'right': 'yq'} }

grid = Grid(ds, coords=coords, metrics=metrics, periodic=['X'])

```


Running this cell:

```python
mean_sst_xgcm = grid.average(sst, ['X', 'Y'])

```


gives a runtime error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-84e9927f5781> in <module>
----> 1 mean_sst_xgcm = grid.average(sst, ['X', 'Y'])
      2 mean_sst_xgcm.isel(time=0).values

/net2/rnd/anaconda3/envs/analysis/lib/python3.6/site-packages/xgcm-0.3.0+16.g6cfa86a-py3.6.egg/xgcm/grid.py in average(self, da, axis, **kwargs)
   1442         da = da.copy()
   1443         weight = self.get_metric(da, axis)
-> 1444         weighted = da.weighted(weight)
   1445         # get dimension(s) corresponding
   1446         # to `da` and `axis` input

/net2/rnd/anaconda3/envs/analysis/lib/python3.6/site-packages/xarray/core/common.py in __getattr__(self, name)
    231                     return source[name]
    232         raise AttributeError(
--> 233             "{!r} object has no attribute {!r}".format(type(self).__name__, name)
    234         )
    235 

AttributeError: 'DataArray' object has no attribute 'weighted'
```

**Comment by jbusecke** [comment]
Whats your xarray version? The weighted method was only recently introduced. 

Thanks for testing

**Comment by jbusecke** [comment]
Whats your xarray version? The weighted method was only recently introduced. 

Thanks for testing

**Comment by raphaeldussin** [comment]
I upgraded from 0.15.0 to 0.15.1 and it works. 2 comments however:

* xarray returns an error if metrics have missing values, easily fixable with fillna(0.) Would it make sense to include this step when creating weights in xgcm?
* I don't recover the exact same answers between my homemade average function:

```python
def horizontal_mean(da, metrics):
    num = (da * metrics['areacello'] * metrics['wet']).sum(dim=['xh', 'yh'])
    denom = (metrics['areacello'] * metrics['wet']).sum(dim=['xh', 'yh'])
    return num / denom
```
and xgcm averaging with weights = [dxt, dyt], or weights = ['areacello']. Errors are smaller than the third decimal point though, probably some truncation error arising from summing all these large numbers?

**Comment by jbusecke** [comment]
Thanks a lot for the detailed reply.

> xarray returns an error if metrics have missing values, easily fixable with fillna(0.) Would it make sense to include this step when creating weights in xgcm?

Yes, I noticed that too. Ill see if I can fix that elegantly.

> I don't recover the exact same answers between my homemade average function:

That is a bit weird. Could it be that the `wet` mask is the culprit? I had this in older MOM versions, that there are a few points on land (in rivermouths) that would be cut out by the wet mask, but would be counted if the raw data array was used. 

Is `np.logical_xor(metrics['wet'] * ~np.isnan(da)).sum()` equal 0?

**Comment by raphaeldussin** [comment]
I have the same number of land points in wet and in the dataarray but that was a good sanity check.

**Comment by jbusecke** [comment]
Weird. Then maybe it is some truncation artifact due to the multiplication with the mask...I wont worry about it too much for now. Really appreciate you checking this.

**Comment by raphaeldussin** [comment]
@jbusecke I'm able to get (close to) the same answers using the xgcm averages from your PR, see:

https://mom6-analysiscookbook.readthedocs.io/en/latest/03_spatial_operations.html 

an elegant fix for the fillna would be great!
