### ISSUE TITLE
higher-order derivatives

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#185]
I was wondering is it possible to calculate higher-order derivatives using the current functionality of xgcm?  I guess the calculation of the harmonic diffusion of a tracer q ($\nabla^2 q$) would be:

```python
q_harm = Grid.derivative(Grid.derivative(q, 'X'), 'X') +\
         Grid.derivative(Grid.derivative(q, 'Y'), 'Y')
```
Since calling derivative once will shift the result to the left of the tracer cell, I'm not so sure the result by calling twice is properly aligned back to the tracer point.

I'm also curious if this way can be generalized to higher-order derivatives, such as in the bi-harmonic diffusion as $\nabla^4 q$.

**Comment by jbusecke** [comment]
Hi @miniufo miniufo, thanks for using xgcm. 

I think this should work, and as you have written it here, the second derivative should again end up on the tracer point. Do you have some data to compare the results to? That would be a great way to verify the results.

> I'm also curious if this way can be generalized to higher-order derivatives, such as in the bi-harmonic diffusion as $\nabla^4 q$.

We do have the functionality to pass multiple axes. I am wondering if your use case would be satisfied by `grid.derivative(q, ['X','X'])`. 

Could you check if that results in the same output as  Grid.derivative(Grid.derivative(q, 'X'), 'X'). 
I think we are not currently testing this with multiple instances of the same axis, but I think it still works.

If this works, than for the 4th derivative you could do `grid.derivative(q, ['X','X', 'X', 'X'])`.

Note that depending on your data, the results might get very noisy, since we only work with first-order differences internally.  [Higher-order finite differences](https://en.wikipedia.org/wiki/Finite_difference) are currently not supported

**Comment by miniufo** [comment]
Hi @jbusecke , I've updated xgcm to 0.3 and then tried your ways.  However, errors are raised.

For nested call of derivative as:
```python
derivX2_nes = grid.derivative(grid.derivative(T, 'X'),'X')
```
it reports:
>  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 988, in get_metric
>  "array dims %r and axes %r" % (array_dims, axes)
>  KeyError: "Unable to find any combinations of metrics for array dims {'YC', 'XC'} and axes ('X',)"

I guess this is related to the metrics keyword arg.  I use standard MITgcm outputs and I've already pass in the metrics as:
```python
import xmitgcm
import xgcm

dset = xmitgcm.open_mdsdataset('F:/output_budget/',
                    delta_t=300, read_grid=True, prefix=['Stat3D'])
metrics = {
    ('X',): ['dxC', 'dxG'],  # X distances
    ('Y',): ['dyC', 'dyG'],  # Y distances
    ('Z',): ['drF', 'drC'],  # Z distances
    ('X', 'Y'): ['rA', 'rAz', 'rAs', 'rAw']  # Areas
}

grid = xgcm.Grid(dset, periodic=['X'], metrics=metrics)
```

For the multiple axes you suggested `grid.derivative(T, ['X', 'X'])`, it reports:
>  File "C:\ProgramData\Anaconda3\lib\site-packages\xgcm\grid.py", line 1134, in derivative
>  ax = self.axes[axis]
>  TypeError: unhashable type: 'list'

I guess the multiple axes passed in should be in a set, not list, so duplicated axes are not allowed.

Any suggestion?

**Comment by jbusecke** [comment]
Thanks for these clarifications. 

To further dig into what is going on here:
```
derivX2_nes = grid.derivative(grid.derivative(T, 'X'),'X')
```
could you paste the output of the full dataset and try to split the two operations into seperate call, with printing the intermediate output? It seems that you dont have the grid metrics available at the right location.

> For the multiple axes you suggested grid.derivative(T, ['X', 'X']), it reports:

Hmm this is a deeper issue to think about. This syntax works for (diff, interp, etc..), because they are strictly executed in serial. Once you involve the metrics, it becomes a bit tricky. I remember talking to @rabernat about this when we implemented it. Do we want a derivative in two axes, to basically 
1) repeat the `derivative` step twice, invoking distance metrics each time (as would be required here). 

2) Or do we want it to do  `diff` twice and then divide by the 2 dimensional metric (e.g. area). 

2)  is what you want for integrals, because the product of the two distance metrics might not exactly equal the area in a finite volume model.

The more I think about this, I think I tend to the former. But perhaps some other folks can chime in. Are there model differences in the way multiple finite derivatives are implemented?

Do we need to distinguish between multiple axes in the same direction, in which case only 1) makes sense to me. Also is this an exclusive problem to `derivative`? Or are other functions affected?

cc @rabernat

**Comment by miniufo** [comment]
Hi @jbusecke  Thanks for your quick reply.

1. For multiple axes way, I would suggest an intuitive API by adding a kwarg `order` like:
```python
derivative_n = Grid.derivative(T, ['X', 'Y'], order=n)
```
rather than
```python
derivative_n = Grid.derivative(T, ['X', 'Y']*n)
```

2. For the error raised in nested call, my code is simple:
```python
import xmitgcm
import xgcm

indir = 'I:/channel/'
dset = xmitgcm.open_mdsdataset(indir+'output_budget/',
                    delta_t=300, grid_dir=indir, read_grid=True,
                    prefix=['Stat3D'])
metrics = {
    ('X',): ['dxC', 'dxG'],  # X distances
    ('Y',): ['dyC', 'dyG'],  # Y distances
    ('Z',): ['drF', 'drC'],  # Z distances
    ('X', 'Y'): ['rA', 'rAz', 'rAs', 'rAw']  # Areas
}

grid = xgcm.Grid(dset, periodic=['X'], metrics=metrics)

T = dset['THETA'][0,0].load()

# nested solution with Grid.derivative
derivY1_nes = grid.derivative(T, 'Y', boundary='fill')
derivY2_nes = grid.derivative(derivY1_nes, 'Y', boundary='fill')
```
The error is raised at the last line as:
> Traceback (most recent call last):
>  File "E:\OneDrive\Python\MyPack\TestXGCMDerivative.py", line 116, in <module>
>    derivY2_nes = grid.derivative(derivY1_nes, 'Y', boundary='fill')
>  File "C:\Users\Administrator\Anaconda3\lib\site-packages\xgcm\grid.py", line 1174, in derivative
>    dx = self.get_metric(diff, (axis,))
>  File "C:\Users\Administrator\Anaconda3\lib\site-packages\xgcm\grid.py", line 1017, in get_metric
>    "array dims %r and axes %r" % (array_dims, axes)
> KeyError: "Unable to find any combinations of metrics for array dims {'YC', 'XC'} and axes ('Y',)"

So these things are printed for debugging:
```python
In [8]: print(xgcm.__version__)
0.3.0

In [9]: print(xmitgcm.__version__)
0.4.1

In [10]: print(dset)
<xarray.Dataset>
Dimensions:   (XC: 200, XG: 200, YC: 400, YG: 400, Z: 30, Zl: 30, Zp1: 31, Zu: 30, time: 3)
Coordinates:
  * XC        (XC) >f4 2500.0 7500.0 12500.0 ... 987500.0 992500.0 997500.0
  * YC        (YC) >f4 2500.0 7500.0 12500.0 ... 1987500.0 1992500.0 1997500.0
  * XG        (XG) >f4 0.0 5000.0 10000.0 15000.0 ... 985000.0 990000.0 995000.0
  * YG        (YG) >f4 0.0 5000.0 10000.0 ... 1985000.0 1990000.0 1995000.0
  * Z         (Z) >f4 -5.0 -15.0 -27.5 -45.0 ... -2330.0 -2580.0 -2830.0 -3080.0
  * Zp1       (Zp1) >f4 0.0 -10.0 -20.0 -35.0 ... -2705.0 -2955.0 -3205.0
  * Zu        (Zu) >f4 -10.0 -20.0 -35.0 -55.0 ... -2705.0 -2955.0 -3205.0
  * Zl        (Zl) >f4 0.0 -10.0 -20.0 -35.0 ... -2205.0 -2455.0 -2705.0 -2955.0
    rA        (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dxG       (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyG       (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    Depth     (YC, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAz       (YG, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dxC       (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    dyC       (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAw       (YC, XG) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    rAs       (YG, XC) >f4 dask.array<chunksize=(400, 200), meta=np.ndarray>
    drC       (Zp1) >f4 dask.array<chunksize=(31,), meta=np.ndarray>
    drF       (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    PHrefC    (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    PHrefF    (Zp1) >f4 dask.array<chunksize=(31,), meta=np.ndarray>
    RhoRef    (Z) >f4 dask.array<chunksize=(30,), meta=np.ndarray>
    hFacC     (Z, YC, XC) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    hFacW     (Z, YC, XG) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    hFacS     (Z, YG, XC) >f4 dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskC     (Z, YC, XC) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskW     (Z, YC, XG) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskS     (Z, YG, XC) bool dask.array<chunksize=(30, 400, 200), meta=np.ndarray>
    maskInC   (YC, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInS   (YG, XC) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    maskInW   (YC, XG) bool dask.array<chunksize=(400, 200), meta=np.ndarray>
    iter      (time) int32 dask.array<chunksize=(1,), meta=np.ndarray>
  * time      (time) int64 1866250800 1866261600 1866272400
Data variables:
    UVEL      (time, Z, YC, XG) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    VVEL      (time, Z, YG, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    WVEL      (time, Zl, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    THETA     (time, Z, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    RHOAnoma  (time, Z, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    PHIHYD    (time, Z, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>
    momKE     (time, Z, YC, XC) float32 dask.array<chunksize=(1, 30, 400, 200), meta=np.ndarray>

In [11]: print(T)
<xarray.DataArray 'THETA' (YC: 400, XC: 200)>
array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [2.8994339, 2.8941731, 2.9212184, ..., 3.1726084, 3.0835252,
        2.9713194],
       [3.061857 , 2.9578333, 2.9494348, ..., 3.316772 , 3.2797012,
        3.1743088],
       ...,
       [5.4207854, 5.4086466, 5.4055886, ..., 5.480547 , 5.4608674,
        5.43989  ],
       [5.685765 , 5.6744523, 5.664376 , ..., 5.7212887, 5.709993 ,
        5.6980166],
       [7.9161615, 7.9161615, 7.9161615, ..., 7.9161615, 7.9161615,
        7.9161615]], dtype=float32)
Coordinates:
  * XC       (XC) >f4 2500.0 7500.0 12500.0 ... 987500.0 992500.0 997500.0
  * YC       (YC) >f4 2500.0 7500.0 12500.0 ... 1987500.0 1992500.0 1997500.0
    Z        >f4 -5.0
    rA       (YC, XC) >f4 25000000.0 25000000.0 ... 25000000.0 25000000.0
    Depth    (YC, XC) >f4 0.0 0.0 0.0 0.0 0.0 ... 2955.0 2955.0 2955.0 2955.0
    drF      float32 10.0
    PHrefC   float32 49.05
    RhoRef   float32 999.8
    hFacC    (YC, XC) >f4 0.0 0.0 0.0 0.0 0.0 0.0 ... 1.0 1.0 1.0 1.0 1.0 1.0
    maskC    (YC, XC) bool False False False False False ... True True True True
    maskInC  (YC, XC) bool False False False False ... False False False False
    iter     int32 6220836
    time     int64 1866250800
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC

In [12]: print(derivY1_nes)
<xarray.DataArray (YG: 400, XC: 200)>
dask.array<true_divide, shape=(400, 200), dtype=float32, chunksize=(400, 200), chunktype=numpy.ndarray>
Coordinates:
  * YG       (YG) >f4 0.0 5000.0 10000.0 ... 1985000.0 1990000.0 1995000.0
  * XC       (XC) >f4 2500.0 7500.0 12500.0 ... 987500.0 992500.0 997500.0
```

Hope these are enough.

**Comment by jbusecke** [comment]
Great. Thanks for providing those. So If I am seeing this right, you have two dy (y-distance) metrics [`dyC` and `dyG`], both located at the u and v points of the grid (north and east face).

Your first operation will internally 'diff' the variable `T`, taking the difference between two tracer points. The metric associated with that operation is located on the cell face, here on the `v` point `('XC', 'YG')`. That metric is indeed available (its `dyC`). The resulting array is now located at the same position on the north face. 
When you attempt to apply `derivative` again, the internal logic 'diffs' two cell boundary points back to the tracer location `('XC', 'YC')` and needs to have a dy associated with it. But that metric is missing!  
As far as I can see, you have an incomplete set of metrics (there should be a max of 4 for tracer, u,v and vorticity point). The [mitgcm manual](http://mitgcm.org/public/r2_manual/latest/online_documents/node47.html) calls the needed metric `dyF`.

An approximate workaround could look like this: 
```python
# initiate grid without metrics
grid = xgcm.Grid(dset, periodic=['X'])
dset.coords['dxF'] = grid.interp(dset['dxC'], 'X')
dset.coords['dyF'] = grid.interp(dset['dyC'], 'Y')
# optionally reconstruct `dxV` and `dyU` in a similar way

# add additional metrics
metrics = {
    ('X',): ['dxC', 'dxG', 'dxF'],  # X distances
    ('Y',): ['dyC', 'dyG', 'dyF'],  # Y distances
    ('Z',): ['drF', 'drC'],  # Z distances
    ('X', 'Y'): ['rA', 'rAz', 'rAs', 'rAw']  # Areas
}

grid = xgcm.Grid(dset, periodic=['X'], metrics=metrics)

T = dset['THETA'][0,0].load()

# nested solution with Grid.derivative
derivY1_nes = grid.derivative(T, 'Y', boundary='fill')
derivY2_nes = grid.derivative(derivY1_nes, 'Y', boundary='fill')
```

This should now work. 

NOTE: Interpolation of the metrics could lead to errors if the grid is very non-regular (e.g. near the poles) and it is always preferred to recover the metric from the model output if available.

Let me know if there are more problems with this.

Regarding your suggestion:

> derivative_n = Grid.derivative(T, ['X', 'Y'], order=n)

I think this could be misleadingly imply that we are using an n-th order differencing scheme. 

Even on a more basic level I am still struggling to come up with a good example where we would need a derivative in two directions (in the case of a tracer this would end up on a corner/vorticity cell) the way it is implemented right now. Let alone doing this n amount of times... do you have a simple example to clarify this?

**Comment by miniufo** [comment]
@jbusecke Thanks for your detailed explanation.

> there should be a max of 4 for tracer, u,v and vorticity point

This is an important note for me.

-----
Now I get the results for these codes:
```python
# reference solution for 2nd-order derivative
for j in range(1, len(T.YC)-1):
    # loop over interior grid points
    derivY2_ref[j, :] = ((T[j+1, :] - T[j  , :])/(Y[j+1] - Y[j  ]) -
                         (T[j  , :] - T[j-1, :])/(Y[j  ] - Y[j-1])
                         ) / ((Y[j+1] - Y[j-1])/2)

# nested solution with Grid.derivative
derivY2_nes = grid.derivative(grid.derivative(T, 'Y', boundary='fill'),
                              'Y', boundary='fill')
```
The reference 2nd-order derivative `derivY2_ref` is identical to the nested/recursive solution `derivY2_nes`, except at the boundaries.  I am happy with this result and the Laplacian diffusion term could be calculated using nested/recursive call.

---
I've been dealing with diagnostic equations in geofluid.  I used to central differencing on A-grid dataset until I start to use the C-grid MITgcm.  I'm not happy with the matlab `diff` or numpy `diff` mostly because they returned `n-1` values.  The xgcm has internally padded the one missing data with a `fill_value` (although it is easy).  More importantly, xgcm defines the results by a shift (C-grid style definition) so that the `Grid.diff` is effectively a **central** differencing.  Now I am re-thinking everything I previously encountered on A-grid, using the concepts of xgcm.  **I just wonder if `Grid.derivative` could be used as a building block for more complicated situation**.  For example, I want to calculate some diagnostics in MITgcm in an offline fashion so I won't need to rerun the model.  So far I come to the Laplacian diffusion operator, and I confirm that this:
```python
q_harm = Grid.derivative(Grid.derivative(q, 'X'), 'X') +\
         Grid.derivative(Grid.derivative(q, 'Y'), 'Y')
```
should be the right way.

---
> Regarding your suggestion:
> derivative_n = Grid.derivative(T, ['X', 'Y'], order=n)
> I think this could be misleadingly imply that we are using an n-th order differencing scheme.

Isn't recursive calls of `Grid.derivative` or `Grid.diff` exactly the n-th order differencing?  Or there are many choices of schemes and recursive call is only one of them?  I found the [webpage for matlab diff](https://ww2.mathworks.cn/help/matlab/ref/diff.html?lang=en) and it says that:
*Y = diff(X,n) calculates the nth difference by applying the diff(X) operator recursively n times. In practice, this means diff(X,2) is the same as diff(diff(X)).*

That's why I would suggest an api in this way.

---
>do you have a simple example to clarify this?

I've also need to calculate some cross partial-derivatives, like in the advection of vorticity, in which this
```python
d2udydx = Grid.derivative(u, ['Y', 'X'])
```
would be handy for $\frac{\partial^2 u}{\partial y\partial x}$.  Although there may be many excellent schemes, I hope I can do the simplest one with xgcm.  Right now I wouldn't go that far.

**Comment by jbusecke** [comment]
Glad it is working now. And happy that you seem motivated to continue using xgcm 🎉 

> I just wonder if Grid.derivative could be used as a building block for more complicated situation.

This is **precisely** the idea behind xgcm. Simplify very general finite distance/volume operators and let users build on top of that!

> Isn't recursive calls of Grid.derivative or Grid.diff exactly the n-th order differencing?

So first I have to apologize I somehow thought of a 'central' vs 'forward/backward' finite differencing scheme as 'order'. That is false. 

You are right that roughly speaking the nth repetition of a derivative call approximates the nth order derivative.

**BUT** you have to be really careful with saying that xgcm does a `central difference`. It does not do that for the first order! For it to be a proper central difference we would need the metrics between adjacent tracer and grid face values. This is currently not supported! The supported metrics describe neighboring points of the same kind e.g. the distance between two tracer points.

Consider this formulation from [Wikipedia](https://en.wikipedia.org/wiki/Finite_difference)
<img width="877" alt="image" src="https://user-images.githubusercontent.com/14314623/76637588-6c171680-6521-11ea-9df9-82399f5fb5d1.png">


 We do not have h/2 in this example. We are technically doing a forward/backward difference and relocate the data point (which is what a lot of gcms actually do!). 

I think your comment is correct when the distances are uniform. In that case,  I believe this also works out to reproduce the 'Second-order central' scheme (from the same wiki page) when applied twice,
<img width="624" alt="image" src="https://user-images.githubusercontent.com/14314623/76638037-27d84600-6522-11ea-8451-f89f4307b879.png">
 but not when applied 3 times! I am not sure if this can be generalized to odd and even orders.

But it is important to keep in mind that this might not be accurate when grid distances are not uniform.

We have been discussing extending the data model of xgcm to include these 'sub-metrics', to reproduce even better what certain model (like GFDLs MOM) do internally, but that would require a substantial refactoring of the internal machinery.

**Comment by miniufo** [comment]
I think I have learned something.  My experiences are limited, so I did not take into account the case of non-uniform grids.  Actucally, I always regrid non-uniform data onto uniform grids before any further diagnosing.

I like the idea of including 'sub-metrics'.  Maybe we need more expert modellers to get involved and make xgcm more general.  Hope that I become more familiar with MOM sometimes later, but now I'm a huge fan of MITgcm.

PS: I've recently noticed that you are an expert on mixing.  I just finished transplanting my Java code to python on calculating the effective diffusivity by [Nakamura (1996, JAS)](https://journals.ametsoc.org/doi/abs/10.1175/1520-0469%281996%29053%3C1524%3ATDMEFA%3E2.0.CO%3B2).  This is easy and straightforward with the great help of `xarray` and `xgcm`.  I can focus on designing the top APIs without much attention on the specific details (I need to write every details when using Java).  I'll write a jupyter notebook later.  I guess you may be interested in this.

Very glad to discuss with you.  I'll come back here if I come up with some ideas.

**Comment by jbusecke** [comment]
> I think I have learned something. My experiences are limited, so I did not take into account the case of non-uniform grids. Actucally, I always regrid non-uniform data onto uniform grids before any further diagnosing.

If you have the raw metric output, you dont have to do that anymore. xgcm will enable you to work with complex grids just like with a uniform grid.

> I like the idea of including 'sub-metrics'. Maybe we need more expert modellers to get involved and make xgcm more general. Hope that I become more familiar with MOM sometimes later, but now I'm a huge fan of MITgcm.

This will be a substantial amount of work, so it might not happen soon, but I think it would be a cool addition.

> PS: I've recently noticed that you are an expert on mixing. I just finished transplanting my Java code to python on calculating the effective diffusivity by Nakamura (1996, JAS). This is easy and straightforward with the great help of xarray and xgcm. I can focus on designing the top APIs without much attention on the specific details (I need to write every details when using Java). I'll write a jupyter notebook later. I guess you may be interested in this.

Oh yes I would be very curious. 

> Very glad to discuss with you. I'll come back here if I come up with some ideas.

This was also great for me. Yes please keep raising issues if something is unclear or you wish to have other functionality!

Do you think we can close this issue for now?

**Comment by miniufo** [comment]
Yes we can close this now.  Thanks again @jbusecke .

FYI: [calculating effective diffusivity using xgcm](https://github.com/miniufo/GeoApps/blob/master/notebooks/Contour%20analysis%20and%20effective%20diffusivity.ipynb)
