### ISSUE TITLE
vertical integration to the free surface

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#191]
Recently I want to perform an integration of velocity from the bottom to the free surface to get the barotropic velocity.  I've read [the document here](https://xgcm.readthedocs.io/en/latest/grid_metrics.html#Grid-aware-integration) that gives an example on how to use `xgcm.integrate` to do this.  Notice that the example integrates to `z=0` (the top level), not to free surface.

I think the water volume could be exactly conserved only if the integration is performed to the free surface.  Although this may not be a big deal if long-time average is used.  Just to be exact.  So is it possible to do it like this: add `ETAN` (sea level height anomaly) to `drW[0]` and then perform the integration in a similar way:
```python
ds['drW2'] = ds.drW # is this a deep copy?
ds['drW2'][0] += ds.ETAN

ubt = (ds.UVEL * ds.drW2).sum('Z')
```

**Comment by jbusecke** [comment]
That heavily depends on which vertical coordinate system is used. 
I am not sure what the example uses but if it is a z (not z*) coordinate system, then you are right in adding the surface elevation. 

I personally have dealt with a lot of z* model output (MOM5) and there you have to infer the vertical cell depth as a function of (x,y,z,t) using something like [this](https://github.com/jbusecke/mom_xtools/blob/335db4b461b6e674cc384b563bb53a3d5a784552/mom_xtools/mom_budgets.py#L114). 
Either way you have to make sure that your vertical distances are correctly represented (which was your approach). The values of the depth dimensions are then only approximate but the budgets should be conserved. There are still issues with time averaging, but adding the surface should be a good first step.

**Comment by miniufo** [comment]
Thanks @jbusecke.  My data are on a z coordinate so I'll just add the surface elevation to get the right dz.

I happen to have a dataset from CM2.1 in which the coordinates are `['st_ocean', 'yt_ocean', 'xt_ocean']` (just the dataset no model info).  Is there any simple way to justify what kind of z-coordinate (z or z*) the data are defined on?  Could it be z* if the metrics are time varying?  If I understand it right, the model-output in case of z* would be more disk-consuming than that of z if we add more metrics variables?

**Comment by jbusecke** [comment]
Oh sorry just realized I never answered to this. I am pretty sure CM2.1 is run in z* coordinates. But I am not sure what a general way to determine this is...There are ways to reconstruct the time/space variable cell thickness (and thus the actual cell depth) if they werent saved, but the best thing is to output e.g. budget terms integrated over the cell depth. 

For the examples, the cell depth should take care of any variability, so I think we could close this?

**Comment by miniufo** [comment]
Hi @jbusecke, thanks for your explanation.  So cell-weighting is important to generalize the flux calculation in different grids.
