### ISSUE TITLE
add testing of mdsxray module

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#21]

**Comment by rabernat** [comment]
In order to accomplish this (and move forward with #30), we need a test MITgcm dataset which will either be distributed directly within the github repo or else downloaded during testing. Either way, it needs to be as complete as possible (in terms of variables output) and simultaneously as small as possible (in terms of domain size).

@pittwolfe, perhaps one of your very coarse-resolution basin models would do the trick. How big are those variables?

**Comment by pittwolfe** [comment]
The 3D fields are 25 x 100 x 20, so, for single precision, about 200kB each.

**Comment by rabernat** [comment]
That's about the same size as the global_oce verification experiments, so no real advantage to using your setup. What we really need is a genuinely tiny box model.

**Comment by rabernat** [comment]
This is addressed by #31. I will open a new issue for more refined tests.
