### ISSUE TITLE
Upgrade package infrastructure

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#213]
We have some problems with our infrastructure. Travis is broken. Dependencies need updating. Etc.

I think we need to 
- [ ] Move all testing to github actions
- [ ] Refactor setup.py to be a bit more modern (see [rechunker's setup.py](https://github.com/pangeo-data/rechunker/blob/master/setup.py) for some examples

This affects #211 and #212 at least.

**Comment by jbusecke** [comment]
Agreed. I will actually work on this right now before starting anything else because otherwise we have no control over what to merge or not.

**Comment by jbusecke** [comment]
We can absorb #212 into this aswell.

**Comment by jbusecke** [comment]
My idea is to model the github workflow/setup.py after rechunker. I have never used github actions, so I might need a few pointers. 

The first thing that comes to my mind, when looking at the[ci.yaml](https://github.com/pangeo-data/rechunker/blob/master/.github/workflows/ci.yaml) is that it does not use conda? Or am I reading it wrong?

**Comment by rabernat** [comment]
> when looking at the [ci.yaml](https://github.com/pangeo-data/rechunker/blob/master/.github/workflows/ci.yaml) is that it does not use conda?

That's correct. Pip is slower but generally simpler to use in ci. The same approach should work for xgcm if we want. Or we could use conda from github actions. No strong preference from me.

**Comment by dcherian** [comment]
I have this working quite well in cf-xarray: https://github.com/xarray-contrib/cf-xarray/blob/main/.github/workflows/ci.yaml

**Comment by jbusecke** [comment]
Ok Ill look into the conda approach, since I think the fine grained env files were quite helpful in detecting dependency issues early on, and I find them very helpful to have at hand to develop 😀

**Comment by jbusecke** [comment]
Ah awesome @dcherian. I'll get inspiration over there after lunch!

**Comment by jbusecke** [comment]
Closed via #214

**Comment by timothyas** [comment]
Hey there, I'm curious what happened with travis and/or why it was decided to move to Github Actions? I'm just wondering for my own projects, for which I've used travis and modeled my testing+ci structure from xgcm. And also, would it be necessary to switch over for xmitgcm? (which I can help out on that) Let me know if you want me to post this elsewhere too if you think it could be more helpful to others or anything like that.

**Comment by rabernat** [comment]
travis-ci.org stopped working for xgcm. Specifically, it stopped posting status updates on PRs, which is a really important feature. It might have something to do with the migration from travis-ci.org to travis-ci.com. Regardless, we determined that it was not worth the effort to debug travis, and instead put our effort into switching to github actions. Github actions are really amazing and obviously integrate best with github.

In the long run, yes, I think we want to be migrating all our projects from travis to github actions. Whether this is a priority depends on each project. We would absolutely welcome your help making this migration for xmitgcm!

**Comment by timothyas** [comment]
Makes sense, thanks @rabernat!
