### ISSUE TITLE
Does xWMT exist? Would it be useful?

### ISSUE THREAD

**Issue by hdrake** [xgcm/xgcm#216]
I've been writing some code based on xgcm & xhistogram to compute watermass transformations. I'm sure I'm not the first to do this, but I couldn't find any packages that do this or other more involved analyses.

Or would a more general package be useful, like `xocean`, or similar? It would come with functions for computing common derived quantities that can be daunting for first-time users? The following come to mind:
- residual overturning circulations
- watermass transformations
- tracer-moments (e.g. average temperature of a tracer patch, weighted by tracer concentration)
- diagnostic budgets (as opposed to budgets for prognostic variables, which are usually easier to close)

Most of these are generic enough calculations that they shouldn't be model specific.

**Comment by jbusecke** [comment]
Hey @hdrake,

that sounds pretty cool! 
I'd be very keen to see those.

I personally think that these types of quantities would profit more from thorough tutorials/docs rather than a "one-click" solution, but that is just my personal opinion and I would be curious to hear other input.

I think this way the user would gain more understanding about what is going on and could modify their analysis accordingly if needed.

Just FYI, we have the goal of creating the "go-to tool" for vertical coordinate transformation within xgcm very soon (@rabernat at has payed the foundation for this and I have some private code that builds on this which I will refactor). I think that might be very helpful for e.g. residual overturning.

**Comment by jbusecke** [comment]
cc @gmacgilchrist

**Comment by gmacgilchrist** [comment]
Thanks for the cc, @jbusecke. I have likewise been building code for these general calculations. I tend to agree with Julius that they can perhaps be better elucidated through tutorials than a specific package. The tricky part (at least in the sense that some non-arbitrary choices have to be made) seems to me to be the coordinate transformation (I have also been using xhistogram) and I think that the vertical coordinate functionality Julius and Ryan are working on will lend itself to that nicely. Perhaps a comprehensive tutorial to go alongside that new functionality would be sufficient?

That being said, I had wondered whether a small package to do some of the fiddly calculations (density flux from heat and freshwater fluxes; the "b-factor" for neutral density; perhaps checking/visualizing budget closure on the native grid) could be useful. I don't know if this is what you had in mind @hdrake ? It sounds like you were maybe thinking of something more comprehensive?

**Comment by rabernat** [comment]
Having been doing WMT calculations for nearly a decade, I personally feel that the complexity is too great to create a simple standalone function or package. There are just too many edge cases to consider, and every model is going to require a slightly different treatment. But I'd love to be convinced I'm wrong on this! 😁 

I believe the first step, and a useful step regardless, is to simply document and share what people are doing today. http://gallery.pangeo.io/repos/pangeo-gallery/physical-oceanography/ would be a great place to put such examples.

**Comment by rabernat** [comment]
> I had wondered whether a small package to do some of the fiddly calculations (density flux from heat and freshwater fluxes; the "b-factor" for neutral density;

Big 👍  to this. We already have https://github.com/xgcm/fastjmd95, which does some of these things.

**Comment by hdrake** [comment]
Thanks for your thoughts, @jbusecke @gmacgilchrist @rabernat 

I agree that it would be best to simply have some polished tutorials to do these kinds of calculations. I think it is worth writing these kinds of operations as model-specific functions within the tutorial itself, to get people in the habit of creating writing modular code :)

Something like
```python
def preprocess(ds):
    ...

def wmt(ds, bins):
   ...

ds = xr.open_mfdataset(...)
ds = preprocess(ds)
sigma_bins = np.arange(30., 45., 0.1)
ds.wmt = wmt(ds, sigma_bins)
ds.wmt.plot()
```

Are there any MITgcm or other simulations that have the output (snapshots of tendency terms) needed to do these kinds of calculations up on Pangeo? I'd be happy to either take a crack at it, or I can put together a really small 2D dataset and post it directly on github, just for illustrative purposes.

**Comment by rabernat** [comment]
> Are there any MITgcm or other simulations that have the output (snapshots of tendency terms) needed to do these kinds of calculations up on Pangeo?

My student @stb2145 has done closed WMT budgets for ECCOv4 with cloud data using xgcm and xhistogram. She is nearly ready to submit a paper focusing on the Weddell Sea. Once that paper is submitted, we can share the code.

If you're eager to move faster, we'd be happy to review any other examples you want to work with.

> Are there any MITgcm or other simulations that have the output (snapshots of tendency terms) needed to do these kinds of calculations up on Pangeo?

The only data I'm aware of is [ECCOv4](https://catalog.pangeo.io/browse/master/ocean/ECCOv4r3/). It's remarkably hard to come across ocean model data with fully closed heat and salt budgets. But if you have other data in mind, we'd love to see it.

**Comment by hdrake** [comment]
I've been doing budgets in my own idealized simulations but I don't have an atmosphere in any of mine so it's a lot easier :)

**Comment by dcherian** [comment]
Looping in @ALDepp who has been doing WMT things with POP2 at NCAR.

**Comment by rabernat** [comment]
> I've been doing budgets in my own idealized simulations but I don't have an atmosphere in any of mine so it's a lot easier :)

I doubt this changes the complexity much--in the end, you always just have a `TFLUX` and `SFLUX` which go into the tendency equations. However, the main challenge in ECCOv4 is dealing with the non-linear free surface and associated z* coordinate. The volume of the ocean changes, and this has to be accounted for in the WMT budget. Another reason why it's hard to develop a generic function for WMT...every model is a bit different.

**Comment by ALDepp** [comment]
Hi all, I am actually currently working on a WMT tutorial notebook for POP2. I second the notion that tutorials would be best here, some of the manipulations I have to do on POP output (because of the way some variables are output) are likely not needed in other models (and are not immediately obvious), so I think detailed documentation would be helpful.

**Comment by gmacgilchrist** [comment]
Just FYI, I have started putting together [tutorials](https://mom6-analysiscookbook.readthedocs.io/en/latest/10a_Watermass_transformation.html) for WMT calculation in MOM6. They step through different methods for transforming the vertical coordinate, including `xhistogram`, `xccm.transform`, and the online remapping in MOM6.

Updates are ongoing!

**Comment by gmacgilchrist** [comment]
Just a heads up to anyone still following this thread. Myself and @jetesdal have been working on WMT in MOM6 and have found that, at least in our efforts, building it up as a package actually works rather well. Getting the necessary tendencies or fluxes (and closing budgets) is still model-dependent of course, but given those as input, we're leveraging the transform method from xgcm (and some functionality uses xhistogram) to produce both maps and integrated values of WMT. @jetesdal is presenting some preliminary work at the CESM working group meeting this week, and we'll publish the package soon after, once we've done some more testing and generated examples. Very happy to work with others in expanding the functionality in the future, particularly to see how it can be increasingly generalized.

**Comment by hdrake** [comment]
> Just a heads up to anyone still following this thread. Myself and @jetesdal have been working on WMT in MOM6 and have found that, at least in our efforts, building it up as a package actually works rather well. Getting the necessary tendencies or fluxes (and closing budgets) is still model-dependent of course, but given those as input, we're leveraging the transform method from xgcm (and some functionality uses xhistogram) to produce both maps and integrated values of WMT. @jetesdal is presenting some preliminary work at the CESM working group meeting this week, and we'll publish the package soon after, once we've done some more testing and generated examples. Very happy to work with others in expanding the functionality in the future, particularly to see how it can be increasingly generalized.

Updating this thread to point out that the package mentioned by @gmacgilchrist above lives at [`xwmt`](https://github.com/NOAA-GFDL/xwmt). In PR [40](https://github.com/NOAA-GFDL/xwmt/pull/40), we've generalized the package API so that it is now model agnostic (at least in principle, we have not yet tested with another model), with the structure of the tracer budgets being specified by `yaml` files (see the [MOM6](https://github.com/hdrake/xbudget/blob/main/xbudget/conventions/MOM6.yaml) example) that can be read by [`xbudget`](https://github.com/hdrake/xbudget). We include [tutorial notebooks](https://github.com/hdrake/xwmt/tree/main/examples) showcasing the package in a few different use cases.

This `xwmt` package only handles the water mass transformation terms (derivatives of volume-integrated tendencies); we handle the other terms of the mass budget in [`xwmb`](https://github.com/hdrake/xwmb) (following the approach described in @stb2145's [Weddell Sea paper](https://os.copernicus.org/articles/19/381/2023/) but generalized to arbitrarily-shaped regions with vertical boundaries).

We welcome contributions or feedback from the WMT community!

**Comment by jbusecke** [comment]
Thanks for the update @hdrake! This looks awesome. I would strongly encourage to share this on the pangeo discourse forum or elsewhere more public too, since I am not sure how many folks will see this closed issue.

**Comment by jbusecke** [comment]
Thanks for the update @hdrake! This looks awesome. I would encourage to share this on the pangeo discourse forum or elsewhere more public too, since I am not sure how many folks will see this closed issue.

**Comment by hdrake** [comment]
Yes, that is the long-term plan but we need to write documentation for the packages first.
