### ISSUE TITLE
Test suite takes forever

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#223]
Our test suite is really taking a long time, prohibiting fast development and CI.

A quickish fix could be to run tests in parallel with [pytest-xdist](https://github.com/pytest-dev/pytest-xdist). 

I the long run I should probably trim down on the crazy parametrization matrix I built into `test_grid.py`.

**Comment by rabernat** [comment]
> I the long run I should probably trim down on the crazy parametrization matrix I built into `test_grid.py`.

I favor this option. 

This should explain how to diagnose the slow tests: https://stackoverflow.com/questions/27884404/printing-test-execution-times-and-pinning-down-slow-tests-with-py-test

**Comment by jbusecke** [comment]
I would do both, actually. Or are you opposed to xdist?

**Comment by jbusecke** [comment]
I have tried out the implementation of `pytest-xdist` in #226 and it shaves of 50% of the time it takes to run the tests! 1:30 min vs 3:xx min!

It is a very easy change in the code and I think we should implement it. I think we should still try to trim the test suite but that will be a much more time intensive task.

**Comment by jbusecke** [comment]
Another thing to look into could be using [mamba](https://github.com/mamba-org/mamba) instead of miniconda, since the setup of miniconda takes as long (longer if #226 is merged) than our actual tests.

**Comment by dcherian** [comment]
> Does anyone have experience with switching from conda to mamba and potential pitfalls?

cc @andersy005 

> we just have a ton (~4k) 

this is a bit ridiculous ;D

**Comment by jbusecke** [comment]
> this is a bit ridiculous ;D

I know, I know, is there a way to use pytest parametrization to create a 'sparser' matrix? Can def skip some of the options for some of the tests.

**Comment by andersy005** [comment]
> Does anyone have experience with switching from conda to mamba and potential pitfalls?

`goanpeca/setup-miniconda@v1` GitHub action has an experimental `mamba` feature (see this [example](https://github.com/conda-incubator/setup-miniconda#example-6-mamba)). Even though I've not tried it yet, I highly doubt that it'll significantly reduce the ~2min installation time you are noticing. The times you have in https://github.com/xgcm/xgcm/pull/226#issuecomment-690744370 look pretty good in my opinion.

**Comment by jbusecke** [comment]
Ok then i'll just put some time aside to reduce some of the testing parameterizations and otherwise leave it alone.

**Comment by jbusecke** [comment]
I am unsure if our caching is setup correctly in ourt [github actions](https://github.com/xgcm/xgcm/blob/10a11417d3cbc5daa99578ecef31c6c8cfefa91b/.github/workflows/ci.yaml#L28-L30c). There still seems to be packages solved for each time. Is that the expected behaviour (e.g. we are just saving the download time) or should this run even faster with caching? @andersy005 you were saying the times look good?

**Comment by andersy005** [comment]
> here still seems to be packages solved for each time. Is that the expected behaviour (e.g. we are just saving the download time) 

The only time that is being saved is the "download time", other than that the environment is re-created each time. I haven't played with the caching mechanism to confirm whether there's room for saving more time....

**Comment by andersy005** [comment]
Should we close this issue? It appears that the current CI runtimes are reasonable

![Screen Shot 2021-05-21 at 3 00 16 PM](https://user-images.githubusercontent.com/13301940/119197922-c117bc00-ba45-11eb-86e1-97aa940ee744.png)

**Comment by jbusecke** [comment]
Agreed
