### ISSUE TITLE
Globally set `fill_value` set on grid object is not propagated.

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#224]
I just discovered what I think is a bug:

Consider this simple example:
```
from xgcm import Grid
import xarray as xr
import numpy as np

z = np.arange(3)
z_right = z+0.5
ds = xr.DataArray(np.ones_like(z)*1e5, dims=['z'], coords={'z':z}).to_dataset(name='data')
ds = ds.assign_coords({'z_right':z_right})

grid = Grid(ds, coords={'Z':{'center':'z', 'right':'z_right'}},
            boundary='fill', fill_value=np.nan, periodic=False)
grid.interp(ds.data, 'Z')
```
This results in:

![image](https://user-images.githubusercontent.com/14314623/92794864-f24fd080-f37d-11ea-85cf-485dd378c971.jpeg)

Which is not what I would expect (the edge value should be padded with nan) and is not equivalent to the 'old-school' manual way:
```
grid.interp(ds.data, 'Z',boundary='fill', fill_value=np.nan)
```
![image](https://user-images.githubusercontent.com/14314623/92795073-190e0700-f37e-11ea-90b1-0ae3ba25de54.jpeg)

I think the issue is that `fill_value=0.0` is hardcoded in all axis methods as default. See [here](https://github.com/xgcm/xgcm/blob/9c83d5368193237d80f7282f94a76561e0711c51/xgcm/grid.py#L614) for example.

We should add a test that checks that results are the same if you specify `boundary` and/or `fill_value` via grid object or in the axis method. 

Pinging @dcherian

**Comment by jbusecke** [comment]
Just pining @dcherian. Can you confirm that this is actually a bug?

**Comment by dcherian** [comment]
> I think the issue is that fill_value=0.0 is hardcoded in all axis methods as default.

I think so. default `fill_value` should be `None` and if `None`, should get the default from `Axis` if set. Looks like this logic should be added to `_neighbour_binary_func`

**Comment by jbusecke** [comment]
Yes thats what I thought. That whole logic could use a thorough refactor (too many manual copy pastes required). Ill try to tackle this after #205. Would love some input on how to organize the code better from an xarray vet like you 😁
