### ISSUE TITLE
accessors through encapsulation

### ISSUE THREAD

**Issue by dcherian** [xgcm/xgcm#225]
How about this encapsulation approach to providing an accessor?

We could probably clean this up some; there's lots of repeated code. We can add reprs to make things clear etc. etc. and also implement `__dir__` appropriately to get tab completion

Fundamentally, this acts like an accessor. and users can call usual xarray methods on the thing and it will just work (There may be some subtlety about `__get__`, `__getattribute__`, `__getattr__` that i don't understand but this is all fixable).

I like it because it's clean and the grid object (metadata) is explicitly propagated without having to deal with xarray's inconsistencies around propagating coords, attributes etc.

``` python
from typing import Union


class XgcmAccessor:
    """ This forwards methods to the xgcm.Grid object"""

    def __init__(self, obj: Union[xr.Dataset, xr.DataArray], grid: xgcm.Grid):
        self.obj = obj
        self.grid = grid

    def __getattr__(self, key):
        from functools import partial

        # all Grid functions will need to have signature (xarray_object, ...)
        # which is true already
        # Could return wrapper with functools.wraps for nicer behaviour
        return partial(getattr(self.grid, key), self.obj)


class XgcmDataArray:
    """ This wraps a DataArray. """

    def __init__(self, obj: xr.DataArray, grid: xgcm.Grid):
        self.obj = obj
        self.grid = grid

    def __getattr__(self, attr):
        result = getattr(self.obj, attr)
        if isinstance(result, xr.DataArray):
            return XgcmDataArray(result, self.grid)
        else:
            return result

    @property
    def xgcm(self):
        return XgcmAccessor(self.obj, self.grid)


class XgcmDataset:
    """ This wraps a Dataset. """

    def __init__(self, obj: xr.Dataset, grid: xgcm.Grid):
        self.obj = obj
        self.grid = grid

    def __getattr__(self, attr):
        """ Appropriately wrap result if necessary. """
        result = getattr(self.obj, attr)
        if isinstance(result, xr.DataArray):
            return XgcmDataArray(result, self.grid)
        elif isinstance(result, xr.Dataset):
            return XgcmDataset(result, self.grid)
        else:
            return result

    @property
    def xgcm(self):
        return XgcmAccessor(self.ds, self.grid)
```

``` python
import cf_xarray


ds = xr.open_dataset("/home/deepak/.pop_tools/data/cesm_pop_monthly.T62_g17.nc")
grid, xds = pop_tools.to_xgcm_grid_dataset(ds, periodic=False)

xgcmds = XgcmDataset(xds, grid)

xgcmds.mean("time") # works
xgcmds.cf.mean("T")  # other accessors work
xgcmds.SALT.xgcm.interp(("X", "Y"), boundary="extend")  # works!
```

**Comment by Huite** [comment]
While I'm (currently) not a user of xgcm, I have a similar use case, where I'm trying to cart around some unstructured topology. This seems like a very clever approach, although it won't work yet for the methods, e.g.:

```python
xgcmds.isel(time=0).xgcm.interp(("X", "Y"), boundary="extend") 
```

Of course, Python allows for pretty easy wrapping of methods:
```python
from functools import wraps

def dataarray_wrapper(func, grid):
    @wraps(func)
    def wrapped(*args, **kwargs):
        result = func(*args, **kwargs)
        if isinstance(result, xr.DataArray):
            return XgcmDataArray(func(*args, **kwargs), grid)
        else:
            return result
    return wrapped
```

With e.g. an additional branch to `__getattr__`:
```python
import types

def __getattr__(self, attr):
    result = getattr(self.obj, attr)
    if isinstance(result, xr.DataArray):
        return XgcmDataArray(result, self.grid)
    elif isinstance(result, types.MethodType):
        return dataarray_wrapper(result, self.grid)
    else:
        return result
```

There isn't always a guarantee that the wrapped xarray method will deliver result in a matching grid, but this could be checked in the wrapping function, in which case it might return an ordinary xarray object, or an adjusted grid object?

At any rate, this seems like a rather powerful way of extending xarray -- or is it too clever?

**Comment by dcherian** [comment]
It's definitely too clever :) but #197 is also clever.

It's possible we could make an `XgcmIndex` that will propagate all this info in `ds.indexes`

**Comment by dcherian** [comment]
I think a better approach will be to create a `XgcmIndex` that contains the `Grid` object. Then an xgcm accessor can use that to do things.
