### ISSUE TITLE
Tracking coords across grid operations

### ISSUE THREAD

**Issue by kthyng** [xgcm/xgcm#227]
This is related to but an extension of issue #150. 

I have upgraded and tried the new keep_coords=True option discussed in #150 but it appears to only work for 1D coords. I am using ROMS and have 1D, 2D, 3D, or 4D coords associated with variables depending on the variable. Is it in the purview of xgcm to consider tracking coords like xarray does? I consider this to be a big advantage of using xarray. I don't know the guts of xgcm, but I would guess that since the grid object tracks where variables are located on the staggered C grid, coords could similarly be tracked along grid operations like derivative.

Here is a screenshot of the `xarray DataArray temp` of temperature straight from the `Dataset` vs. after taking `grid.derivative` on it. Dimensions are appropriately updated after the operation, and 1D coordinates `ocean_time` and `s_rho` are preserved, but none of the other coordinates that are more than 1D. What I would ideally like is for the coordinates (lon/lat/z, etc) to be updated with their `eta_v`/`xi_rho` equivalents that are appropriate after the derivative is taken, which are available in the `Dataset` but would be tracked in the `grid` object like metrics, etc.

![image](https://user-images.githubusercontent.com/3487237/92813109-31821f80-f386-11ea-832c-388bfc56c654.png)

I can work up a min working example if this is something that is of interest for xgcm. Otherwise I will work on it in a package specifically for ROMS output. Thanks!

**Comment by dcherian** [comment]
IMO we should fix this in xgcm and deprecate the `keep_coords` option. This code is working around an xarray inefficiency that I fixed a while ago.

**Comment by jbusecke** [comment]
Thanks for posting the details @kthyng.

Do I understand correctly, that you want to attach all 'matching' coordinates from `ds`, which are not in `ds.temp` to the derivative?

If that is the issue, a quick solution is to assign the derivative back to the dataset:
```
ds['temp_dy'] = grid.derivative(....)
ds.temp_dy
```
Could you try that and see if the output has the desired coordinates? 
This has come up before somewhere so if this is a solution to your problem, we should at least improve our docs and maybe consider some option in xgcm to attach all available coords from the source dataset (this will be a bigger undertaking though).

>IMO we should fix this in xgcm and deprecate the keep_coords option. This code is working around an xarray inefficiency that I fixed a while ago.

@dcherian  If I am interpreting the issue correctly this wont fix the problem (the `keep_coords` argument only preserves non-dim coordinates that still fit the derivative dataarray *from the source dataarray not the dataset*), but I generally agree with you on this. Would you raise a seperate issue for that?

**Comment by kthyng** [comment]
@jbusecke I see, yes, adding the derived `DataArray` to the original `Dataset` does indeed so what I want. I have been returning `DataArrays` that are not aware of their `Datasets`, so this would present a problem. However, I just learned that the xgcm `grid` object secretly stores the dataset it is derived from (`grid._ds`)?! This is so handy! I have already committed to passing around the grid object in dataset attributes, so this means that I could indeed use the dataset from the grid object to pass off the coordinates to the new DataArray. Does there happen to be a function that you know of to do this?

I'm still interested in @dcherian's thoughts too...

**Comment by dcherian** [comment]
Ooops, I totally misunderstood this issue. Sorry!

I was going off @rabernat's comment https://github.com/xgcm/xgcm/issues/150#issuecomment-532457417

> Yes: for now this is intentional. Xgcm drops all non-dimension coords from the inputs immediately. This makes alignment of slices less error prone and expensive.

which should be fixed.

re your actual question: I don't see any better solution. What you want requires stored state (all non-dim coord variables), since xarray won't associate those `lat_v, lon_u, ...` coordinates with the original `temp` DataArray on `lat_rho, lon_rho` when you pull it out of the original Dataset. So we need to associate the Grid object with the DataArray somehow; either in attrs as in xroms; or some other accessor-with-state magic.

**Comment by jbusecke** [comment]
First I want to clarify that I did not at all mean to dismiss @dcherian s input previously (my wording did not quite reflect that, apologies). I just wanted to separate these two realated issues as clearly as possible. 

@kthyng 
> I have already committed to passing around the grid object in dataset attributes, so this means that I could indeed use the dataset from the grid object to pass off the coordinates to the new DataArray. Does there happen to be a function that you know of to do this?

I do not think that this is part of xgcms current functionality, but I think this could be relatively easily achieved from xarray (possibly with xr.align? - @dcherian would know more about the xarray side of things). Since this has been requested multiple times I would be open to implement this. 

@dcherian 
> What you want requires stored state (all non-dim coord variables), since xarray won't associate those lat_v, lon_u, ... coordinates with the original temp DataArray on lat_rho, lon_rho when you pull it out of the original Dataset

As @kthyng pointed out correctly, we **do** store the full dataset in the grid object as `grid._ds`. Does that make it easier to get this working? I am thinking we could just do an optional `xr.align(output_da, grid._ds)`, or is that too naive?

I would really like to get @rabernat s take on this as well.

**Comment by dcherian** [comment]
This isn't alignment (which is "getting things on the same grid").

Ah I see a solution on the xgcm side (sorry very dense this morning!): 

``` python
for name, da in grid._ds.items():  # really self._ds.items()?
    if set(da.dims) <= set(result.dims):
        result.coords[name] = da
```

where `result` is the DataArray after `diff` operation for example:

**Comment by kthyng** [comment]
@dcherian It certainly would be handy from my perspective to have xgcm manage the coords for me. It seems like xarray might have a function for doing this that it uses to decide which coordinates match DataArrays when added to a Dataset?

**Comment by dcherian** [comment]
There isn't a function but this is the logic in xarray (the same as I typed up above)

https://github.com/pydata/xarray/blob/23dc2fc9f2785c348ff821bf2da61dfa2206d283/xarray/core/dataset.py#L1165-L1177
``` python
        needed_dims = set(variable.dims)

        coords: Dict[Hashable, Variable] = {}
        for k in self.coords:
            if set(self.variables[k].dims) <= needed_dims:
                coords[k] = self.variables[k]

        ...

        return DataArray(variable, coords, name=name, indexes=indexes, fastpath=True)
```

IMO this is a simple and easy fix in xgcm that should be done (@rabernat, @jbusecke  WDYT)

**Comment by jbusecke** [comment]
I think we should do it. I would prefer to have it enabled by a kwarg in the axis method (False by default to not break things for legacy applications).
