### ISSUE TITLE
Query grid object?

### ISSUE THREAD

**Issue by kthyng** [xgcm/xgcm#239]
Sorry if I have missed this, but is it possible to query an existing xgcm grid object for information? Something like ` grid.get_coords(array, axes)` such that `grid.get_coords(ds.temp, 'X')` would return 'center' (name of position). It would then also be useful to be able to generally query the position and return the name of the coord: `grid.get_coord_from_position('center')` would return 'xi_rho' (name of coordinate associated with that position and axis).

**Comment by jbusecke** [comment]
This functionality is available but currently not part of the public API.
I believe [grid.axes[axis]._get_axis_coord](https://github.com/xgcm/xgcm/blob/10a11417d3cbc5daa99578ecef31c6c8cfefa91b/xgcm/grid.py#L798-L803) does what you are looking for.

**Comment by kthyng** [comment]
Excellent! Thank you. 🙏  I would also like to be able to ask generally for information from the grid, like asking grid for the name of the coordinate given the position name and axis, but not associated with a particular array (what the second question above is after). Does that happen to be accessible?

**Comment by jbusecke** [comment]
`grid[axis].coords[position]` should do that.

**Comment by kthyng** [comment]
Thank you so much, I was able to get it to work with `grid.axes[axis].coords[position]`. I really appreciate you helping me figure this out! I'll close this now.
