### ISSUE TITLE
[FEATURE] Handle interpolation and differencing to internal boundaries

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#240]
**Is your feature request related to a problem? Please describe.**

Many ocean models have "internal" boundaries, i.e. outcrops of bathymetry, that manifest as missing values (NaNs) in the data variables. When we call `grid.interp` or `grid.diff` along the X or Y axes of such variables, we end up with NaNs whenever there is a boundary neighbor. This differs from how a GCM would handle such boundaries internally. A GCM would instead apply a different algorithm, like a Dirichlet or Neumann boundary condition, at these specific points.

**Describe the solution you'd like**

We should have the option to handle internal boundary conditions. This will require refactoring of our core low-level algorithms for `diff` and `interp`. Perhaps an opportunity to refactor those routines to use numba.

**Comment by jbusecke** [comment]
If I understand correctly this could be handled with #344? Ill keep open for now.
