### ISSUE TITLE
[BUG] grid.interp will decrease the size of the chunk and then fail to use the 'mapper' in the tutorial

### ISSUE THREAD

**Issue by liu-ran** [xgcm/xgcm#251]
'grid.interp' will decrease the size of the chunk and then fail to use the 'mapper' in the tutorial as the picture shows. The X dim of the chunk is not 270 any more after using the 'grid.interp'. But the array is still 270.  How to repair the chunk?
![微信图片_20200929225601](https://user-images.githubusercontent.com/48266323/94575825-3bbd7c80-02a7-11eb-9fba-15ef7de88570.png)

**Comment by liu-ran** [comment]
I guess that the wrong chunk size (269) leads to the error of the 'mapper(ekemean) '. How to deal with it?
![微信图片_20200929230608](https://user-images.githubusercontent.com/48266323/94576918-7d025c00-02a8-11eb-9e73-50392e155d39.png)

**Comment by dcherian** [comment]
I guess we should automatically rechunk after these operations.

For now use `eke = eke.chunk(-1)`

**Comment by rabernat** [comment]
The chunks that come out of xgcm are not evenly sized, so you don't get a complete picture from dask's `repr`.

I agree we should avoid creating these weird chunk structures.

**Comment by liu-ran** [comment]
Many thanks! @dcherian  It indeed repairs the chunk of the eke.  

But I still fail to use `mapper(ekemean)`. There is no error report. The Jupyter just told me the server broke down and will restart right now. However, I can use `mapper(variable)` to pain other simple physical variables as the picture shows. If I try to pain some calculated variables like the mean eke, the Jupyter ran for a long time and then broke down. 


![微信图片_20200929233444](https://user-images.githubusercontent.com/48266323/94580675-c3f25080-02ac-11eb-9629-ce736c9e039f.png)

**Comment by jbusecke** [comment]
@liu-ran this sounds like you are killing the kernel with the computation (which will only be executed in the plotting command). 

Could you provide some more details on how you load the data? Where are you running this? On the pangeo cloud? Or your local machine?

**Comment by jbusecke** [comment]
Should we leave this issue open? Or is the problem resolved @liu-ran?

**Comment by liu-ran** [comment]
Haha, it was resolved. I will close it. Thank you. @jbusecke 

> Should we leave this issue open? Or is the problem resolved @liu-ran?
