### ISSUE TITLE
[BUG] xgcm.transform requires argument `axis` - not described in API docs

### ISSUE THREAD

**Issue by cspencerjones** [xgcm/xgcm#253]
The new function `xgcm.transform` does not include the required argument `axis` in the API documentation. 

When I pass 
`grid.transform(vel0, target = rho_axis, target_data=(pd0-1000), method='conservative', mask_edges=True, suffix='_transformed')`

I get
`TypeError: transform() missing 1 required positional argument: 'axis'`

**xgcm version and environment**: v0.5.0

**Comment by rabernat** [comment]
Good catch @cspencerjones! Relevant docs are here: https://xgcm.readthedocs.io/en/latest/api.html#xgcm.Axis.transform

**Comment by jbusecke** [comment]
If you are using the grid method this is actually the right doc https://xgcm.readthedocs.io/en/latest/api.html#xgcm.Grid.transform, which includes the `axis` as far as I can see. Are you using the latest released version @cspencerjones?

**Comment by cspencerjones** [comment]
Ahh ok sorry my bad! I was apparently looking at `axis.transform` rather than `grid.transform`. This subtlety was lost on me.

**Comment by rabernat** [comment]
Perhaps we should consider removing all the `Axis` stuff from the public API.

**Comment by jbusecke** [comment]
Not a bad idea @rabernat. Could we raise another issue? I can group it in our ['refactor project'](https://github.com/xgcm/xgcm/projects/5)
