### ISSUE TITLE
conda install issue with v0.5.0?

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [xgcm/xgcm#254]
Aloha!  I'm not sure if this is actually a "look, it's not you, it's me" problem but I'm trying to `conda install` xgcm v0.5.0 into my main Pangeo environment and this is the result?

command: `conda install -c conda-forge xgcm`
result:
```Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: XXXXXXX/miniconda3/envs/pangeo

  added / updated specs:
    - xgcm


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xgcm-0.3.0                 |             py_0          38 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          38 KB

The following NEW packages will be INSTALLED:

  xgcm               conda-forge/noarch::xgcm-0.3.0-py_0


Proceed ([y]/n)? n


CondaSystemExit: Exiting.

**Comment by Thomas-Moore-Creative** [comment]
NB: `pip install xgcm==0.5.0` *does* seem to work.

**Comment by jbusecke** [comment]
Thanks for trying xgcm @Thomas-Moore-Creative , and sorry things got stuck at this very early stage.

I cannot reproduce this on my machine, so I assume the conda side of things is ok. Can you provide some more information about your environment (`conda list` should give all the installed packages). 

One thing you might try is set up a 'fresh' environment with `conda create --name xgcm_only xgcm`, does that get the newest version?

**Comment by Thomas-Moore-Creative** [comment]
Geez, no apologies needed @jbusecke.  You folks are providing the community very cool tools and it's most likely an issue with my specific environments ¯\_(ツ)_/¯ .  I'm going to start fresh and report back. Thanks for the assistance!

**Comment by Thomas-Moore-Creative** [comment]
Changes & actions: 

- updated conda to latest version: 4.8.5
- `conda create --name xgcm_only`
- `conda install -c conda-forge xgcm`

Result = `xgcm    conda-forge/noarch::xgcm-0.5.0-py_0` install success.

**Comment by Thomas-Moore-Creative** [comment]
Seems clear this was about either my version of conda, the environment I was installing into, or both.
