### ISSUE TITLE
Grid object confusion (outer/left)

### ISSUE THREAD

**Issue by cspencerjones** [xgcm/xgcm#255]
I had a chat with @jbusecke  about this already, but it's really easy to set up the grid object incorrectly and then get errors. Here is a minimal working example. 

```
import numpy as np
import xarray as xr
from xgcm import Grid
ds = xr.Dataset({"dat1": (["z_c"], np.ones(9)),
        "dat2": (["z_c"], np.linspace(0,20,9))},
                coords={'z_c': (['z_c',], np.arange(1,10)), 'z_l': (['z_l',], np.arange(0.5,9)),'z_o': (['z_o',], np.arange(0.5,11))})
grid = Grid(ds, periodic=False, coords={'Z': {'center': 'z_c', 'left': 'z_l', 'outer': 'z_o'}})
grid.transform(ds.dat1, target = np.arange(0,20,2), 
               target_data=ds.dat2, method='conservative', mask_edges=True, suffix='_transformed', axis = 'Z')
```

The error here is 
```
ValueError: operand to apply_ufunc has required core dimensions ['z_o'], but some of these dimensions are absent on an input variable: ['z_o']
```
and it comes from the fact that I have defined `left` and `outer` in the grid object. Is there any way we can make this clearer, prevent this behavior, or raise a warning?

**Comment by rabernat** [comment]
I agree 💯 on this. It's related to some existing issues, such as e.g. #111.

We need better checking and validation of inputs when constructing a grid.

**Comment by jbusecke** [comment]
I think this highlights two things we should implement:

a) We should not at all allow more than 2 dimensions per axis
b) It would be nice to have some better internal logic to 'switch' between coordinates (with possible 'guessing' of e.g. outer from center/left).

I have seen issues/confusion with setting up the grid object several times now, and will make it a priority to fix this with #111.

**Comment by rabernat** [comment]
> a) We should not at all allow more than 2 dimensions per axis

Disagree! MITgcm usually has all 4 populated, depending on the variable!

> b) It would be nice to have some better internal logic to 'switch' between coordinates (with possible 'guessing' of e.g. outer from center/left).

This is currently covered by the "default shifts" functionality. Did you mean improving that logic?

**Comment by jbusecke** [comment]
> Disagree! MITgcm usually has all 4 populated, depending on the variable!

Do you have an example of that? I am afraid I am not seeing how that would be a thing (I thought 'left'/'right' would always be a subset of 'outer'). But obviously I do not want to disrupt existing workflows.

> This is currently covered by the "default shifts" functionality. Did you mean improving that logic?

Not quite what I meant. To clarify,  I was talking more about some 'autogenerate'-ish capability to guess a coordinate like `outer` from a dataset that does not have it (like its done manually in the [docs](https://xgcm.readthedocs.io/en/latest/transform.html#Realistic-Data-Example)) 

![image](https://user-images.githubusercontent.com/14314623/94727599-fa6fb000-032c-11eb-8594-be468286a8c7.jpeg)

The `default_shifts` capability will come into play, once I understand how we can have more than 2 axis positions in one grid object.

**Comment by jbusecke** [comment]
>> a) We should not at all allow more than 2 dimensions per axis

>Disagree! MITgcm usually has all 4 populated, depending on the variable!

Instead of not allowing it, we could proceed as follows:

If more than 2 coordinates are present issue a warning that points to a (to be written) part of the docs on how to deal with many grid positions. This would have some instructions on how to modify the `default_shift` behavior (which was what caused this particular issue for @cspencerjones).

I think we should try to anticipate a 'common' use case (which I would argue is a 2 grid position setup?) and then provide more warnings to help users in finding a solution from the docs.
