### ISSUE TITLE
Documentation: "Getting started with XGCM for the CSIRO ACCESS-D model" [Documentation]

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [xgcm/xgcm#257]
I'm hoping to make possible the consumption of output from CSIRO’s “boutique” Climate Analysis Forecasting Ensemble (CAFE) system through XGCM.  I've started [a public repo](https://github.com/Thomas-Moore-Creative/Getting-started-with-XGCM-for-the-CSIRO-CAFE-system) and will document my progress (or NOT!) here in this issue.

This is possibly a self-serving issue as I'm working with this in-house output but hopefully documenting this process will help others, specifically those with `MOM4p1` or `MOM5` Arakawa B-grid output?

This documentation may help guide users when CAFE data becomes public.

I'm currently following along with the approach here: [https://xgcm.readthedocs.io/en/latest/example_MOM6.html](https://xgcm.readthedocs.io/en/latest/example_MOM6.html)

At first glance it seems my task is to do the same for a MOM5, tri-polar B-grid, what is done in the MOM6 example?

**Comment by dcherian** [comment]
This POP notebook (B-grid) might be useful: https://pop-tools.readthedocs.io/en/latest/examples/pop_div_curl_xr_xgcm_metrics_compare.html

**Comment by Thomas-Moore-Creative** [comment]
Thanks @dcherian - I'll have a look.  I'm wondering if there's a function out there that will take a GFDL `gridpsec.nc` file and generate the dictionaries needed for xgcm?

Also: I'm still a GITnoob and set the wrong label for this issue - but can't seem to figure out how to change it to `docs` =)

**Comment by dcherian** [comment]
> a GFDL gridpsec.nc file and generate the dictionaries needed for xgcm?

don't know. cc @raphaeldussin

**Comment by jbusecke** [comment]
> Also: I'm still a GITnoob and set the wrong label for this issue - but can't seem to figure out how to change it to docs =)

Done. Perhaps only the admins can do that?

> At first glance it seems my task is to do the same for a MOM5, tri-polar B-grid, what is done in the MOM6 example?

Thats a good start. I have worked quite a bit with MOM5 output, let me know if you need pointers.

> GFDL gridpsec.nc file and generate the dictionaries needed for xgcm?

Nope, not that I know of. But check your dataset attributes. The GFDL output was usually pretty good about metadata and it would work out of the box with xgcm (no `coords` dictionary needed).

**Comment by Thomas-Moore-Creative** [comment]
Thanks for all that @jbusecke - and I'd love pointers.  I wasn't able to find a specific "MOM5" example but maybe in my ignorance I'm making this harder than it needs to be?

**Comment by Thomas-Moore-Creative** [comment]
@jbusecke is there a complete list of the MOM5 data variables related to grid information that must be available for XGCM to work?  I'm trying to track down this info in a local run of MOM5 and not clear that it's available to me yet?

**Comment by jbusecke** [comment]
Can you post a screenshot of the variables you have? For the very basic stuff you only need the 'logical' grid indicies (e.g. 1-dimensional coordinates of your data). I could also make some time for a zoom, to see if we can figure this out a bit quicker in person?

**Comment by Thomas-Moore-Creative** [comment]
> Can you post a screenshot of the variables you have? For the very basic stuff you only need the 'logical' grid indicies (e.g. 1-dimensional coordinates of your data). I could also make some time for a zoom, to see if we can figure this out a bit quicker in person?

@jbusecke - very much would appreciate the personal chat via zoom.  Will DM you - I'm on Australia AEST time (-15HRS from New York?)

Meanwhile I'll further document what I've learned about the grid for Australia's "ACCESS-D" model below.

**Comment by Thomas-Moore-Creative** [comment]
**An ACCESS-D dataset someone is trying to make use of:**
![ACCESS-D_data](https://user-images.githubusercontent.com/36463906/95402750-2e198e00-095c-11eb-9a22-969d0d69ccf5.png)

This model is based on the Murray (1996) tripolar grid that has a bipolar Arctic region:
https://mom-ocean.github.io/assets/pdfs/MOM5_manual.pdf
(section 1.4 & 9.3)
![ACCESS-D_polar_grid](https://user-images.githubusercontent.com/36463906/95403167-31f9e000-095d-11eb-8143-3afa2584abf6.png)
![ACCESS-D_MOM5_B-grid](https://user-images.githubusercontent.com/36463906/95403255-69688c80-095d-11eb-889b-09893f95d660.png)

**Comment by Thomas-Moore-Creative** [comment]
# Two files with grid information:

**One "grid info" file associated with the dataset, including plot of "areat_t" showing tripolar structure:**
![ACCESS-D_grid_5](https://user-images.githubusercontent.com/36463906/95403365-c5cbac00-095d-11eb-982b-a39741332558.png)

**another "grid spec" file that seems to have grid info related to Figure 9.5 above**
![ACCESS-D_grid_1](https://user-images.githubusercontent.com/36463906/95403411-e431a780-095d-11eb-9e95-d731271a0592.png)
![ACCESS-D_grid_2](https://user-images.githubusercontent.com/36463906/95403419-e7c52e80-095d-11eb-9ac4-d70bf4d6710a.png)
![ACCESS-D_grid_3](https://user-images.githubusercontent.com/36463906/95403424-eb58b580-095d-11eb-8ca1-cf58b38cbe8e.png)
![ACCESS-D_grid_4](https://user-images.githubusercontent.com/36463906/95403427-eeec3c80-095d-11eb-93e2-6fa186319e4d.png)

**Comment by Thomas-Moore-Creative** [comment]
Very much appreciate the time and the chat @jbusecke .  I'll advance my efforts and report back.

**Comment by jbusecke** [comment]
If I don't get back to you with that mom supergrid to do etc conversion, please ping me!

**Comment by Thomas-Moore-Creative** [comment]
@jbusecke looking at figure 9.5 (from MOM5 manual) above I chose to use the metrics for (1,1) and (0,0), adding them up to get the `dxt` etc.

Here are some grabs of progress, I *think* it's working properly but we're going to run a short model run and turn on some internal MOM diagnostics that I can then compare xgcm results to directly?  Keen to do more thorough checking.

Also still keen to see what your "MOM supergrid" method was and if it jives with my guesses here?

![Screen Shot 2020-10-09 at 3 45 41 pm](https://user-images.githubusercontent.com/36463906/95545921-f2112680-0a4a-11eb-89ed-483e0f176de1.png)
![Screen Shot 2020-10-09 at 3 46 27 pm](https://user-images.githubusercontent.com/36463906/95545927-f8070780-0a4a-11eb-8edd-211eade5926d.png)
![Screen Shot 2020-10-09 at 3 46 51 pm](https://user-images.githubusercontent.com/36463906/95545931-fb01f800-0a4a-11eb-973d-455b338b0726.png)

**Comment by Thomas-Moore-Creative** [comment]
> If I don't get back to you with that mom supergrid to do etc conversion, please ping me!

[ the sound of a very happy and soothing **PING!**]

**Comment by jbusecke** [comment]
Couldt find it right now. Ill clock out today and report back next week. Sorry for the delay.

**Comment by jbusecke** [comment]
Actually I found it: https://github.com/jbusecke/gfdl_preprocessing/blob/master/notebooks/old/CM-O_suite_static_grid_files.ipynb

**Comment by jbusecke** [comment]
Oh that is a private repo...Ill invite you and move the stuff somewhere else soon...

**Comment by Thomas-Moore-Creative** [comment]
@jbusecke - no apologies needed.  Enjoy your Friday night and get back to it when you can.  Your engagement with our issues is much appreciated.

**Comment by jbusecke** [comment]
How about you use that now, and long term i'll factor it into [mom_xtools](https://github.com/jbusecke/mom_xtools/tree/master/mom_xtools)? I need to consolidate the ~5k repos I made at the beginning of my Postdoc eventually hahaha.

**Comment by Thomas-Moore-Creative** [comment]
really appreciate the engagement and help @jbusecke

**Comment by jbusecke** [comment]
@Thomas-Moore-Creative just wanted to give you a quick ping about the state of our example gallery. I have started to move our examples over to [xgcm-examples](https://github.com/xgcm/xgcm-examples), which builds this neat [gallery](https://gallery.pangeo.io/repos/xgcm/xgcm-examples/). I think your examples would fit in there nicely!

**Comment by Thomas-Moore-Creative** [comment]
Hey @jbusecke, thanks for all the great work on the examples and the gallery.  I'm always open to contributing.  At the moment what I'm doing isn't ready for prime time.  If I can carve some free time out I'll look at advancing things.  However I'd expect that others ( @navidcy ?) may have made better progress and might be better placed to contribute examples that will best help users?

**Comment by navidcy** [comment]
oh, thanks for pinging @Thomas-Moore-Creative, will have a look at this issue :)

**Comment by jbusecke** [comment]
Please ping me whenever I can be of help, @navidcy.
