### ISSUE TITLE
Put examples into a standalone repo / integrate with pangeo gallery

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#258]
Our list of examples is growing, and there are new proposals for examples / tutorials coming in (see #216, #257)

I would propose that we put the examples into a new repo (e.g. `xgcm-examples`) and use [pangeo gallery](http://gallery.pangeo.io/contributing.html) / [binderbot](https://github.com/pangeo-gallery/binderbot) to automatically build them in the cloud. Then we could use a git submodule in xgcm to make the built notebooks appear as part of the docs.

What do you think?

**Comment by Thomas-Moore-Creative** [comment]
Hi @rabernat, hopefully raising #257 in this repo was a constructive place to put it?  I'm happy to document anywhere that suits others.  I'm mainly trying to provide visibility of my embryonic efforts for when I hit the inevitable hurdles, hoping that might mean folks like @jbusecke could give me a boost. =)

**Comment by jbusecke** [comment]
Love this idea. Is there another example repo that we could use to get a feel for how the gallery/binderbot integtation works?

**Comment by rabernat** [comment]
We would start by creating a new repo following the pangeo-gallery [contributing guide](http://gallery.pangeo.io/contributing.html).

We would get it to the point where it builds cleanly for gallery.pangeo.io.

Then we add this repo (the "built" branch) as a submodule on the main xgcm docs page.

It's a little bit of a hack for now, but it would work well enough.

**Comment by jbusecke** [comment]
I have started this: https://github.com/jbusecke/xgcm-examples

Let me play a bit with it and then next week Ill start to migrate the notebooks and organize them?

**Comment by jbusecke** [comment]
I am running into errors during the [binderbot process](https://github.com/jbusecke/xgcm-examples/runs/1233401967?check_suite_focus=true). Does anybody have more knowledge about how to diagnose what is going on?

**Comment by rabernat** [comment]
Pangeo Gallery is up: http://gallery.pangeo.io/repos/xgcm/xgcm-examples/01_example-notebook.html

But there is only dummy content in there for now.

**Comment by jbusecke** [comment]
Brilliant! That was my intention for now. I would like to set up the full pipeline and then migrate/reorganize the notebooks. Does that sound ok?

**Comment by jbusecke** [comment]
Ok I have migrated all notebooks over to [xgcm-examples](https://github.com/xgcm/xgcm-examples). I am running into some issues with the mitgcm example (@rabernat is that data in the cloud somewhere so we can refactor?) and the MOM6 example (@raphaeldussin there seems to be some problem with the downloaded grid file, could you try to run the notebook from the `failed` folder in the [xgcm-examples](https://github.com/xgcm/xgcm-examples)? 

How should we proceed with the docs over here? Is there a way to process external notebooks with sphinx? Or should we just built a list of links to the notebooks and binders (probably easier).

**Comment by raphaeldussin** [comment]
@jbusecke I'll take a look this week

**Comment by jbusecke** [comment]
Awesome! Thanks @raphaeldussin
