### ISSUE TITLE
[BUG] `transform` error when `target_data` array has no name

### ISSUE THREAD

**Issue by cspencerjones** [xgcm/xgcm#260]
Here is a minimal example

```
import numpy as np
import xarray as xr
from xgcm import Grid
ds = xr.Dataset({"dat1": (["z_c"], np.ones(9)),
        "dat2": (["z_c"], np.linspace(0,20,9))},
                coords={'z_c': (['z_c',], np.arange(1,10)), 'z_l': (['z_l',], np.arange(0.5,9)),'z_o': (['z_o',], np.arange(0.5,10))})
grid = Grid(ds, periodic=False, coords={'Z': {'center': 'z_c', 'outer': 'z_o'}})
grid.transform(ds.dat1, target = np.arange(0,20,2), 
               target_data=ds.dat2.rename(None), method='conservative', mask_edges=True, suffix='_transformed', axis = 'Z')
```

It throws an error: `TypeError: dimension None is not a string`

Obviously, no-one is directly dropping the name of the dataarray, but the name will be dropped if e.g. density is calculated from temp and salinity using jmd95. 

This may not be a super common problem but it was kind of hard to debug so I'd like it if the error was more informative (or if it didn't happen at all).

I'm running on AWS.

**Comment by rabernat** [comment]
Perhaps we could raise a warning if  target_data has no name and then make up a fake name, like `_UNNAMED_`?

**Comment by jbusecke** [comment]
Sounds like a good plan. Ill work on this in the next days.

**Comment by jbusecke** [comment]
See #266 for a fix.

**Comment by jbusecke** [comment]
@cspencerjones, any chance you could check out this PR and see if that fixes the problem?
