### ISSUE TITLE
Unexpected transform behavior for decreasing target_data with missing values [BUG]

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#261]
I just ran into an issue with the transform module, when I tried to transform data onto a `target_data` set that has missing values and decreasing values along the axes:

For a simple test dataset with decreasing values along the `Z` axis I get the expected result, which is a value identical to the `target`, since I am interpolating the array onto itself.

```python
ds = xr.DataArray(np.array([6,5,4,3,2,1]), dims=['z'], coords={'z':np.array([1,2,3,4,5,6])}).to_dataset(name='test')
ds
grid = Grid(ds, coords={'Z':{'center':'z'}}, periodic=False)
expected = grid.transform(ds.test, 'Z', [4.0], target_data=ds.test)
expected
```
![image](https://user-images.githubusercontent.com/14314623/95347930-79b03700-088b-11eb-87d1-ecc803547ab0.jpeg)

But the results change, once I introduce nans at the beginning and end:
```python
# now introduce nans at the beginning and end
ds['test_nan'] = xr.DataArray(np.array([np.nan,5,4,3,2,np.nan]), dims=['z'], coords={'z':np.array([1,2,3,4,5,6])})
result = grid.transform(ds.test, 'Z', [4.0], target_data=ds.test_nan)
result
```
![image](https://user-images.githubusercontent.com/14314623/95348247-d6abed00-088b-11eb-8c43-cb427385e731.jpeg)

The `numpy.interp()` itself is able to handle nans in the data, but needs the x values (target_data in our context) to be increasing, which is why we implemented a simple internal [`flipping` mechanism](https://github.com/xgcm/xgcm/blob/b2fc97e29c6e262f69dc699d4c31dd2ad3ee53fc/xgcm/transform.py#L21-L24).

I think nans on the edge of the array circumvent the data to be flipped, because it only checks the first/last values. We should either remove missing values from the input in the core algo, or make the flipping decision based on the first/last non-nan value rather then the first/last value of the input array. 

My preferred solution would be the latter along the lines of:
```python
# if last theta value is smaller than first, assume the profile is monotonically decreasing and flip
theta_sign_test = theta[~np.isnan(theta)]
if theta_sign_test[-1] < theta_sign_test[0]:
    theta = np.flip(theta)
    phi = np.flip(phi)
```

Thoughts on whether this will affect performance negatively or if there is a more clever trick to do this @rabernat @dcherian ?

**Comment by dcherian** [comment]
what if you used `DataArray.sortby(dim, ascending=True)` instead of all this lower level logic?

**Comment by rabernat** [comment]
`all(np.diff(array) > 0)` is a good way to check monotonicity

**Comment by jbusecke** [comment]
> what if you used DataArray.sortby(dim, ascending=True) instead of all this lower level logic?

Its not needed for the other methods, just for interpolation. Furthermore this enables us to accomodate the case where some location can have a monotonically increasing profile and others a monotonically decreasing profile (not sure that is super relevant, but I think its more general.

> all(np.diff(array) > 0) is a good way to check monotonicity

I belive that is done within `np.interp` already. The goal of this is not to check for monotonicity, but instead to have a rough guess on whether the profile is increasing or decreasing with depth. This will still fail if the profile is e.g. nearly constant with noise, but I think that is ok in this case. The example I pasted however should be handled correctly, since it is strictly monotonic (when flipped).

**Comment by jbusecke** [comment]
Oh I think i misunderstood your comment @rabernat. So you are saying we should flip the array if `all(np.diff(array) > 0)`, if it is nonmonotonic it will result in nans anyways, and if it was true that `all(np.diff(array) < 0)`, we will get the values we want?

Is `all` faster than comparing the first/last element? This is assuming that `~np.isnan()` and `np.diff()` are equally fast (might be totally wrong...). This might be a bit of a rabbit hole. Ill try to fix the issue in  PR soon and then we can make a note to check this line if performance becomes an issue?

**Comment by jbusecke** [comment]
numba doesnt seem to like `all()`, so I went with my proposed implementation in #266
