### ISSUE TITLE
Add option to automatically define 'target' points in transform() [FEATURE]

### ISSUE THREAD

**Issue by paigem** [xgcm/xgcm#265]
I was wondering if it might be possible to automatically read in the values for the `target` argument in the `transform()` function. As it currently stands, the user needs (by my understanding) to manually define an array of `target` points. Perhaps there could be an added option `target=None` where the values of `target` could be taken directly from the input data. This could involve, e.g., defining an array based on the min and max values of the desired `target` data variable.

As a new user playing around with `transform()` this week, I found myself essentially doing this exact step manually and so thought I'd suggest this as a built-in option.

Discussed this briefly with @jbusecke earlier today.

**Comment by jbusecke** [comment]
Thanks for raising the issue @paigem. I really enjoyed the chat with you and getting a perspective on the process of getting to know xgcm from scratch.

I think it would be possible to implement something like this, but as I mentioned offline I am worried that determining the min/max of a large datasets could take a substantial amount of time. 

@dcherian @rabernat what do you think? We could maybe check the size and error out for datasets above a set size and explain that the `target` has to be manually specified or an additional option has to be turned on if the user is willing to wait?

We could allow integers to be passed, which would trigger the calculation of min/max of `target_data` and then assigns `target=np.linspace(target_data.min(), target_data.max(), target)` internally. We would have to set a reasonable default for the integer `target=20` value.

The user could then do something like `grid.transform(da, axis, target_data=...)`

**Comment by rabernat** [comment]
Thanks a lot for the suggestion Paige! I had never considered automatically defining `target`, but I see how that could be handy.

It's a bit analogous to [`numpy.histogram`](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html). You can explicitly specify the bins, or your can specify just a number of bins (with `bins=10` as the default). Internally, numpy has a very [sophisticated set of option](https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html#numpy.histogram_bin_edges) for choosing the bins.

@jbusecke raises a good point, that defining the bins requires you to know at least the range of the data, and for more sophisticated methods, something about the pdf. This can be expensive for large data.

My personal feeling is that building this logic into xgcm would potentially create more problems than it solves. I think the user should be "forced" to think about what bins to use.

Is is possible that your concern could be addressed via better documentation and explanation of this issue?

**Comment by paigem** [comment]
I can see the benefit of "forcing" the user to think about the target points, so that sounds reasonable @rabernat. 

I do think a bit more explanation in the documentation about how and why the user needs to define `target` would be helpful. Even something like what you and @jbusecke state above, that the user can, e.g., find the min and max values to define the target array, but that it's important to think about the bins to be used.

I'll mention that it appears some datasets have rough variable ranges in the metadata (e.g. the 'unpacked_valid_range' metadata in the NCEP GODAS dataset used in the [vertical transformation example](https://xgcm.readthedocs.io/en/latest/transform.html#Realistic-Data-Example)). If the metadata were more standardized across models, the min and max of a variable wouldn't require any calculation to determine.
