### ISSUE TITLE
Wanting to interpolate from isentropic dataset to PV space

### ISSUE THREAD

**Issue by winash12** [xgcm/xgcm#275]
I am coming here after reading this documentation https://xgcm.readthedocs.io/en/latest/transform.html . I have potential vorticity data in the following shape (16,73,144) . The last two dimensions are latitude and longitude and the first dimension is number of levels of potential temperature. This data was obtained by interpolating isobaric data to isentropic data. So I have a stack of isentropic levels from 260 K to 400 K in intervals of 10 . Now I want to interpolate to another vertical coordinate i.e. Potential Vorticity. This PV is also discretely ordered from 1 to 10. I want to be able to obtain potential temperature in PV space. I want to be able to plot Theta (or potential temperature) as a function of (PV, lat,lon). On a single PV surface I would like to plot potential temperature or theta. How can I do that using xgcm ?

**Comment by rabernat** [comment]
Thanks for this interesting question @winash12! Can I ask you to just post a bit of clarification that will help us help you.

- What are the *original* dimensions of your data? Presumably your reanalysis or model data started in pressure or sigma coordinates, not isentropic coordinates, correct?
- Did you calculate PV originally in pressure / sigma coordinates and then interpolate to isentropic coordinates? Or did you calculate it in isentropic coordinates?
- Could you post xarray's full repr for the DataArrays in question? You can obtain this by calling `print(data)`.

**Comment by winash12** [comment]
Thanks for your prompt response @rabernat ! 


> Thanks for this interesting question @winash12! Can I ask you to just post a bit of clarification that will help us help you.
> 
> * What are the _original_ dimensions of your data? Presumably your reanalysis or model data started in pressure or sigma coordinates, not isentropic coordinates, correct?

Yes the reanalysis data started off in isobaric space. 


> * Did you calculate PV originally in pressure / sigma coordinates and then interpolate to isentropic coordinates? Or did you calculate it in isentropic coordinates?

I calculated  PV  in isentropic coordinates - i.e. I calculated the Ertel's Potential Vorticity numerically. 

> * Could you post xarray's full repr for the DataArrays in question? You can obtain this by calling `print(data)`.

Ok so I am not using xarray. I am using numpy and netcdf - python.

**Comment by rabernat** [comment]
> Ok so I am not using xarray. I am using numpy and netcdf - python.

Xgcm is only compatible with xarray inputs. However, it should be easy to switch your analysis to xarray. Just open your files with xarray rather than netcdf4-python.

How did you interpolate your data to isentropic coordinates? I assumed you were already using xgcm for that, but I guess you have some other solution. (That's precisely what the `transform` function does.)

> On a single PV surface I would like to plot potential temperature or theta. How can I do that using xgcm ?

I believe it should be straightforward to accomplish this with xgcm's `transform` function. But first you will need to get your data into xarray and create an appropriate `xgcm.Grid` object for them. Once you show us the format of your DataArrays, we can help you figure out the exact command to use.

**Comment by winash12** [comment]
> > Ok so I am not using xarray. I am using numpy and netcdf - python.
> 
> Xgcm is only compatible with xarray inputs. However, it should be easy to switch your analysis to xarray. Just open your files with xarray rather than netcdf4-python.
> 
Excellent ! Will get back to you on that one ASAP !

> How did you interpolate your data to isentropic coordinates? I assumed you were already using xgcm for that, but I guess you have some other solution. (That's precisely what the `transform` function does.)
> 
Yes it's a custom interpolation that handles intersections with the earth's surface(through extrapolation)  and  eliminates superadiabatic layers
> > On a single PV surface I would like to plot potential temperature or theta. How can I do that using xgcm ?
> 
> I believe it should be straightforward to accomplish this with xgcm's `transform` function. But first you will need to get your data into xarray and create an appropriate `xgcm.Grid` object for them. Once you show us the format of your DataArrays, we can help you figure out the exact command to use.

I will try to get back to you on this one.

**Comment by winash12** [comment]
http://wind.mit.edu/~reanal/pv.html - I believe this is exactly what I want to do ! Plot potential temperature on the dynamical tropopause - which is defined as the surface having potential vorticity q of 2.0 PVU

**Comment by rabernat** [comment]
> Yes it's a custom interpolation that handles intersections with the earth's surface(through extrapolation) and eliminates superadiabatic layers

FWIW, we would be very interested in seeing if we could support this use case within xgcm. Can you link us to any code / documentation of the details of the algorithm? Besides the customizations you described, is linear interpolation?

**Comment by winash12** [comment]
> > Yes it's a custom interpolation that handles intersections with the earth's surface(through extrapolation) and eliminates superadiabatic layers
> 
> FWIW, we would be very interested in seeing if we could support this use case within xgcm. Can you link us to any code / documentation of the details of the algorithm? Besides the customizations you described, is linear interpolation?

I believe the details are in https://www.unidata.ucar.edu/software/gempak/ and I made some enhancements based on peer reviewed literature. I will add the details later on as another PR. 

Yes I use Newton- Raphson iteration.

**Comment by rabernat** [comment]
Out of curiosity, have you looked into metpy?

https://unidata.github.io/MetPy/latest/api/generated/metpy.interpolate.interpolate_to_isosurface.html

> A classic use of this function would be to compute the potential temperature on the dynamic tropopause (2 PVU surface).

**Comment by winash12** [comment]
> Out of curiosity, have you looked into metpy?
> 
> https://unidata.github.io/MetPy/latest/api/generated/metpy.interpolate.interpolate_to_isosurface.html
> 
> > A classic use of this function would be to compute the potential temperature on the dynamic tropopause (2 PVU surface).

No I have not ! Thanks for the heads up ! I will certainly look into that right away !.
