### ISSUE TITLE
Documentation not linking to pull requests properly

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#280]
The `` :pull:`263` `` syntax doesn't actually work

https://github.com/xgcm/xgcm/blob/828a53a27e378d1201dabfe587c46f001b76736b/doc/whats-new.rst#L15-L18

https://xgcm.readthedocs.io/en/latest/whats-new.html

**Comment by dcherian** [comment]
Need to fix here: https://github.com/xgcm/xgcm/blob/828a53a27e378d1201dabfe587c46f001b76736b/doc/conf.py#L69
to look like here: https://github.com/xarray-contrib/cf-xarray/blob/5c8844ca6c443f3d5a90c0ce2294cf4d162f4c53/doc/conf.py#L53-L56

**Comment by jbusecke** [comment]
Ah thanks for noticing this. Ill fix.
