### ISSUE TITLE
[DOC] broken link to pangeo?

### ISSUE THREAD

**Issue by dschwoerer** [xgcm/xgcm#284]
**How could the docs be improved? Additional examples, different wording, etc.**
[The link](http://pangeo-data.github.io):
`.. _Pangeo: http://pangeo-data.github.io`
forwards to some Website. My Chinese is not that good, but it feels that it is the wrong site?

**Comment by jbusecke** [comment]
😱  How did this happen? Thanks for raising the issue. @rabernat is https://pangeo.io/ the right replacement? Ill fix this right away.

**Comment by rabernat** [comment]
Already fixed in 6443b0ef8b9b01ecb206e60b74f08114f9d3d763

**Comment by rabernat** [comment]
and d2f393d0bfdf99223d4e7c60e489057341b628ef
