### ISSUE TITLE
Upstream dev build failing

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#286]
See error log e.g. https://github.com/xgcm/xgcm/runs/1474263999

The relevant error is

> Warning: Pip subprocess error:
  ERROR: Could not find a version that satisfies the requirement llvmlite<0.37,>=0.36.0.dev0 (from numba==0.53.0.dev0+305.g96bf1ea40->-r /home/runner/work/xgcm/xgcm/ci/condaenv.hi770ybr.requirements.txt (line 9)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0rc1, 0.33.0, 0.34.0rc1, 0.34.0, 0.35.0rc2, 0.35.0rc3)
  ERROR: No matching distribution found for llvmlite<0.37,>=0.36.0.dev0 (from numba==0.53.0.dev0+305.g96bf1ea40->-r /home/runner/work/xgcm/xgcm/ci/condaenv.hi770ybr.requirements.txt (line 9))

**Comment by rabernat** [comment]
This is related to pip's new dependency resolver: https://github.com/pypa/pip/issues/8099

**Comment by jbusecke** [comment]
I just skimmed that document and am not sure how to resolve this. I presume this is happening due to the upstream installs (they might not have migrated to the new pip version?). Do you have a feeling if we should wait for upstream changes or implement a temporary fix?

**Comment by supercode-r** [comment]
Collecting llvmlite<0.37,>=0.36.0.dev0 (from numba)
  Could not find a version that satisfies the requirement llvmlite<0.37,>=0.36.0.dev0 (from numba) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0.1, 0.12.1, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.23.2, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.27.1, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.32.1, 0.33.0rc1, 0.33.0, 0.34.0rc1, 0.34.0, 0.35.0rc2, 0.35.0)
No matching distribution found for llvmlite<0.37,>=0.36.0.dev0 (from numba)
(+1 that, got the same error) Please share if you were able to fix it.

**Comment by supercode-r** [comment]
pip install llvmlite==0.33.0
This worked for me.

**Comment by supercode-r** [comment]
`pip install llvmlite==0.33.0`
This worked for me.
