### ISSUE TITLE
Fill missing values in metric arrays? [FEATURE]

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#292]
As mentioned in #182 [here](https://github.com/xgcm/xgcm/issues/182#issuecomment-648349393) xgcm currently fails out when the metrics we use have missing values. 

We could very easily fix this by adding a `.fillna(0)` [here](https://github.com/xgcm/xgcm/blob/94377432d6678b9168ca132cd1b1c5564e37502b/xgcm/grid.py#L1744) but I am not sure that we want to do that every time. How much performance will this cost?

The other option I see is to catch the exception and provide a more helpful error message specific to xgcm? This could sound somthing like this: 

`xgcm cannot use the metric x, because it has missing values. Please fill missing values with `ds['x'].fillna(0)` before creating the grid`.

Thoughts?

**Comment by raphaeldussin** [comment]
@jbusecke this may be a little out-of-scope but one issue with filling missing values in coordinates with zeros is that it can mess up plots quite a bit. I wonder if using some type of extrapolation for coordinates (e.g. https://github.com/ajdawson/gridfill or https://github.com/raphaeldussin/HCtFlood) would be better?

**Comment by jbusecke** [comment]
Good point. In that case, I think I am getting more and more convinced to not alter the data automatically but instead build a better warning. 

These packages are very interesting for the stuff I am doing over at [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing) though! Thanks for the links.
