### ISSUE TITLE
What should be the metrics for a regular C-grid at the boundaries

### ISSUE THREAD

**Issue by tomchor** [xgcm/xgcm#306]
I'm having trouble understanding how to accurately define the necessary metrics for integration/differentiation for my grid. This is related to #291, and the fact that all the examples in that page assume you know what quantities like `hFacW` and `drF` represent in the `MITgcm` output. Since I've never run that model, I'm not 100% sure of how those quantities are defined.

Consider the 4-point 1D grid below with `xC[i]` for the centers and `xO[i]` for the outer points:

![Sketch_210203_074052 (2)](https://user-images.githubusercontent.com/13205162/106771087-750a4e00-65f3-11eb-882b-b41e86d7f823.jpg)

I understand that in the interior the distances should be probably defined just as `xC[i]-xC[i-1]`, but my questions are two:

- Should I define these distances separately for `xO`?
- How do I define those distances at the boundaries?

So I'd appreciate if someone could exemplify how the metrics need to be defined in a grid like this.

PS: Although I ask these questions with a general C-grid in mind, the model I'm using is [Oceananigans](https://github.com/CliMA/Oceananigans.jl).

**Comment by miniufo** [comment]
> Should I define these distances separately for xO?
I think one needs to define these if the grid is nonuniform.  Since `xgcm` aims to deal with non-uniform grids, it chooses to defined several metrics.

> How do I define those distances at the boundaries?
If this axis is periodic, boundaries is simple.  For those of non-periodic ones, I guess `extend` would be good enough?

**Comment by jbusecke** [comment]
Hi @tomchor, 

that is an interesting question, and I am not quite sure about a general answer. I think this will come down to the way boundary conditions are handled in your model?

For xgcm you need to provide metrics on the `xo1` point (the metrics have to be the same shape as the coordinates), but the crux will be to define the value of the metric, and whether it represents a partial cell (as you sketched) or invokes some sort of boundary condition. 

What operations are you trying to apply at the boundary? 
Which grid metrics does Oceananigans provide? If you could post some snapshots of those, perhaps I can get a better idea?

Something that might be relevant here could be masking in addition to the metrics (see #293).

**Comment by tomchor** [comment]
@jbusecke Thank you for the answer! Yeah, for now I could only make metrics work by using constant values for Δx, Δy and Δz, but I'm pretty sure that's wrong at the boundaries.

I have two set-ups: one in which that direction is periodic (so xO1 would be the same point as xO5) and another one where it's bounded (so xO1 would be the exact location of one wall, and xO5 would be the exact location of the other).

> For xgcm you need to provide metrics on the xo1 point (the metrics have to be the same shape as the coordinates), but the crux will be to define the value of the metric, and whether it represents a partial cell (as you sketched) or invokes some sort of boundary condition.

So if `len(xO)==5` and `len(xC)==4`, then the metrics for these respective points should also have length 5 and 4? (By the way, if that's true, that would be valuable information for the docs!)

> What operations are you trying to apply at the boundary?

I'm going to do mostly integrals, derivatives and interpolations. 

> Which grid metrics does Oceananigans provide? If you could post some snapshots of those, perhaps I can get a better idea?

Also, since the Oceananigans grids are always regular for now (and the model is so new) there aren't any grid metrics provided. (Although the model will start dealing with nonregular grids soon, so I should prepare for that.) We are now trying to figure out what metrics are necessary to [make Ocenananigans easier for xgcm](https://github.com/CliMA/Oceananigans.jl/issues/1334).

In any case, if you still wanna see an output, here's the output of a very simple test case that I ran:

```python
In [2]: ds
Out[2]: 
<xarray.Dataset>
Dimensions:  (time: 49, xC: 24, xF: 24, yC: 24, yF: 24, zC: 16, zF: 17)
Coordinates:
  * zC       (zC) float64 -3.875e+03 -3.625e+03 -3.375e+03 ... -375.0 -125.0
  * zF       (zF) float64 -4e+03 -3.75e+03 -3.5e+03 ... -500.0 -250.0 0.0
  * xC       (xC) float64 2.083e+04 6.25e+04 1.042e+05 ... 9.375e+05 9.792e+05
  * yF       (yF) float64 0.0 4.167e+04 8.333e+04 ... 9.167e+05 9.583e+05
  * xF       (xF) float64 0.0 4.167e+04 8.333e+04 ... 9.167e+05 9.583e+05
  * yC       (yC) float64 2.083e+04 6.25e+04 1.042e+05 ... 9.375e+05 9.792e+05
  * time     (time) float64 0.0 1.44e+04 2.88e+04 ... 6.768e+05 6.912e+05
Data variables:
    δ        (time, zC, yC, xC) float32 ...
    s        (time, zC, yC, xF) float32 0.006796 0.0133 0.02436 ... 5.255 5.25
    ζ        (time, zC, yF, xF) float32 ...
    Δx       float64 4.167e+04
    Δy       float64 4.167e+04
    Δz       float64 250.0
Attributes:
    Δx:                    41666.666666666664
    Δy:                    41666.666666666664
    interval:              14400.0
    Oceananigans:          This file was generated using Oceananigans v0.47.0...
    Julia:                 This file was generated using Julia Version 1.5.3\...
    Δz:                    250.0
    date:                  This file was generated on 2021-02-08T19:43:11.636.
    output time interval:  Output was saved every 4 hours.
    schedule:              TimeInterval
```

**Comment by jbusecke** [comment]
> I'm going to do mostly integrals, derivatives and interpolations.

The integral clearly should have a smaller Δx in this case (I think this is a prime example for having an additional masking array!), but how is a derivative or an interpolation defined at the boundary point? There must be some sort of 'ghost' point outside the wall?
Our philosophy for xgcm is to reproduce as exactly as possible what models are doing internally. Do you know how your model handles such a case?

**Comment by jbusecke** [comment]
#240 might be relevant here too!

**Comment by jbusecke** [comment]
> Also, since the Oceananigans grids are always regular for now (and the model is so new) there aren't any grid metrics provided. (Although the model will start dealing with nonregular grids soon, so I should prepare for that.) We are now trying to figure out what metrics are necessary to make Ocenananigans easier for xgcm.

This is fantastic. Please let me know what I can do to help!

**Comment by jbusecke** [comment]
```python
Dimensions:  (time: 49, xC: 24, xF: 24, yC: 24, yF: 24, zC: 16, zF: 17)
```
It seems that in this case the setup is a bit different from your sketch? I might misunderstand this here, but it seems that both x and y coordinates have the same number of elements?

**Comment by tomchor** [comment]
> but how is a derivative or an interpolation defined at the boundary point? There must be some sort of 'ghost' point outside the wall?
Our philosophy for xgcm is to reproduce as exactly as possible what models are doing internally. Do you know how your model handles such a case?

Yes, it uses ghost cells outside of the domain. But I don't expect derivatives to work at the boundaries out of the box anyway! I was just mentioning that I'll def use xgcm for that.

However, that said, my understanding is that the metrics should be a function of the grid and BCs alone. And then you might need to pass appropriate BCs for specific operations (derivatives and interpolations at boundaries being the most obvious) since the metrics alone has limitations. Is that really how it works or do I have the wrong idea?

**Comment by tomchor** [comment]
> Dimensions:  (time: 49, xC: 24, xF: 24, yC: 24, yF: 24, zC: 16, zF: 17)
It seems that in this case the setup is a bit different from your sketch? I might misunderstand this here, but it seems that both x and y coordinates have the same number of elements?

@jbusecke Yes! I'm sorry, I should have clarified. In this example dataset x and y are periodic (`xC` are center points and `xF` are left points using xgcm terminology). The z axis is bounded, so `zC` are center points and `zF` are outer points. In this case the `z` coordinate is the one corresponding to my original sketch!

**Comment by jbusecke** [comment]
> However, that said, my understanding is that the metrics should be a function of the grid and BCs alone. And then you might need to pass appropriate BCs for specific operations (derivatives and interpolations at boundaries being the most obvious) since the metrics alone has limitations. Is that really how it works or do I have the wrong idea?

I think it is even more simplistic. The basic operations are `grid.diff` and `grid.interp`, which are literally just a finite difference and a simple linear interpolation between two neighboring points (this is where the boundary conditions are applied and the grid position is changed). The metrics are then used to convert e.g. the difference of two values into a derivative (by simply dividing it with the metric).

I just ran through this simple example:
```python
import xarray as xr
import numpy as np
from xgcm import Grid
zC = xr.DataArray(np.arange(10)+0.5, dims=['zC'])
zF = xr.DataArray(np.arange(11), dims=['zF']) 
tracer = xr.DataArray(np.arange(10)*20, dims=['zC'])
vel = xr.DataArray(np.ones(11), dims=['zF'])
dzF = xr.DataArray(np.hstack([0.5, np.ones(9), 0.5]), dims=['zF'])
dzC = xr.DataArray(np.ones(10), dims=['zC'])
ds = xr.Dataset({'tracer':tracer, 'vel':vel}, coords={'zF':zF, 'zC':zC, 'dzF':dzF, 'dzC':dzC})
ds
```
<img width="586" alt="image" src="https://user-images.githubusercontent.com/14314623/107405036-e145ef80-6ad4-11eb-9670-eb41f760b6b3.png">

```python
grid = Grid(
    ds,
    periodic=False,
    coords={'Z':{'center':'zC', 'outer':'zF'}},
    boundary={'Z':'extend'},
    metrics={'Z':['dzF']}
)
grid
```
<img width="334" alt="image" src="https://user-images.githubusercontent.com/14314623/107403839-9bd4f280-6ad3-11eb-9bdc-b1cd211f4742.png">

```python
grid.derivative(ds.tracer, 'Z')
```
<img width="579" alt="image" src="https://user-images.githubusercontent.com/14314623/107404758-9926cd00-6ad4-11eb-9036-f634b072fd26.png">


In this case with `boundary='extend'` the outermost tracer value is repeated beyond the first `zF` value and thus the difference (and derivative) is zero. The metric value does not matter in this case. This would of course be different for another boundary condition like `fill` (which fills the value beyond with a constant value):
```python
grid.derivative(ds.tracer, 'Z', boundary='fill', fill_value=0)
```
<img width="570" alt="image" src="https://user-images.githubusercontent.com/14314623/107406000-ea838c00-6ad5-11eb-9608-4554c600c1c4.png">


The metric values definitely matter if you e.g. try to integrate a variable on the `zF` coordinate. 

```python
grid.integrate(ds.vel, 'Z')
```
<img width="582" alt="image" src="https://user-images.githubusercontent.com/14314623/107405311-2c600280-6ad5-11eb-90b1-eb2dc3b8b019.png">


In this case the boundary condition is irrelevant, since the integral is just the sum of (value * metric) of every grid point. The result for a uniform metric array would have been `11`, which would be incorrect I believe. 

Does this help, or the opposite (sorry I am a bit dense this morning).

**Comment by tomchor** [comment]
@jbusecke Thank you very much for the example. It helps a lot! For me this has valuable information that I couldn't get from the docs. For example your definitions of `dzF` and `dzC` tell me that it this metric is the extent "around" a particular point, and not the distance between that point and the next one (the distinction is unimportant in the interior, but important at the boundaries, like you pointed out).

Just a quick question. You define the `Z` metrics as

```python
    metrics={'Z':['dzF']}
```

but how does xgcm know that that specific metric pertains to `zF` points and not `zC` points? For example, in my head something like this would be necessary:

```python
    metrics={'Z': dict(zF='dzF')}
```

(or `metrics={'Z': dict(zF='dzF', zC='dzC')}` if we're being more general.)

**Comment by tomchor** [comment]
> This is fantastic. Please let me know what I can do to help!

Thanks! I think for know I'm doing most of the Oceananigans-`xgcm` effort since most of the other collaborators and devs use Julia for postprocessing. So just by helping me understand xgcm a bit better you're already helping.

That said, feel free to read that Oceananigans github issue (or other issues there) and chime in with some `xgcm`-specific or even general knowledge. Very few of us there have a lot of experience with the usual GCMs (MITgcm, ROMs, etc), so we're not even sure of what metrics are generally useful to output in a general sense.

**Comment by jbusecke** [comment]
> but how does xgcm know that that specific metric pertains to zF points and not zC points?

This is purely based on the convention that metrics are 'centered' on their coordinates, and the rest is some bookkeeping with xarray internally. "this metric is the extent "around" a particular point, and not the distance between that point and the next one", hits the nail on the head. And I think it originated from MITgcm conventions. I will make sure to add that to the docs.

**Comment by rabernat** [comment]
> This is purely based on the convention that metrics are 'centered' on their coordinates

I think it's a bit more soid than that. Xarray's broadcasting rules come into play. You will frequently be multiplying / dividing the variables by the metrics. Xarray assumes that variables with the same dimension ('zF' and 'zF') are located at the same location and so can be broadcasted easily.

**Comment by jbusecke** [comment]
Right. The metric that describes the cell 'around' a given data-point (area or the cell, volume of the cell, distances between bounding cell faces) has the same coordinates so that broadcasting and arithmetic can be easily applied with xarray.

**Comment by tomchor** [comment]
Thanks to everyone. I think by now I'm been able to understand exactly what metrics are and how to apply it to a general output. I've also been able to run a few successful examples using Oceananigans output by now so I'm closing this issue.

**Comment by rabernat** [comment]
🎉 

But we should think about how to update the docs to reduce new-user confusion.

**Comment by tomchor** [comment]
Honestly just looking at @jbusecke's toy example with a random array got rid of 90% of my confusion. Given it's a small amount of lines, I'd consider including something like that in the docs before you pull up the MITgcm output.

**Comment by jbusecke** [comment]
Will put that in #271, including some of the descriptions that were used here. Thanks for your patience @tomchor. I would love to include an Oceananigans example over in https://github.com/xgcm/xgcm-examples. If you have a notebook that you would like to share, that would be awesome!

**Comment by tomchor** [comment]
Thank _you_ for the patience (you cooked up a whole example for this issue!).

I'd like to create an example using Oceananigans output for xgcm at some point, but at the very least I think it'd be good to wait until [the Oceananigans-xgcm issue](https://github.com/CliMA/Oceananigans.jl/issues/1334) is resolved. I think the example is bound to be confusing if we have to create all the metrics by hand in Python. (I created [this script](https://github.com/tomchor/pynanigans/blob/e4f3eefc8056c78457c2b5430d78cd804ca760ef/__init__.py#L55-L64) for personal use that does it automatically for now if you're curious about what that would look like.)

Also, I plan to create an example in the Oceananigans docs that outputs to NetCDF (all the examples there output in a Julia format at the moment). So it would be nice if I could link an existing example from Oceananigans that people literally run in a few minutes on their laptop and then use the generated file to reproduce the xgcm example.

But let me know if you disagree! I may be missing something aspect.

**Comment by jbusecke** [comment]
> Also, I plan to create an example in the Oceananigans docs that outputs to NetCDF (all the examples there output in a Julia format at the moment). So it would be nice if I could link an existing example from Oceananigans that people literally run in a few minutes on their laptop and then use the generated file to reproduce the xgcm example.

That sounds super dope! Ill chime in over at https://github.com/CliMA/Oceananigans.jl/issues/1334 in a bit!
