### ISSUE TITLE
zonal means

### ISSUE THREAD

**Issue by dcherian** [xgcm/xgcm#310]
How are people computing zonal averages these days? There's a conversation over at pop-tools (https://github.com/NCAR/pop-tools/issues/33) around an existing FORTRAN program to do this. 

Since this is a common community need, I am wondering if people have thoughts on how we might collaborate on an xarray-aware implementation.

One solution would be to implement conservative regridding using a 2D gufunc like what was done with 1D regridding. This would line up with the `grid.coarsen` feature request IIUC.

**Comment by jbusecke** [comment]
I have gone the xESMF route for a recent project, but I am not sure if it fulfills the strict requirements raised over at pop-tools. It was focussed on the equator, where zonal averages should be pretty straightforward...

I would favor a solution that uses/improves xESMF to do this, and then we can feed the data back to xgcm for the average?
As far as I can tell xESMF has a bunch of momentum right now, so it would be nice to see if it can solve this problem. This does require a reliable aggregation/reconstruction of grid metrics (which would be of interest to me in general and in particular for [cmip6_preprocessing](https://github.com/jbusecke/cmip6_preprocessing)). @dcherian is this something that has been discussed over at cf-xarray? (Its a bit offtopic but basically I would like a reliable way to reconstruct area from lat/lon vertices)

> This would line up with the grid.coarsen feature request IIUC.

I actually envisioned `grid.coarsen` to be strictly logical (e.g. n x m grid boxes), and not related to actual dimensions. Basically my idea was to wrap `xarray.coarsen` with some understanding of metrics.

**Comment by briochemc** [comment]
Sorry to revive this "stale" issue, but I too would like to know:

> How are people computing zonal averages these days?

Is it possible for xesmf to do a grid-aware zonal mean that takes into account the areas of "distorted"  cells in tripolar grids?
