### ISSUE TITLE
Allow `fill_value` for the flag `boundary='extend'`

### ISSUE THREAD

**Issue by roxyboy** [xgcm/xgcm#314]
Currently when the flag `boundary='extend'` is set, the values outside the array are set to their closest array value: https://github.com/xgcm/xgcm/blob/86c9641427b278239f2c4b55886fd113d837057f/xgcm/grid.py#L105

Would it make sense to allow for the option of `fill_value` for such case, e.g. zero for stream functions at the lateral boundaries, similar to the case of `boundary='fill`?

**Comment by rabernat** [comment]
Isn't that what `boundary='fill', fill_value=0` does? How would this be different?

**Comment by roxyboy** [comment]
The docstring states that `boundary='fill'` prescribes a Neumann condition so my (naive) understanding was that it would prescribe a boundary condition where the difference at the boundary would be zero with `fill_value=0` instead of prescribing zero for the absolute value at the boundary...

**Comment by rabernat** [comment]
The docs are wrong! 😄  I think we got Neumann and Dirichlet backwards. PR would be very welcome to fix this.

However, the more basic teminology is accurrate.

"Fill" is just what it sounds like. It fills in the fill_value on the boundary.

"Extend" is just what is sounds like. The field close to the boundary is "extended" with the nearest value. This is a limited sort of Neumann boundary condition in which the derivative is zero.

**Comment by roxyboy** [comment]
Ok, thanks for the explanation and I'll work on a PR :)
