### ISSUE TITLE
Interpolate CMIP6 data into reanalysis grid

### ISSUE THREAD

**Issue by jdldeauna** [xgcm/xgcm#318]
Hello! Thanks for this great package, I’ve been able to use xgcm to transform data variables into density coordinates. I was also hoping to use it to interpolate CMIP6 data into [reanalysis data depth levels](https://github.com/jdldeauna/GitHub-Issues/blob/master/Interpolate%20CMIP6%20data%20to%20reanalysis%20grid.ipynb), but I’m confused as to how to assign coordinates to do this appropriately. I also wonder how data such as World Ocean Atlas (which has less info available compared to CMIP6 data) can be used for interpolation. I would appreciate any insights. Thank you so much!

**Comment by jbusecke** [comment]
Hi @jdldeauna, officially welcome to the xgcm package!

I just checked the docs and you are absolutely right, this scenario is not covered (but it should!). To transform to different values on the same data (here depth), you simply have to simply not give any `target_data` input. `xgcm.transform()` knows which dimension of your dataset is associated with the axis you provide (I think that should be `Z` in your case), and then you just need to give the new depth spacing.

Ill illustrate this with the example in the [docs](https://xgcm.readthedocs.io/en/latest/transform.html#Linear-Interpolation)
```python
# repeating steps from the docs
import numpy as np
import xarray as xr
from xgcm import Grid

from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
ds  = cat["GODAS"].to_dask()


level_outer_data = np.pad(ds.level_w.values, [1, 0])
level_outer = xr.DataArray(
    level_outer_data,
    dims=['level_outer'],
    coords={'level_outer': ('level_outer', level_outer_data)}
)
ds = ds.assign_coords({'level_outer': level_outer})

grid = Grid(ds, coords={'Z': {'center': 'level', 'outer': 'level_outer'},
                        'X': {'center': 'lon', 'right': 'lon_u'},
                        'Y': {'center': 'lat', 'right': 'lat_u'}},
            periodic=['X'])

salt = 1000 * ds.salt
```

Now all you have to do is either leave the `target_data` argument out or set it to `None`:
```python
target_z_levels = np.array([1,100, 1000, 3000])
salt_on_different_z = grid.transform(salt, 'Z', target_z_levels, target_data=None, method='linear')
salt_on_different_z
```
And now you have your dataset on the values given by `target_z_levels`:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/14314623/112995915-b7569400-9139-11eb-9020-c0ade5ef42c6.png">

Let me know if that works in your case.

Also would you want to add your example to the documentation? It would be a great first Pull Request to work on and will help future users with understanding this feature better. I will help wherever I can!

**Comment by jdldeauna** [comment]
Hello @jbusecke thank you so much! I was trying to [apply transform to my data](https://github.com/jdldeauna/GitHub-Issues/blob/master/Interpolate%20CMIP6%20data%20to%20reanalysis%20grid.ipynb) but unfortunately I keep getting this error:

```
KeyError: "None of the DataArray's dims ('member_id', 'time', 'lev', 'lat', 'lon') were found in axis coords."
```
Does this mean that any target z levels should have the same coordinates as the data to be transformed?

I was also trying to do the example from the docs, but I would run into this error:

```
ValueError: Bad Request: https://www.googleapis.com/download/storage/v1/b/pangeo-ncep-godas/o/.zmetadata?alt=media
b'User project specified in the request is invalid.'
```

Again, thank you so much for your help! I really appreciate your patience as I am trying to figure this out.

**Comment by jdldeauna** [comment]
Hi! I was able to [apply the transform ](https://github.com/jdldeauna/GitHub-Issues/blob/master/Interpolate%20CMIP6%20data%20to%20reanalysis%20grid.ipynb)to the reanalysis data, sorry for misunderstanding the example.

I did want to ask if the [link](https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/) from the example in the docs is down, or maybe I just don't have access? Thanks!

**Comment by jbusecke** [comment]
Hi @jdldeauna, 
> Hi! I was able to apply the transform to the reanalysis data, sorry for misunderstanding the example.

That looks very cool (and the model temperature looks very wrong 😬). There is absolutely no need for you to apologize. I think the documentation is just not clear enough. If you are interested I would love to work with you to improve it! Can you think of ways to make the example easier to understand? What would have helped you to figure this problem out quicker?

>I did want to ask if the link from the example in the docs is down, or maybe I just don't have access?

I am still a bit unsure where exactly this link is referenced in the docs? If you could screenshot the section, that would be helpful.

**Comment by jbusecke** [comment]
I have reopened this for now, just so I can keep track.

**Comment by jdldeauna** [comment]
Hello @jbusecke thanks for the replies!

> Can you think of ways to make the example easier to understand? What would have helped you to figure this problem out quicker?

I think mainly from reading the [documentation](https://xgcm.readthedocs.io/en/latest/transform.html) I thought that transform only worked when both theta and phi were a function of the same z. I didn't connect that because I could use arbitrary target values, I could then specify target_data=None and transform would just interpolate the data to those target values. I also had to look up periodic boundary conditions, which I then assigned as "False" for my data. Maybe there is room for an example like this on the xgcm page? Not necessarily mine, but just in case others are also trying to do something similar.

> I am still a bit unsure where exactly this link is referenced in the docs?

I was running into errors trying to do the xgcm examples which utilized the Pangeo catalogs (following your initial reply to this issue). I opened an issue [here](https://github.com/pangeo-data/pangeo-datastore/issues/124), and then realized that it was because I didn't have a Pangeo Cloud account, so that is my mistake. 😬😅

**Comment by jbusecke** [comment]
> I was running into errors trying to do the xgcm examples which utilized the Pangeo catalogs (following your initial reply to this issue). I opened an issue here, and then realized that it was because I didn't have a Pangeo Cloud account, so that is my mistake. 😬😅

Ah I see, were you able to sign up? If not, please let me know and I'll make sure you get an account.

> Maybe there is room for an example like this on the xgcm page? Just in case others are also trying to do something similar. I would be happy to work on and develop my notebook as an example, but I'm not sure it's up to par with the others.

Absolutely. I think a short example how to interpolate onto different depths (instead of another variable) would fit very well into the [existing transform doc page](https://github.com/xgcm/xgcm/blob/master/doc/transform.ipynb) (which is just a notebook). I'd encourage you to edit that to your liking, and submit a pull request. Let me know if the instructions in the [contributor guide](https://xgcm.readthedocs.io/en/latest/contributor_guide.html) explain the process in sufficient detail. If they don't (I am afraid they might not), do not hesitate to contact me, and I can help you get started.

> I also had to look up periodic boundary conditions, which I then assigned as "False" for my data.

I forget to do that all the time myself. I think that needs to be emphasized more clearly. This would be another helpful part to include in the PR.
