### ISSUE TITLE
Apply black formatting to the docs

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#326]
In #325 we saw some minor formatting issues that would benefit from applying black formatting to all python blocks in our documentation. 

I saw this package: https://github.com/asottile/blacken-docs, but wanted to open an issue to discuss how this could be done best.

Ideally I would like this to be part of the pre-commit action.

**Comment by jbusecke** [comment]
I believe this was indeed implemented in #330? @andersy005 can you confirm this?

**Comment by andersy005** [comment]
@jbusecke, 

> I believe this was indeed implemented in #330? @andersy005 can you confirm this?

Yes, this is being taken care of by this pre-commit hook

https://github.com/xgcm/xgcm/blob/d38b6a4544561d7a1a11c72f55b08f5306a7ef75/.pre-commit-config.yaml#L18

**Comment by jbusecke** [comment]
Awesome. Closing this now.
