### ISSUE TITLE
Errors in difference and interpolation operation with ECCOv4r4

### ISSUE THREAD

**Issue by gmacgilchrist** [xgcm/xgcm#327]
With ECCOv4r4 output, attempting to:
1. Difference a scalar in either horizontal dimension (here, using `X`), then
2. Interpolate back to the center point

returns the following error:

```ValueError: 'j_g' not found in array dimensions ('time', 'face', 'j', 'i_g')```

Here is a minimum reproducible example (using data downloaded from the ECCO Drive):

```
import xarray as xr
from xgcm import Grid

rootdir = '/Users/graemem/Documents/research/data/ECCO/v4r4/'

localdir = 'nctiles_monthly/MXLDEPTH/*/'
filename = 'MXLDEPTH_*.nc'
ds = xr.open_mfdataset(rootdir+localdir+filename)
ds = ds.rename({'tile':'face'})

localdir = 'nctiles_grid/'
filename = 'ECCO-GRID.nc'
grid = xr.open_dataset(rootdir+localdir+filename)
grid = grid.rename({'tile':'face'})

ds = xr.merge([ds,grid])

# Define the connectivity between faces
# Copied directly from https://xgcm.readthedocs.io/en/latest/xgcm-examples/01_eccov4.html#Spatial-Derivatives:-Heat-Budget

face_connections = {'face':
                    {0: {'X':  ((12, 'Y', False), (3, 'X', False)),
                         'Y':  (None,             (1, 'Y', False))},
                     1: {'X':  ((11, 'Y', False), (4, 'X', False)),
                         'Y':  ((0, 'Y', False),  (2, 'Y', False))},
                     2: {'X':  ((10, 'Y', False), (5, 'X', False)),
                         'Y':  ((1, 'Y', False),  (6, 'X', False))},
                     3: {'X':  ((0, 'X', False),  (9, 'Y', False)),
                         'Y':  (None,             (4, 'Y', False))},
                     4: {'X':  ((1, 'X', False),  (8, 'Y', False)),
                         'Y':  ((3, 'Y', False),  (5, 'Y', False))},
                     5: {'X':  ((2, 'X', False),  (7, 'Y', False)),
                         'Y':  ((4, 'Y', False),  (6, 'Y', False))},
                     6: {'X':  ((2, 'Y', False),  (7, 'X', False)),
                         'Y':  ((5, 'Y', False),  (10, 'X', False))},
                     7: {'X':  ((6, 'X', False),  (8, 'X', False)),
                         'Y':  ((5, 'X', False),  (10, 'Y', False))},
                     8: {'X':  ((7, 'X', False),  (9, 'X', False)),
                         'Y':  ((4, 'X', False),  (11, 'Y', False))},
                     9: {'X':  ((8, 'X', False),  None),
                         'Y':  ((3, 'X', False),  (12, 'Y', False))},
                     10: {'X': ((6, 'Y', False),  (11, 'X', False)),
                          'Y': ((7, 'Y', False),  (2, 'X', False))},
                     11: {'X': ((10, 'X', False), (12, 'X', False)),
                          'Y': ((8, 'Y', False),  (1, 'X', False))},
                     12: {'X': ((11, 'X', False), None),
                          'Y': ((9, 'Y', False),  (0, 'X', False))}}}

# Create the grid object
xgrid = Grid(ds, periodic=False, face_connections=face_connections)

# Calculate gradients in field
dg = xgrid.diff(ds['MXLDEPTH'], 'X')
dgx = xgrid.interp(dg ,'X')
```

The `grid.diff` operation works as expected, but it is in attempting to interpolate back to the center point that there is some inconsistency in which dimension is recognized, returning the error above.

The examples in the `xgcm` docs are for v4r**3** (as opposed to r4 as I am working with here), but my understanding is that the grid (and therefore the connections) should be the same.

Am I making a trivial error, or has something important changed between r3 and r4? I'm using the latest version of `xgcm` from conda-forge.

**Comment by rabernat** [comment]
Thanks for reporting Graeme.

After your first interp call, the data is at the U velocity point. I think you may need to treat it as a vector at this point and call `diff_2d_vector`: https://xgcm.readthedocs.io/en/latest/xgcm-examples/01_eccov4.html#Spatial-Derivatives:-Heat-Budget
That would require also interpolating in Y.

The challenge here is that X and Y axes become confounded in the LLC grid. It all makes my head hurt a bit. But I'm not sure whether this a bug rather than a pathology of the LLC grid.

**Comment by gmacgilchrist** [comment]
Thanks for the response, Ryan. I did wonder if there was a trick with`diff_2d_vector`. I'll give that a go and report back.

**Comment by gmacgilchrist** [comment]
That's the one - thanks. It works to interpolate in both x and y, then take the difference as though they were vectors.

Working code:
```
# Calculate gradients in field
gx = xgrid.interp(ds['MXLDEPTH'], 'X')
gy = xgrid.interp(ds['MXLDEPTH'], 'Y',boundary='fill')
dg = xgrid.diff_2d_vector({'X':gx,'Y':gy},boundary='fill')
```
