### ISSUE TITLE
[BUG] xgcm.transport should check that the input is datarray

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#328]
Currently you can do something like: 
```python
...
grid.transform(ds, ...)
```

It then fails with some obscure dtype failure. We should have a check that the input is a dataarray. 

Just noting this here since that came up during the siparcs meeting 

cc @andersy005 @jdldeauna

**Comment by jbusecke** [comment]
Ill add a proper code example tomorrow. My brain is done for today

**Comment by andersy005** [comment]
It appears that the target levels are being checked in `input_handling` decorator, but `phi` and `theta` aren't being checked to make sure they are of the right type. 


https://github.com/xgcm/xgcm/blob/b68a4c70fdb8ade2e7462a958c810a07b0fbcfdb/xgcm/transform.py#L180-L190

**Comment by jbusecke** [comment]
Oh I see. Let me try to submit a PR fixing this.
