### ISSUE TITLE
[FEATURE] metrics object

### ISSUE THREAD

**Issue by dcherian** [xgcm/xgcm#342]
Brainstorming API for the new metrics object. Copying over from #199, I propose something like this in a new `metrics.py` file.

``` python

# in metrics.py
class Metrics(dict):
    def __setitem__(self, key, value):
        # do validation / alignment checks here
        # copy over Grid.set_metric
        super().__setitem__(key, value)

    def get_for(self, array: xr.DataArray, axes):
	 	""" Gets appropriate metric for dataarray 'array' and set of axes 'axes'.
		When metrics are not present, will attempt to interpolate existing metrics
		to the position of 'array' using Grid.interp_like.
		"""
        # copy over Grid.get_metric()
		pass
    

# in grid.py
from .metrics import Metrics

class Grid:
    
	def __init__(..., metrics=None, ...):
		self.metrics = Metrics()
		if metrics is not None:
    		# do assignment as in current __init__
			pass
    
inst = Grid()
print(inst.metrics)  # {}
inst.metrics["a"] = 10
inst.metrics["b"] = 20
print(inst.metrics)  # {a: 10, b: 20}
```

**Comment by jbusecke** [comment]
The important new use case to consider in my opinion is that we can now possibly 'overwrite' metrics.

Assume you have two metric-coordinates `dx_t` and `dx_e`. I would think in your example above one should be able to do:
```
inst.metrics['X'] = 'dx_t'
...something else...
inst.metrics['X'] = 'dx_e'
```
I think we need to make sure that:
a) At no time we have two dataarrays with the same dimensions in our Metric object
b) That we have some way to 'overwrite' a metric if we modified it. 
c, optional) I think it would be helpful if we could also pass dataarrays directly (this should be easy to implement, once the other parts work).

**Comment by jdldeauna** [comment]
This sounds great! Is it something like assigning `set_metrics` and `get_metric` to the `metrics.py` file, and then just making sure that `grid.py` imports these methods? I can work on a PR for this.

**Comment by dcherian** [comment]
I'm not sure this is really a good idea anymore. The current API seems fine to me. WDYT?

**Comment by jbusecke** [comment]
I would also defer this to a point where we have all worked with the current API. If we feel that more comlexity is needed we can add it then?

**Comment by jdldeauna** [comment]
Yeah, the current API works fine for me. Adding complexity later on if needed sounds good :)
