### ISSUE TITLE
Overeager stale bot?

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#347]
I am finding myself to reopen most of the autoclosed issues here. Maybe we want to have some more time elapse between marking as stale and closing? 
I am also wondering if we should include `bug` in the exempt labels?
@andersy005

**Comment by andersy005** [comment]
@jbusecke, the default number of days before an issue is marked stale is 60. We can definitely increase to a more reasonable value. What would you like the new default number of days to be? The list of available options is here: https://github.com/actions/stale#all-options

> I am also wondering if we should include bug in the exempt labels? 

👍🏽

**Comment by jbusecke** [comment]
Was it already 30 days since that darn thing warned us about stale issues? I think that is actually fine, I guess I just have to go through the rest of these.
