### ISSUE TITLE
conditional integrate

### ISSUE THREAD

**Issue by miniufo** [xgcm/xgcm#349]
I've recently tried to calculate the area enclosed by tracer contours.  I have a global tracer field `PTRACER01` like:
```python
<xarray.DataArray 'PTRACER01' (YC: 1600, XC: 3600)>
dask.array<getitem, shape=(1600, 3600), dtype=float32, chunksize=(1600, 3600), chunktype=numpy.ndarray>
Coordinates:
  * XC       (XC) >f4 0.05 0.15 0.25 0.35 0.45 ... 359.5 359.6 359.8 359.9 360.0
  * YC       (YC) >f4 -79.95 -79.85 -79.75 -79.65 ... 79.65 79.75 79.85 79.95
Attributes:
    standard_name:  PTRACER01_concentration
    long_name:      Concentration of PTRACER01
    units:          kg m-3
```

I also pre-define a set of contours `contours` from from its min to max values:
```python
<xarray.DataArray 'contours' (contour: 181)>
dask.array<add, shape=(181), dtype=float64, chunksize=(181), chunktype=numpy.ndarray>
Coordinates:
  * contour  (contour) float64 0.0 1.0 2.0 3.0 4.0 ... 177.0 178.0 179.0 180.0
```

In this case, the area enclosed by each contour would be:
```python
landsea = tracer - tracer + 1 # sea is 1 and land is nan

area = grid.integrate(landsea.where(tracer < contours))
```
So the `area` is a conditional integration over the region where `tracer < contours`, and it is a funtion of `contour`:
```python
<xarray.DataArray 'area' (contour: 181)>
dask.array<sum-aggregate, shape=(181), dtype=float32, chunksize=(181), chunktype=numpy.ndarray>
Coordinates:
  * contour  (contour) float64 0.0 1.0 2.0 3.0 4.0 ... 177.0 178.0 179.0 180.0
```

The thing is that the tracer is a large 2D (YC, XC) field, and `tracer < contours` becomes a 3D (YC, XC, contour) conditional mask array that is too big for my machine to allocate enough memory.

Do you guys have any elegant solution on this?  Do I need to write explicit loops like:
```python
for k in contours:
    sum[k] = 0
    for j in YC:
        for i in XC:
            if tracer[j, i] < contours [k]:
                sum[k] += landse[j, i] * dA[j, i]
```
to avoid the allocation of the `tracer < contour` mask array? (that would be sucks as losing the convenience of xarray)

**Comment by jbusecke** [comment]
I think [xhistogram](https://github.com/xgcm/xhistogram) does what you want!

**Comment by miniufo** [comment]
Wooo, that is a wonderful solution!  Didn't try xhistogram-thinking.  I'll give a try soon.  Thanks @jbusecke

**Comment by jbusecke** [comment]
No problem. There was just a new release that makes it perform a lot better too! I will close this here, if that is ok.
