### ISSUE TITLE
Directory structure?

### ISSUE THREAD

**Issue by jklymak** [xgcm/xgcm#36]
Hi Ryan,  

This looks extremely useful.

Just a few questions - what directory structure does `ddir` have?  Do you use `globalIO = TRUE` or do you have a directory for each tile?  i.e. `ddir+'/0000'`,  `ddir+'/0001'`, etc for all the tiles.

I make scant use of the Diagnostics package.  I assume if I wanted to use this, I'd want to start using it for more prosaic variables like 'U', 'W','PH' etc?

Is `xray` better than `xarray` or is `xarray` in the future?  

Do you run this on a supercomputer?  

Thanks!  Jody

**Comment by rabernat** [comment]
Jody--I'm glad you have found my obscure package. Its overall future is a bit uncertain, as there are [many](https://github.com/lesommer/oocgcm) [other](https://github.com/spencerahill/aospy) [similar](https://github.com/spencerahill/infinite-diff/) [packages](https://github.com/pwolfram/mpas_xarray_wrapper) in various stages of development. Many of us have been discussing how to collaborate more effectively on a general purpose xarray-based package for GCM analysis. Please join the discussion on our [hackpad](https://aospy.hackpad.com/) if you are interested. 

Right now the main practical utility of `xgcm` is to conveniently read MITgcm mds files into xarray format. The [example notebook](https://github.com/xgcm/xgcm/blob/master/example_notebooks/MITgcm_global_budgets.ipynb) shows how this is done. I also just updated the docs on the relevant function: [open_mdsdataset](http://xgcm.readthedocs.io/en/latest/api.html#xgcm.open_mdsdataset). I would be very interested to hear your feedback.

> what directory structure does ddir have? 

It is just the run directory of your MITgcm simulation. No subdirectories.

> Do you use globalIO = TRUE or do you have a directory for each tile?

It will only work for singlecpuio. It can't handle tiles in any way. (It would be great to add support for tiles--PRs welcome!)

> I assume if I wanted to use this, I'd want to start using it for more prosaic variables like 'U', 'W','PH' etc?

Yes, it will work fine for that. It knows how to interpret the "default output." However, it might complain if you don't have an `available_diagnostics.log` file. A hacky fix is to just copy a random one from any simulation into your directory.

> Is xray better than xarray or is xarray in the future?

Did you mean to say `xgcm`? `xarray` and `xray` are [the same thing](https://github.com/pydata/xarray/issues/704). `xgcm` depends on `xarray`. There is no choice to be made.

> Do you run this on a supercomputer?
Yes, I have, but until [dask.distributed](http://distributed.readthedocs.io/en/latest/) matures a bit more, it is not possible to scale beyond a single node.

**Comment by jklymak** [comment]
I think just getting mds files into xarray is a great contribution.  I'm a little uncertain exactly what you are doing - have you basically written a backend that mimics what the netcdf backend does, and therefore you don't write intermediary netcdf format - you simply read the mds data when xarray requests it?  If so, that's a fabulous abstraction.  

I'm seeing about setting xarray up on the cluster I use (haise.navo.hpc.mil).  

I don't see how dask would interact well with 256 sub-files spread among as many subdirectories.  But I don't really understand how it works.  is `singlecpuio` a big performance hit (well I guess I can try and see).  I always stored in tiles simply because I often wasn't interested in many of the tiles (boundary conditions, passive basins, etc).  However, if I am doing my work on the cluster anyway that savings doesn't really buy me anything.  So the only issue would be if it took 20 minutes to write out each time step instead of 20 seconds.

Glad that xray and xarray are exactly the same thing.  I assumed xray was an obsolete version of xarray.

Thanks a lot.  Jody

**Comment by rabernat** [comment]
> you simply read the mds data when xarray requests it? If so, that's a fabulous abstraction.

Yes. It is "lazy" in this sense.

>  is singlecpuio a big performance hit (well I guess I can try and see). 

This depends on your cluster and the nature of your filesystem. In my experience, it is a performance _improvement_ to have one process handle all the io if you are using a shared filesystem.

> I'm seeing about setting xarray up on the cluster I use (haise.navo.hpc.mil).

Don't even consider not using [conda](http://conda.pydata.org/). Complete environment specifications for xgcm can be found in the [ci directory](https://github.com/xgcm/xgcm/tree/master/ci).

I am really glad to have someone else trying this out, but I should warn you that the package is in a state of heavy churn and is extremely far from a stable api.

**Comment by jklymak** [comment]
> Don't even consider not using conda. Complete environment specifications for xgcm can be found in the ci directory.

Hmmm, doubt `haise` has conda (or pip, or...)

> I am really glad to have someone else trying this out, but I should warn you that the package is in a state of heavy churn and is extremely far from a stable api.

No problem... I've been warned.

**Comment by rabernat** [comment]
> Hmmm, doubt haise has conda (or pip, or...)

It can be done entirely in user space, with no need for system-wide installation of packages. (But of course still probably easier with sysadmin help.)

**Comment by jklymak** [comment]
Umm, yes it can.  Should have thought of that years ago!  These machines are so fancy, I don't quite realize they are just running RedHat underneath it all....

**Comment by rabernat** [comment]
I'll close this now. Feel free to open new issues as they arise.
