### ISSUE TITLE
[BUG] test_gcm_dataset.py is deprecated

### ISSUE THREAD

**Issue by jdldeauna** [xgcm/xgcm#365]
There is an available test for using GCMs (`test_gcm_dataset.py`) but it's marked as `deprecated`. Could it still be used, and is the [`GCMDataset`](https://github.com/xgcm/xgcm/blob/b5e9499249b045ca9a411ec756e1a7bbd21bca77/xgcm/test/test_gcm_dataset.py#L11) still available? Alternatively, is it advisable to write tests which use intake to download GCM datasets for testing, or would that add complexity we wouldn't want?

This is in connection to [adding sel and isel to xgcm](https://github.com/xgcm/xgcm/issues/200).

**Comment by TomNicholas** [comment]
I am actually removing this code as part of #368 - just because I wanted to call a new file `gridops.py` and this old code was in the way :sweat_smile: I might factor out the removal of this deprecated code into a separate PR though to simplify #368.
