### ISSUE TITLE
dask and map_overlap in the grid_ufunc refactor

### ISSUE THREAD

**Issue by TomNicholas** [xgcm/xgcm#378]
Continuing on from the discussion in #368 about how exactly to employ `xarray.apply_ufunc`, `dask.array.map_overlap`, `pad`, and the new grid_ufunc definitions to get clean dask graphs.

(@rabernat your notebook can live here)

**Comment by rabernat** [comment]
I made a notebook to explore this here: https://gist.github.com/rabernat/0135a7b03b46705da7877147a3736aa8

[NBViewer Version](https://nbviewer.jupyter.org/gist/rabernat/0135a7b03b46705da7877147a3736aa8?flush_cache=true)

Some take-home points:
- I think we mainly need to handle two cases differently.
  - When the array is contiguous along the core dimension, it's pretty straightforward
  - When the array is chunked along the core dimension, we need to call map_overlap with carefully constructed arguments
- Our pad function should probably be returning a numpy or dask array, not a DataArray. That will make it easier to compose with the low-level grid operation. But that's not what we currently do
  https://github.com/xgcm/xgcm/blob/f110c0718d68a7956fc603f36d1a3027acc53304/xgcm/grid.py#L1644

**Comment by TomNicholas** [comment]
This was closed by merging #380
