### ISSUE TITLE
endianness as an option for `xgcm.open_mdsdataset`

### ISSUE THREAD

**Issue by jklymak** [xgcm/xgcm#38]
OK, have running, but I am an apostate and save my mds data in my machine's native little endian (I'll be honest - the big-endian thing in mitgcm doesn't make sense to me when I bet 98% of the machines are native little endian).  Is there an easy path to add a switch to `xgcm.open_mdsdataset` to use native endian.  I see you have some of that machinery in there, but then the reading endian gets hardwired at some point.

Thanks!   Jody

**Comment by rabernat** [comment]
Should be quite easy. Let me give it a try.

**Comment by rabernat** [comment]
@jklymak do you know how to check out my fix (#39) to test it? I would like to know it actually works on little endian data (I don't have any) before merging. 
https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by jklymak** [comment]
Hmmm... that link says to click on "command line" but when I go to the pull request, there is nothing saying command line....

Is there a git link I can use; I've just been calling `pip install git+https://github.com/xgcm/xgcm.git`

**Comment by rabernat** [comment]
You first need to clone the master git repository and install it locally.

```bash
git clone https://github.com/xgcm/xgcm.git
cd xgcm
python setup.py develop
```

Once you have that working, you can pull down my branch
```bash
git checkout -b rabernat-fix_endian master
git pull https://github.com/rabernat/xgcm.git fix_endian
```

If you hit problems and this doesn't work for any reason, I will just merge it as is.

**Comment by jklymak** [comment]
It works for me!


`In [5]: ds = xgcm.open_mdsdataset(ddir,iters,deltaT=5,prefix=['U','V','W'],endian='<').chunk()
xgcm/mdsxray.py:273: UserWarning: Not sure what to do with rlev = L
  warnings.warn("Not sure what to do with rlev = " + rlev)

In [6]: ds
Out[6]:
<xarray.Dataset>
Dimensions:  (X: 1024, Xp1: 1024, Y: 256, Yp1: 256, Z: 400, Zl: 400, Zp1: 401, Zu: 400, time: 1)
Coordinates:
    YC       (Y, X) float64 202.8 202.8 202.8 202.8 202.8 202.8 202.8 202.8 ...
    YG       (Yp1, Xp1) float64 -2.842e-13 -2.842e-13 -2.842e-13 -2.842e-13 ...
    rA       (Y, X) float64 3.072e+05 3.035e+05 2.997e+05 2.96e+05 2.924e+05 ...
  * Xp1      (Xp1) float64 0.0 757.5 1.506e+03 2.245e+03 2.974e+03 3.695e+03 ...
    PHrefC   (Z) float64 49.05 147.2 245.2 343.4 441.5 539.6 637.6 735.8 ...
    PHrefF   (Zp1) float64 0.0 98.1 196.2 294.3 392.4 490.5 588.6 686.7 ...
    dxG      (Yp1, X) float64 757.5 748.2 738.9 729.8 720.8 711.9 703.1 ...
    dxC      (Y, Xp1) float64 752.8 752.8 743.5 734.4 725.3 716.3 707.5 ...
  * Zl       (Zl) float64 0.0 -10.0 -20.0 -30.0 -40.0 -50.0 -60.0 -70.0 ...`
