### ISSUE TITLE
open_mdsdataset fails for two-dimensional data

### ISSUE THREAD

**Issue by hugke729** [xgcm/xgcm#42]
Trying out xgcm for the first time and choose a 2D simulation to test out open_mdsdataset, but I get the following error
`ValueError: dimensions ('Yp1', 'Xp1') must have the same length as the number of data dimensions, ndim=1`

Using a 3D simulation works fine.

**Comment by rabernat** [comment]
Hey @hugke729, thanks for your feedback. Sorry for the delay in response--I am technically on vacation right now.

Can you clarify what you mean by 2D? Which dimension is missing?

I have successfully used open_mdsdataset with 2D (x and y) output.

**Comment by rabernat** [comment]
@hugke729: Could you zip your data (entire run directory) into a tar.gz file and post it online somewhere for me to download?

**Comment by hugke729** [comment]
I've put two run directories at the link below. The one that fails (internal_wave) and one that works (barotropic gyre).

https://www.dropbox.com/sh/znq2i47jdjlz2tw/AAA33KwM8mhbqXqM0q1mzk31a?dl=0

**Comment by rabernat** [comment]
@hugke729: I just wanted to give you a heads up that I have moved all of the mitgcm-specific features of xgcm into a new package called xmitgcm:
https://github.com/xgcm/xmitgcm
This move also includes a major refactor of the code. I am closing the mitgcm-specific issues here, but I would really appreciate your input on the new package. The new package should definitely handle this case with two-dimensional data correctly.

xgcm is going back to it's original mission: implementing finite-volume differential and integral operations on GCM grids (which is not specific to mitgcm).
