### ISSUE TITLE
[DOC] Documentation for grid ufunc refactor

### ISSUE THREAD

**Issue by TomNicholas** [xgcm/xgcm#423]
We need to start writing some documentation to cover the changes in the grid ufunc refactor (#344) effort.

I think with #418 the API is basically solidified, apart from some various keyword arguments (see some of the discussion in #414).

We definitely need a whole new page that explains:
1) What a grid ufunc is
2) How the signature is specified
3) Relationship to `xarray.apply_ufunc`
4) How to create and apply your own grid ufuncs
5) Some good examples

For the examples I can think of:
1) Simple differencing operations like we have in `gridops.py`
2) Advection schemes like Dhruv was implementing
3) Vector calculus operations (grad, curl, etc.)

It's important that these examples are strong and wide-ranging though, if we want people to actually use `@grid_ufunc` in their own code.

Any other ideas? Or more specific ideas? @rabernat @jbusecke ?

**Comment by TomNicholas** [comment]
It would also be useful to have input on how clear the documentation is from people that we hope to be using the `@grid_ufunc` feature, e.g. @NoraLoose ?

**Comment by jbusecke** [comment]
I think that it could be valuable to go through the effort of 'translating' some fortran source code example (from any given climate model) into a ufunc. I think this would be the most 'end-to-end' example with very high value for many users. It is a lot of work though...This could be weaved into @dhruvbalwada s example I guess.

**Comment by TomNicholas** [comment]
> I think that it could be valuable to go through the effort of 'translating' some fortran source code example (from any given climate model) into a ufunc.

That's a good idea - I would need a fortran snippet of a function that's simple enough though.

**Comment by dhruvbalwada** [comment]
This is what we were trying to code up the other day: https://github.com/MITgcm/MITgcm/blob/master/pkg/generic_advdiff/gad_c2_adv_x.F

**Comment by NoraLoose** [comment]
Hi @TomNicholas! Sure, I'm happy to help with the documentation. I need to catch up on the grid ufunc refactoring you have done. Let me know how I can help!

In case you are still looking for examples for the docs, Laplacian diffusion may be a relevant use case. It's not only used in fortran climate models, but it's also the base operation in gcm-filters. Here is an example code snippet:
https://github.com/ocean-eddy-cpt/gcm-filters/blob/bad651d5cc5443bc0a523ce59472351a4d1c7f7a/gcm_filters/kernels.py#L283-L301

**Comment by TomNicholas** [comment]
I really like [this breakdown for documentation](https://documentation.divio.com/), which theorizes that there are 4 types of documentation, along two axes, as shown in this diagram:

![image](https://user-images.githubusercontent.com/35968931/154104480-47a8582a-0835-41cd-a272-45c527743bf7.png)

> In case you are still looking for examples for the docs, Laplacian diffusion may be a relevant use case.

Thanks for this @NoraLoose .

I think that all of these

> What a grid ufunc is
How the signature is specified
Relationship to xarray.apply_ufunc
How to create and apply your own grid ufuncs

are "explanation", whilst the various examples are either "tutorial" or "how-to", depending on their complexity. (So first-order finite difference could be part of a "tutorial", but Laplacian diffusion would definitely be an advanced "how-to".) The "reference" is the auto-generated API docs.

My plan is to start with "explanation", then move on to more advanced examples in "how-to", for which I expect to have to enable/debug various features as I add examples. Tutorial is perhaps the last thing to do given that this is already a feature intended for advanced users.

**Comment by TomNicholas** [comment]
All the functions in [Dhruv's notebook here](https://github.com/ocean-transport/channel-coarse-grain-pipeline/blob/main/modules/MITgcm_advection_schemes.py) could make good examples if re-written as grid_ufuncs.

**Comment by TomNicholas** [comment]
Closed by #431 and #464, unless anyone has any other big suggestions for docs pages.
