### ISSUE TITLE
[FEATURE] CITATION.cff file

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#449]
I just wanted to cite xgcm and got [this](https://zenodo.org/record/6097129/export/hx#.YjFMhy-B30o) from zenodo. Many of the names are not properly documented.

I would love to have proper names for the bibtex files, and think we can achieve this with the CITATION.cff file. 

I will include all contributors on this if they want. So @rabernat @timothyas @jdldeauna @andersy005 @TomNicholas @ocefpaf @jrbourbeau @raphaeldussin @dcherian @rcaneill @bradyrx @anirban89 @Swanson-Hysell @willirath @apatlpo @dhruvbalwada @navidcy @leouieda @yz3062 @roxyboy, if you would like to be included in the xgcm citation, could you please respond with your **full name + orcid** below? 

Cheers

**Comment by navidcy** [comment]
Navid C. Constantinou 0000-0002-8149-4094

**Comment by dcherian** [comment]
Deepak A. Cherian 0000-0002-6861-8734

**Comment by roxyboy** [comment]
Takaya Uchida; 0000-0002-8654-6009

**Comment by andersy005** [comment]
Anderson Banihirwe 0000-0001-6583-571X

**Comment by anirban89** [comment]
Anirban Sinha *0000-0002-7122-3549*

**Comment by yz3062** [comment]
Yuxin Zhou 0000-0002-3523-8524

**Comment by rcaneill** [comment]
Romain Caneill  0000-0001-6649-4275

**Comment by leouieda** [comment]
Leonardo Uieda  0000-0001-6123-9515

**Comment by willirath** [comment]
Willi Rath 0000-0003-1951-8494

**Comment by ocefpaf** [comment]
Filipe Fernandes 0000-0003-4165-2913

**Comment by dhruvbalwada** [comment]
Dhruv Balwada 0000-0001-6632-0187

**Comment by TomNicholas** [comment]
Thomas Nicholas 0000-0002-2176-0530

**Comment by raphaeldussin** [comment]
Raphael Dussin 0000-0003-4004-4553

**Comment by jdldeauna** [comment]
Josephine Dianne Deauna 0000-0002-0733-9440

**Comment by apatlpo** [comment]
Aurélien Ponte 0000-0002-0252-6028

**Comment by jbusecke** [comment]
Thanks to everyone. I have added a file in #450. Please double check if the information is correct. 

I have chosen the order based on whatever github does to order contributors, I hope everyone is ok with that? 

Still missing @timothyas @jrbourbeau @Swanson-Hysell and @bradyrx. Ill leave this open for a while longer.

**Comment by Swanson-Hysell** [comment]
My contribution was minor to the point that it doesn't make sense for me to be included on such a citation. Thanks for checking.

**Comment by jbusecke** [comment]
Thanks for letting me know @Swanson-Hysell. And I just want to say that any contribution is very much appreciated, no matter how large or small!

**Comment by timothyas** [comment]
Timothy Andrew Smith 0000-0003-4463-6126

(sorry for the delay)

**Comment by jbusecke** [comment]
One more ping for @jrbourbeau and @bradyrx.

**Comment by jbusecke** [comment]
I am going to merge the cff file in now and close this. If @jrbourbeau or @bradyrx want to be added, I can do that at any time later.

**Comment by jrbourbeau** [comment]
Apologies for the delayed reply. My zenodo info is given here https://github.com/xgcm/xhistogram/pull/72#issuecomment-982231044. But also, no worries if you've pushed things out already
