### ISSUE TITLE
[BUG] Decorated lines don't show up in docs

### ISSUE THREAD

**Issue by TomNicholas** [xgcm/xgcm#455]
Opening this to keep track of this very irritating [bug in ipython's sphinx extension](https://github.com/ipython/ipython/issues/13531).

The bug basically strips all lines beginning with `@` from ipython code before building the sphinx docs page, which is a problem when you're [trying to document a decorator](https://github.com/xgcm/xgcm/pull/431).

We either have to fix this upstream in ipython (which I am trying to do) or just demote the relevant code blocks to be static, pre-written inputs and outputs, instead of real code that runs each time the docs are created.

**Comment by TomNicholas** [comment]
Should be fixed by https://github.com/ipython/ipython/pull/13612, and then we need to pin ipython to the latest version after it's released.

**Comment by jbusecke** [comment]
Heroic effort @TomNicholas!

**Comment by rabernat** [comment]
![gif](https://media3.giphy.com/media/6UFgdU9hirj1pAOJyN/giphy.gif?cid=ecf05e475s1ptnp0ackkht8fv93bf61s94rewev0v2i0vl10&rid=giphy.gif)

**Comment by jbusecke** [comment]
Seems like one of the [tests](https://github.com/ipython/ipython/runs/5840872498?check_suite_focus=true) is failing. Let me know if there is a way I can help move this forward. I believe we cannot release until this is fixed?

**Comment by TomNicholas** [comment]
Well my ipython PR has been there for 20 days with no response... (It's not blocking on that test failure.) I will comment there now, but otherwise we could just change the ipython blocks to be static (so run them locally to get the inputs and outputs, then copy-paste in, and fix once ipython merges and releases).

**Comment by jbusecke** [comment]
Sounds like a good plan.

**Comment by TomNicholas** [comment]
Actually the other thing we could do is pin our docs environment to my dev version of ipython, like @rabernat did when reviewing #431. That might be easier as a temporary solution actually.

**Comment by jbusecke** [comment]
Oh yes. I like that. But we should definitely track this in an issue, so we do not forget to switch it back.

**Comment by TomNicholas** [comment]
We might also be able to get around this by executing code cells using the [jupyter-sphinx](https://jupyter-sphinx.readthedocs.io/en/latest/) extension instead of the ipython directive extension, as presumably that would no longer call the code which contains the bug. (see https://github.com/pydata/xarray/issues/6620 for various options.)
