### ISSUE TITLE
Combining variables with different dimension sizes

### ISSUE THREAD

**Issue by jdldeauna** [xgcm/xgcm#462]
Hi! I'm combining variables with different dimension sizes into one grid object:

```python
cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6-noQC.json"
col = intake.open_esm_datastore(cat_url)
cat = col.search(table_id='Omon',experiment_id='historical',
             variable_id=['wmo','no3'], grid_label='gn', member_id='r1i1p1f1',source_id='MPI-ESM1-2-LR')
mpi = cat.to_dataset_dict(
        zarr_kwargs={'consolidated':True, 'decode_times': True, 'use_cftime': True},
        preprocess=combined_preprocessing,
        aggregate=False)
wmo = mpi['CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.wmo.gn.gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/wmo/gn/v20190710/.nan.20190710.good.none.none']
no3 = mpi['CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.no3.gn.gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/no3/gn/v20190710/.nan.20190710.good.none.none']
wmo = wmo.rename({'lev': 'lev_w'})
ds_subset = xr.merge([no3, wmo], compat='override')
grid_wmo = Grid(
    ds_subset,
    coords={
        'X':{'center':'x'},
        'Y':{'center':'y'},
        'Z':{'center':'lev', 'right':'lev_w'},
    },
)
```

but the diff operation fails with the ff error:
```python
dn_dz = grid_wmo.diff(ds_subset.no3,'Z')

ValueError: conflicting sizes for dimension 'lev_w': length 40 on the data but length 41 on coordinate 'lev_w'

dw_dz = grid_wmo.diff(ds_subset.wmo,'Z')

ValueError: conflicting sizes for dimension 'lev': length 41 on the data but length 40 on coordinate 'lev'
```

When I try to make separate grid objects per variable the ff error appears:
```python
grid_wmo = Grid(
    wmo,
    coords={
        'X':{'center':'x'},
        'Y':{'center':'y'},
        'Z':{'right':'lev_w'},
    },
)
dw_dz = grid_wmo.diff(wmo.wmo,'Z')

File /srv/conda/envs/notebook/lib/python3.9/site-packages/xgcm/grid.py:273, in Axis._neighbor_binary_func(self, da, f, to, boundary, fill_value, boundary_discontinuity, vector_partner, keep_coords)
    271 position_from, dim = self._get_position_name(da)
    272 if to is None:
--> 273     to = self._default_shifts[position_from]
    275 if boundary is None:
    276     boundary = self.boundary

KeyError: 'right'
```
```python
grid_no3 = Grid(
    no3,
    coords={
        'X':{'center':'x'},
        'Y':{'center':'y'},
        'Z':{'center':'lev'},
    },
    periodic=False,
    boundary='extrapolate',
)
dn_dz = grid_no3.diff(no3.no3,'Z')

KeyError: 'center'
```
<br>
Is there a different way to combine variables with different dimension sizes into one grid object?

**Comment by TomNicholas** [comment]
All variables end up being stored under one xarray dataset inside `grid._ds`, which is where this restriction is coming from. 

Why exactly are you trying to do this?

**Comment by jdldeauna** [comment]
Mainly to calculate total transport (`wmo` is vertical transport). The variable I used for the example is `no3`, but I was also trying to combine it with `umo` and `vmo` (horizontal transport).

Creating a grid object with just one variable results in the error I showed above, so I'm thinking it means that when using the `diff` operation, both `center` and `right` positions need to be defined. But when I try to include `lev` as center this error appears:
```python 
cat_url = "https://storage.googleapis.com/cmip6/pangeo-cmip6-noQC.json"
col = intake.open_esm_datastore(cat_url)
cat = col.search(table_id='Omon',experiment_id='historical',
             variable_id=['wmo','umo'], grid_label='gn', member_id='r1i1p1f1',source_id='MPI-ESM1-2-LR')
mpi = cat.to_dataset_dict(
        zarr_kwargs={'consolidated':True, 'decode_times': True, 'use_cftime': True},
        preprocess=combined_preprocessing,
        aggregate=False)
wmo = mpi['CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.wmo.gn.gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/wmo/gn/v20190710/.nan.20190710.good.none.none'].rename({'lev': 'lev_w'})
umo = mpi['CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.umo.gn.gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/umo/gn/v20200909/.nan.20200909.good.none.none']
wmo.coords['lev'] = umo.lev

wmo 
Dimensions: (x: 256, y: 220, lev_w: 41, bnds: 2, time: 1980, vertex: 4, lev: 40)
Data variables: wmo (time, lev_w, y, x)

grid_wmo = Grid(wmo,coords={'X':{'center':'x',},'Y':{'center':'y'},'Z':{'center':'lev','right':'lev_w'},},)
dw_dz = grid_wmo.diff(wmo.wmo,'Z')

ValueError: conflicting sizes for dimension 'lev': length 41 on the data but length 40 on coordinate 'lev'
```

**Comment by jbusecke** [comment]
Hey Dianne, can you post the 'raw' dataset representations here (e.g. `mpi['CMIP.MPI-M.MPI-ESM1-2-LR.historical.r1i1p1f1.Omon.wmo.gn.gs://cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Omon/wmo/gn/v20190710/.nan.20190710.good.none.none']` and the other). 

In general I would expect the `wmo` variable to be on an 'outer' axis position (so have one additional element and the wmo value 'bracket' each tracer value). It seems like that is actually the case here, so you might be good by providing `'outer'` instead of `'right'` here: 
```python
'Z':{'center':'lev','outer':'lev_w'},
```
Basically if any coordinate has one value less or more than the tracer, you will always have to specify it as `'inner'` or `'outer'` respectively. [This schematic](https://xgcm.readthedocs.io/en/latest/grids.html#axes-and-positions) always helps me to think through these setups. 

BTW, this is only such an annoying problem since the CMIP6 models do not provide a 'properly' staggered grid output. I would really like to solve this problem specifically in cmip6_pp. Should we schedule a time next week and work on getting a full grid setup from there? So you dont have to go through these painful steps here to get your science done?

**Comment by jdldeauna** [comment]
Assigning `lev_w` as `outer` worked, thanks @jbusecke ! And yes, meeting up would be great, thank you :)
