### ISSUE TITLE
[BUG] black issue in the pre-commit CI

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xgcm#471]
Seeing this error
```
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repojiyk8rxh/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```
 pop up in a few places: [Main branch](https://github.com/xgcm/xgcm/actions/runs/2185346538) and other PRs like [#450](https://github.com/xgcm/xgcm/runs/6065530414?check_suite_focus=true)

Seems like we either need to bump the black version or pin click (see here: https://github.com/psf/black/issues/2964). Any thoughts on this @TomNicholas ?

**Comment by TomNicholas** [comment]
Just bump black then?
