### ISSUE TITLE
xarray attr

### ISSUE THREAD

**Issue by bderembl** [xgcm/xgcm#60]
I am trying to use an xarray loaded via xmitgcm:
```
ds = open_mdsdataset(dir0,iters='all',prefix=['U','V','Eta'])
grid = xgcm.Grid(ds)
```

it seems that grid is empty
from what I see in grid.py, it only returns the summary such that _axes is empty
I looked at comodo.py in get_axis_coords() and in fact my field doen't have an 'axis' attribute: here is the line where I suspect the issue is:
`        axis = ds[d].attrs.get('axis')` 

here is a summary of ds['XC']
Out[34]: 
<xarray.DataArray 'XC' (XC: 1120)>
array([-65.958   , -65.873993, -65.789993, ...,  27.873995,  27.957998,
        28.042002], dtype=float32)
Coordinates:
  * XC       (XC) >f4 -65.958 -65.874 -65.79 -65.706 -65.622 -65.538 -65.454 ...
Attributes:
    long_name:      longitude
    units:          degrees_east
    coordinate:     YC XC
    standard_name:  longitude

**Comment by rabernat** [comment]
I think you probably need to update your xmitgcm installation. These attributes were added only very recently, and we have not made a release since then (but probably should!).

If you installed via pip, run `pip uninstall xmitgcm`.

Then
```bash
git clone https://github.com/xgcm/xmitgcm.git
cd xmitgcm
python setup.py install
```

**Comment by rabernat** [comment]
FYI, I just released a bugfix release of xmitgcm (0.2.1), so if you installed via pip, you can upgrade with `pip install xmitgcm --upgrade`.

**Comment by bderembl** [comment]
awesome. 
sorry I didn't realize I was using an old version

**Comment by rabernat** [comment]
Let me know if this fixed your issue.

**Comment by bderembl** [comment]
yes it did
