### ISSUE TITLE
Vorticity and Okubo-Weiss Criterion

### ISSUE THREAD

**Issue by Herpinemmanuel** [xgcm/xgcm#65]
I am trying to use an array loaded by xmitgcm : 

_ds = open_mdsdataset(dir0,iters='all',prefix=['U','V'])
grid = xgcm.Grid(ds)_

# Subject 
I want to calculate the Okubo Weiss Criterion : W = s1²+s2²-vorticity²
With :

**#s1² = (du/dx-dv/dy)²**

_S1 = grid.diff(ds.U.where(ds.hFacW>0)*ds.dyC, 'X') + grid.diff(ds.V.where(ds.hFacW>0)*ds.dxC, 'Y'))/ds.rAz
S1_carree = S1**2_

**#S2² = (dv/dx+du/dy)²**

_S2 = (grid.diff(ds.V.where(ds.hFacS>0)*ds.dyC, 'X') + grid.diff(ds.U.where(ds.hFacW>0)*ds.dxC, 'Y'))/ds.rAz
S2_carree = S2**2_

**#Vorticity² = (dv/dx-du/dy)²**

_Vorticity = (-grid.diff(ds.U.where(ds.hFacW>0)*ds.dxC, 'Y') + grid.diff(ds.V.where(ds.hFacS>0)*ds.dyC, 'X'))/ds.rAz
Vor_carree = Vorticity**2

Okubo_weiss_criterion = Sn_carree + Ss_carree - Vor_carree_

# Issue :

When  i try to calculate without the mask :  grid.diff(ds.U * ds.dyC, 'X')/ds.r
-> it returns : ValueError: the new name 'XG' already exists
When i try : grid.diff(ds.U * ds.dyC, 'Y')/ds.r
->it returns : ValueError: the new name 'YG' already exists

When i try : grid.diff(ds.U * ds.dxC, 'X')/ds.r
-> it works
When i try : grid.diff(ds.U * ds.dxC, 'Y')/ds.r
-> it works

I dont really understand why i can't differentiate by 'dxC' on Y axe  and by 'dyC' on X axe.. 
Did i used it badly ?

**Comment by rabernat** [comment]
Hi @Herpinemmanuel. Thanks for giving this package a try! I definitely think we can resolve your issue.

Can you confirm which exact part of the expression is causing the error? Does `ds.U * ds.dyC` work? Can you also post the full stack trace of the error?

**Comment by Herpinemmanuel** [comment]
# Program used :

import numpy as np
import matplotlib.pyplot as plt
import xgcm
from xmitgcm import open_mdsdataset

dir0 = '/homedata/bderembl/runmit/test_southatlgyre3'
ds0 = open_mdsdataset(dir0,iters='all',prefix=['U','V'])
grid = xgcm.Grid(ds0)

A = ds0.U * ds0.dyC
print(A)

Sn = (grid.diff(ds0.U.where(ds0.hFacW>0) * ds0.dyC, 'X') + grid.diff(ds0.V.where(ds0.hFacW>0) * ds0.dxC, 'Y'))/ds0.rAz
Sn_carree = Sn**2

# Part of the expression causing error :

With only :  A = ds0.U * ds0.dyC , it works !
 I confirm that the error is caused by **grid.diff()**

# Full stack trace of the error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/eherpin/MITgcm_c66g/verification/southatlgyre/analysis/Cas_6_NOK/6_Okubo_Weiss/B_Okubo_issue.py in <module>()
     15 
     16 # sn² = (du/dx-dv/dy)²
---> 17 Sn = (grid.diff(ds0.U.where(ds0.hFacW>0)*ds0.dyC, 'X') + grid.diff(ds0.V.where(ds0.hFacW>0)*ds0.dxC, 'Y'))/ds0.rAz
     18 Sn_carree = Sn**2
     19 

/home/eherpin/.conda/envs/my_conda/lib/python3.4/site-packages/xgcm-0.0.0-py3.4.egg/xgcm/grid.py in diff(self, da, axis)
    150             # TODO: generalize to higher order interpolation
    151             return shift*(data_right - data_left)
--> 152         return self._neighbor_binary_func(da, axis, interp_function)
    153 
    154 

/home/eherpin/.conda/envs/my_conda/lib/python3.4/site-packages/xgcm-0.0.0-py3.4.egg/xgcm/grid.py in _neighbor_binary_func(self, da, axis, f)
    222                     da_i = da_i.isel(**{ax_name: slice(1,None)})
    223 
--> 224         da_i = _replace_dim(da_i, ax_name, new_coord)
    225         return da_i
    226 

/home/eherpin/.conda/envs/my_conda/lib/python3.4/site-packages/xgcm-0.0.0-py3.4.egg/xgcm/grid.py in _replace_dim(da, olddim, newdim, drop)
    252     """
    253 
--> 254     da_new = da.rename({olddim: newdim.name})
    255     # note that alignment along a dimension is skipped when you are overriding
    256     # the relevant coordinate values

/home/eherpin/.conda/envs/my_conda/lib/python3.4/site-packages/xarray/core/dataarray.py in rename(self, new_name_or_name_dict)
    823         """
    824         if utils.is_dict_like(new_name_or_name_dict):
--> 825             dataset = self._to_temp_dataset().rename(new_name_or_name_dict)
    826             return self._from_temp_dataset(dataset)
    827         else:

/home/eherpin/.conda/envs/my_conda/lib/python3.4/site-packages/xarray/core/dataset.py in rename(self, name_dict, inplace)
   1535                                  "variable or dimension in this dataset" % k)
   1536             if v in self and k != v:
-> 1537                 raise ValueError('the new name %r already exists' % v)
   1538 
   1539         variables = OrderedDict()

ValueError: the new name 'XG' already exists

**Comment by rabernat** [comment]
Can you please do `print(ds0.U * ds0.dyC)`?

Also, for including code or fixed-width text in github discussion, you can place it in [block quotes](https://help.github.com/articles/creating-and-highlighting-code-blocks/) using three backquote characters.

**Comment by Herpinemmanuel** [comment]
When i do print(ds0.U * ds0.dyc) : 

>>><xarray.DataArray (time: 203, Z: 60, YC: 200, XG: 560, YG: 200, XC: 560)>
dask.array<mul, shape=(203, 60, 200, 560, 200, 560), dtype=float32, chunksize=(1, 60, 200, 560, 200, 560)>
Coordinates:
>>>  * YC       (YC) >f4 -43.9271 -43.7814 -43.6357 -43.4899 -43.3442 -43.1985 ...
>>>  * XG       (XG) >f4 -66.0 -65.8372 -65.6744 -65.5116 -65.3488 -65.186 ...
>>>  * Z        (Z) >f4 -5.20833 -15.625 -26.0417 -36.4583 -46.875 -57.2917 ...
    dyG      (YC, XG) >f4 16201.7 16201.7 16201.7 16201.7 16201.7 16201.7 ...
    dxC      (YC, XG) >f4 13035.1 13035.1 13035.1 13035.1 13035.1 13035.1 ...
    rAw      (YC, XG) >f4 2.11191e+08 2.11191e+08 2.11191e+08 2.11191e+08 ...
    PHrefC   (Z) >f4 51.0938 153.281 255.469 357.656 459.844 562.031 664.219 ...
    drF      (Z) >f4 10.4167 10.4167 10.4167 10.4167 10.4167 10.4167 10.4167 ...
    hFacW    (Z, YC, XG) >f4 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1.0 1.0 1.0 1.0 1.0 ...
    iter     (time) int64 0 2160 4320 6480 8640 10800 12960 15120 17280 ...
>>>  * time     (time) int64 0 2160 4320 6480 8640 10800 12960 15120 17280 ...
>>>  * YG       (YG) >f4 -44.0 -43.8543 -43.7085 -43.5628 -43.4171 -43.2714 ...
>>>  * XC       (XC) >f4 -65.9186 -65.7558 -65.593 -65.4302 -65.2674 -65.1047 ...
    dyC      (YG, XC) >f4 16201.7 16201.7 16201.7 16201.7 16201.7 16201.7 ...
    rAs      (YG, XC) >f4 2.10932e+08 2.10932e+08 2.10932e+08 2.10932e+08 ...
    dxG      (YG, XC) >f4 13019.1 13019.1 13019.1 13019.1 13019.1 13019.1 ...

**Comment by rabernat** [comment]
Ok, I understand the problem.

Look at the dimensions of that DataArray: `(time: 203, Z: 60, YC: 200, XG: 560, YG: 200, XC: 560)`. This is because  `ds0.U` and `ds0.dyC` have different dimensions along both the X and Y axes. According to normal [xarray broadcasting rules](http://xarray.pydata.org/en/stable/computation.html#broadcasting-by-dimension-name), when you multiply the two, these dimensions are broadcast against each other to create an enormous array which includes all the different dimensions. This is definitely _not_ what you want to do.

When you try to take the diff with xgcm, it complains because the target dimension `XG` already exists. This is the correct behavior. So this is not really a bug in xgcm.

You need to multiply `ds0.U` by a variable with the same dimensions if you want to avoid broadcasting.

Does this make sense?

**Comment by rabernat** [comment]
FYI, I would construct the strain as
```python
strain = (diff(ds0.U * ds0.dyG, 'X') - diff(ds0.V * ds0.dxG, 'Y')) / ds0.rA
```
This will be at the center point, not the vorticity point.

**Comment by Herpinemmanuel** [comment]
I didn't know about xarray broadcasting rules and  with it , your explanation does make sense.
Thank you very much for your time !
