### ISSUE TITLE
Differencing along time axis

### ISSUE THREAD

**Issue by jetesdal** [xgcm/xgcm#72]
I am trying to calculate time differentials using monthly snapshots of sea surface height (ETAN), temperature and salinity using xgcm. For an example, please see:
https://github.com/jetesdal/ecco_analysis/blob/master/xgcm_grid_diff_time.ipynb

Calculating the time difference using `grid.diff(da, 'T')` raises an error (KeyError: 'center').

The problem seems to be that the grid object from `xgcm.Grid()` includes only one time coordinate.
`T Axis (not periodic):`
`  * center   time (11)`

This is different from the spatial axes. Currently, xgcm does not include the concept of cell centers and edges (as it is described in http://xgcm.readthedocs.io/en/latest/grids.html#grids) for the time dimension.

**Comment by jbusecke** [comment]
Was this ever solved? I cant access the link anymore. So ill go ahead and close this for now.
