### ISSUE TITLE
better names for inferred coordinates?

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#80]
I'm not sure I like `longitude_inferred` as the name for the new face coordinate.

Maybe we can come up with something based on the cell possitions. For example `longitude_edge` or `longitude_face` or `longitude_midpoint` etc. etc.

Or we could keep xgcm's internal lexicon and use 'longitude_left`, `longitude_inner`, etc.

cc @jbusecke

**Comment by jbusecke** [comment]
Thats totally possible. I am not sure if this module is able to digest the 'inner'/'outer' positions...have to look into that.

**Comment by jbusecke** [comment]
#78 Now has a differnet naming scheme. It takes the old name of the dimension/coordinate and adds the xgcm position to it.

**Comment by rabernat** [comment]
This is closed by #85
