### ISSUE TITLE
xgcm organization over data quota

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#82]
Because of all the data files we are storing in git repos, we have exceeded our bandwidth in the xgcm organization

![image](https://user-images.githubusercontent.com/1197350/32474289-db5a87f2-c339-11e7-8b1c-5d85e6e58a9b.png)

We need to find a better way to host the datasets to avoid this problem in the future!

cc @jbusecke

**Comment by jbusecke** [comment]
Seems like Atlassian is not charging for bandwidth like github is. Would it be easy to upload it over there and point to it?

BTW how stupid is the pricing model based on bandwidth? Punishing repos that are popular? No likey at all!

**Comment by rabernat** [comment]
It is only for git lfs. We should get rid of that for this project as it is
not super necessary.

-R

**Comment by jbusecke** [comment]
I guess that is true. Just for reference and other projects that need large binaries it might be worth exploring an option that charges for storage only, and doesnt brake all builds of collaborators once the package has been cloned/forked a bunch of times. 

Could you announce it over here once a solution is implemented? Then i can restart my other builds over at travis.
