### ISSUE TITLE
more typos in autogenerate docs

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#86]
I wish I had caught all these before merging #85, but I am eager to move fast.

Here are the rendered versions on rtd:
http://xgcm.readthedocs.io/en/latest/grid_generation.html
http://xgcm.readthedocs.io/en/latest/api.html#autogenerate

I recommend the following

- [ ] link explicitly to the API docs from your grid_generation doc page. (You can see how to do this in the other doc pages.)
- [ ] re-run your example from grid_generation.md to make the variable names consistent with the new naming conventions
- [ ] fix the typos in the module docstrings

Not urgent, just wanted to document this via an issue.

cc @jbusecke

**Comment by jbusecke** [comment]
I need to update the docs still, but thanks for the fast merge on #96. I really needed that functionality back!

**Comment by rabernat** [comment]
Will you add an example notebook working with real observational data?

**Comment by jbusecke** [comment]
Yes that was the plan. Now that the generation of the 'outer' position works, it is easy to calculate grid distances. That is what I use this module for most and ill add a nice example, emphasizing the effect of proper area weighting like here (http://xarray.pydata.org/en/stable/examples/monthly-means.html) and maye a gradient calculation? Any other ideas that would be helpful to demonstrate?

Can you assign me to this issue? Its easier to keep track of my todos that way.

**Comment by rabernat** [comment]
For some reason I can't assign you.

**Comment by jbusecke** [comment]
Should we integrate this into a larger "Improved docs" Milestone?

**Comment by jbusecke** [comment]
This was covered by #106. Closing
