### ISSUE TITLE
autograd package

### ISSUE THREAD

**Issue by spencerahill** [xgcm/xgcm#87]
Just came across this for first time: https://github.com/HIPS/autograd

Looks pretty cool.  Could be used for derivatives on the sphere?  Potentially useful here? ...

cc @spencerkclark

**Comment by rabernat** [comment]
Auto differentiation is very cool and a hot topic right now given it’s relevance for machine learning. But it’s a separate problem from taking spatial gradients.

**Comment by spencerahill** [comment]
Ah ok, thanks.  The machine learning tie-in would explain the >2k stars!

I'll close this then.
