### ISSUE TITLE
Strategies for indexing and selecting 

### ISSUE THREAD

**Issue by willirath** [xgcm/xgcm#95]
I'm working with NEMO output wrapped into an xarray dataset understood by `xgcm.Grid`. (And it is great to finally be able to just focus on the calculation at hand without all the C-grid boilerplate that's usually necessary to handle the data!)

In working with these data sets, I struggle with a simple way of subsetting the data across different dimensions belonging to the same axis. With a dataset like this:

```python
print(ds)
```
```
<xarray.Dataset>
Dimensions:   (t: 24, x_c: 720, x_r: 720, y_c: 509, y_r: 509, z_c: 46, z_l: 46)
Coordinates:
  * z_c       (z_c) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ...
  * z_l       (z_l) float64 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5 10.5 ...
  * y_c       (y_c) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ...
  * y_r       (y_r) float64 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5 10.5 11.5 ...
  * x_c       (x_c) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ...
  * x_r       (x_r) float64 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5 10.5 11.5 ...
    depth_c   (z_c) float64 dask.array<shape=(46,), chunksize=(23,)>
    depth_l   (z_l) float64 dask.array<shape=(46,), chunksize=(23,)>
    llat_cc   (y_c, x_c) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llat_cr   (y_c, x_r) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llat_rc   (y_r, x_c) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llat_rr   (y_r, x_r) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llon_cc   (y_c, x_c) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llon_cr   (y_c, x_r) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llon_rc   (y_r, x_c) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
    llon_rr   (y_r, x_r) float32 dask.array<shape=(509, 720), chunksize=(509, 720)>
  * t         (t) datetime64[ns] 2008-01-16T12:00:00 2008-02-15 ...
Data variables:
    T  (t, z_c, y_c, x_c) float32 dask.array<shape=(24, 46, 509, 720), chunksize=(1, 23, 509, 720)>
    U  (t, z_c, y_c, x_r) float32 dask.array<shape=(24, 46, 509, 720), chunksize=(1, 23, 509, 720)>
    V  (t, z_c, y_r, x_c) float32 dask.array<shape=(24, 46, 509, 720), chunksize=(1, 23, 509, 720)>
720)>
```
where `T` lives on the tracer grid points `(t, z_c, y_c, x_c)`, `U` lives on the zonal-velocity grid points `(t, z_c, y_c, x_r)`, and `V` lives on the meridional-velocity grid points `(t, z_c, y_r, x_c)`, to sub-set to, e.g., the 30°S...30°N, I'd naively go for something like
```python
sel_llat_cc = (abs(ds.coords["llat_cc"]) <= 30)
sel_llat_cr = (abs(ds.coords["llat_cr"]) <= 30)
sel_llat_rc = (abs(ds.coords["llat_rc"]) <= 30)

T_sel = ds.T.where(sel_llat_cc, drop=True)
U_sel = ds.T.where(sel_llat_cr, drop=True)
V_sel = ds.T.where(sel_llat_rc, drop=True)
```
but this not necessarily results in equally shaped `T_sel`, `U_sel`, and `V_sel`.

Constructing the selectors for the `U`, and `V` grid from the tracer grid is a conceivable but not very elegant way:
```python
sel_llat_cc = (abs(ds.coords["llat_cc"]) <= 30)

sel_llat_cr = ds.llat_cr.astype("bool")
sel_llat_cr.data = sel_llat_cc.data

sel_llat_rc = ds.llat_rc.astype("bool")
sel_llat_rc.data = sel_llat_rc.data
```

How do you usually solve this?

**Comment by rabernat** [comment]
First, let me say I'm very glad that your have xgcm working with NEMO! I would love to see an example of how you are using it.

You question is fundamentally about xarray, not xgcm. Therefore I recommend you raise it on the xarray issue tracker. I don't think that xarray supports this sort of indexing right now. However, I believe that this is one of the goals of the salem package:
https://salem.readthedocs.io/en/v0.1.1/examples.html

This function in particular looks like it does what you want:
https://salem.readthedocs.io/en/v0.1.1/generated/salem.DatasetAccessor.subset.html#salem.DatasetAccessor.subset

I recommend creating the xgcm.Grid *after* you have done the subsetting.

**Comment by jbusecke** [comment]
Yes, it is awesome that xgcm is more widely used! 

I took a look at salem and it looks very cool, but perhaps there is a point to be made about xgcm "internal" selection.

First of all, there are two issues here:
1) @willirath is trying to subset based on 2-dimensional coordinates. Which becomes difficult when coordinates are not purely in lat-lon format (in this case they seem to be). Salem looks incredibly helpful to figure this out.

2) The same problem exists when coordinates are 1-dimensional (I ran into this a while ago).

The selection purely based on location is not aware of the relation between the grid variables, resulting in uneven array size in a case like this:

Imagine the case where we have tracer cells at the center and cell faces on the right. Now if for some unlucky reason the tracer cell is located at 29.9 and the cell face at 30.1, they would be separated, leading to the problem described above. 

Within xgcm we know which cells of the u grid belong to cells of the tracer grid, and could implement logic to account for that.

I could imagine a function like e.g. 
```python
grid.subset(yc = slice(5,10), reference='center')
```
This would take the center position (aka the center cell) as a reference, use the actual coordinate limits to subset and then figure out the appropriate index values to subset each dataarray with the other dimensions. This would also preserve the 'outer' convention, which might be desirable to export result back to other workflows.

What do you think?

**Comment by rabernat** [comment]
Good points Julius. But I'm not convinced there is a big problem if you get uneven array size when subsetting? With a subsetted domain, you are going to have to impose some boundary conditions anyway for diff / interp at the edges. Presumably the results you get at the edges of a subsetted domain will be thrown away anyway.

> Imagine the case where we have tracer cells at the center and cell faces on the right. Now if for some unlucky reason the tracer cell is located at 29.9 and the cell face at 30.1, they would be separated, leading to the problem described above.

In this case, the tracer would still be at the `center` position and the fluxes at the `inner` position. Everything would still work the same, except for operations right at the edge, for which you would have to specify some boundary conditions.

I push back only because I am very conservative about adding features to xgcm. There are very few people working on it and maintaining it right now. It is great at what it does. Let's keep it as simple as possible.

**Comment by jbusecke** [comment]
I hear you. And the boundary condition argument is perfectly valid.
Just to reiterate, I think this is not a fundamental deficiency, we can work around it. It would just be a user-friendliness feature. 

You are doing most of the work on this (incredibly appreciated!) and if you think it would draw focus from the core functions lets not do it. 

@willirath I would be interested how your experience with salem goes. Please keep us posted.

**Comment by willirath** [comment]
> First, let me say I'm very glad that your have xgcm working with NEMO! I would love to see an example of how you are using it.

My approach is currently hosted on our institute's Git server: <https://git.geomar.de/willi-rath/xorca> It basically automates <http://xgcm.readthedocs.io/en/latest/grid_generation.html> in a single preprocessing function for `xarray.open_mfdataset`.

**Comment by jbusecke** [comment]
`grid_generation` was written to recompute grid variables that are not available (mostly for observational products). 

I have written something like this before for GFDL MOM5:
```
def create_minimal_coords_ds(ds_mm, **kwargs):
    """Create a minimal set of coordinates from a mesh-mask dataset.

    This creates `"central"` and `"right"` grid points for the horizontal grid
    and `"central"` and `"left"` grid points in the vertical.

    """
    N_z = len(ds_mm.coords["z"])
    N_y = len(ds_mm.coords["y"])
    N_x = len(ds_mm.coords["x"])

    coords = {
        "z_c": (["z_c", ], np.arange(1, N_z + 1),
                {"axis": "Z"}),
        "z_l": (["z_l", ], np.arange(1, N_z + 1) - 0.5,
                {"axis": "Z", "c_grid_axis_shift": - 0.5}),
        "y_c": (["y_c", ], np.arange(1, N_y + 1),
                {"axis": "Y"}),
        "y_r": (["y_r", ], np.arange(1, N_y + 1) + 0.5,
                {"axis": "Y", "c_grid_axis_shift": 0.5}),
        "x_c": (["x_c", ], np.arange(1, N_x + 1),
                {"axis": "X"}),
        "x_r": (["x_r", ], np.arange(1, N_x + 1) + 0.5,
                {"axis": "X", "c_grid_axis_shift": 0.5})
    }

    return xr.Dataset(coords=coords)
```
I always thought it would be good to create a central repo with this sort of boilerplate code for various models as preset. Although I experienced quite a bit of variability in the naming of even x and y coordinates depending on which group saved the output...not sure if the nemo coordinates are better behaved.

Liebe Gruesse nach Kiel!

**Comment by willirath** [comment]
I've never tried salem.  Will let you know if I get to it.

> > Imagine the case where we have tracer cells at the center and cell faces on the right. Now if for some unlucky reason the tracer cell is located at 29.9 and the cell face at 30.1, they would be separated, leading to the problem described above.
> 
> In this case, the tracer would still be at the center position and the fluxes at the inner position. Everything would still work the same, except for operations right at the edge, for which you would have to specify some boundary conditions.

That's an interesting point.f `xgcm.Grid` automatically infers that a dimension is `"inner"` if it is shorter by one, then all my problems might just boil down to thinking about boundary conditions.  I'll definitely play with this.

> It is great at what it does. Let's keep it as simple as possible.

I totally agree with that!

**Comment by rabernat** [comment]
FYI, I have a PR in progress (#93) which will bypass the need to set these attributes and just let you pass the axis information directly to `Grid` as a dictionary.

**Comment by willirath** [comment]
> I always thought it would be good to create a central repo with this sort of boilerplate code for various models as preset. Although I experienced quite a bit of variability in the naming of even x and y coordinates depending on which group saved the output...not sure if the nemo coordinates are better behaved.

The newer the model output, the more consistent the NEMO data becomes. But there still is a _lot_ of ambiguity. [Nemo itself offers 9 different ways of writing grid info to disk.](http://forge.ipsl.jussieu.fr/nemo/browser/branches/2018/dev_r8864_nemo_v3_6_ZTILDE/NEMOGCM/NEMO/OPA_SRC/DOM/domwri.F90#L58) Even within a single group, it is very difficult to "just open the mesh-mask file" and be sure to have all the info.

So maintaining adapters for automatic grid-generation just working for all the models might be a really frustrating experience. (On the other hand: Seeing the enormous progress of Pangeo makes me hope that there soon will be a _lot_ more people using the Pangeo stack with many different models.)

**Comment by jbusecke** [comment]
> Nemo itself offers 9 different ways of writing grid info to disk.
Yikes. Yeah maybe that is bit too much then. I think a good way to proceed is to document your method as a use case on pangeo. That would have helped me a lot in the (hypothetical) event that I would have to use NEMO data.

**Comment by jbusecke** [comment]
Can we close this?

**Comment by willirath** [comment]
Yes.
